--------------------------------------------------------
--  DDL for Function FUNC_AMBIT_RISPLUS
--------------------------------------------------------

  CREATE OR REPLACE FUNCTION "SINTAGMA_U"."FUNC_AMBIT_RISPLUS" (InstalacioID IN NUMBER) RETURN INT IS

    AMBITO INT;
    SQL_AUX varchar2(100);
    
BEGIN
   
   RETURN QUERY
   
--   DBMS_OUTPUT.PUT_LINE ('INICIO -----> ' || InstalacioID);

     
   SELECT AMBIT.AMBIT_ID INTO AMBITO FROM Z_E002_INSTALACIO_AMBIT_PART AMBIT  WHERE AMBIT.INSTALACIOID = InstalacioID;
   
   --RETURN QUERY  EXECUTE 'SELECT AMBIT.AMBIT_ID FROM Z_E002_INSTALACIO_AMBIT_PART AMBIT  WHERE AMBIT.INSTALACIOID = ' || InstalacioID;
    


--DBMS_OUTPUT.PUT_LINE ('FINAL -----> ' || AMBITO);

--   RETURN AMBITO;

EXCEPTION
WHEN NO_DATA_FOUND THEN
DBMS_OUTPUT.PUT_LINE('no data found -----> !' || InstalacioID);
WHEN TOO_MANY_ROWS THEN
    DBMS_OUTPUT.PUT_LINE('TOO_MANY_ROWS ---> !' || InstalacioID );
    SQL_AUX := 'SELECT AMBIT.AMBIT_ID  FROM Z_E002_INSTALACIO_AMBIT_PART AMBIT WHERE AMBIT.INSTALACIOID =' || InstalacioID;
    DBMS_OUTPUT.PUT_LINE('AMBITO ---> ' || SQL_AUX );

RETURN null;
   
END FUNC_AMBIT_RISPLUS;

/
