--------------------------------------------------------
--  DDL for View VIEW_CERCA_ACTES_INV_CONF
--------------------------------------------------------

  CREATE OR REPLACE FORCE VIEW "SINTAGMA_U"."VIEW_CERCA_ACTES_INV_CONF" ("RESULT_ID", "RESULT_CLASSIFICACIO", "RESULT_PRIORITAT", "RESULT_ENTITAT", "RESULT_NOM_COMPLET", "RESULT_ESTAT_CONFIRMACIO", "RESULT_DATA_RESPOSTA", "RESULT_DATA_RESPOSTA_ORDERBY", "RESULT_VIA_RESPOSTA", "RESULT_ASSISTENCIA", "FILTER_CLASSIFICACIO", "FILTER_PRIORITAT", "FILTER_ENTITAT", "FILTER_NOM_COMPLET", "FILTER_DATA_RESPOSTA", "FILTER_VIA_RESPOSTA", "FILTER_ESTAT_CONFIRMACIO", "FILTER_ACTE", "FILTER_ASSISTENCIA") AS 
  SELECT
	conv.ID AS RESULT_ID,
	conv.CODI_CLASSIFICACIO || ' ' || conv.NOM_CLASSIFICACIO AS RESULT_CLASSIFICACIO,
	conv.PRIORITAT AS RESULT_PRIORITAT,
	conv.ENTITAT AS RESULT_ENTITAT,
	conv.NOM || ' ' || conv.COGNOM1 || ' ' || conv.COGNOM2 AS RESULT_NOM_COMPLET,
	est_conf.DESCRIPCIO AS RESULT_ESTAT_CONFIRMACIO,
	fn_convert_to_vn (TO_CHAR (conv.DATA_CONFIRMACIO,'DD/MM/YYYY') ) AS RESULT_DATA_RESPOSTA,
	fn_convert_to_vn (TO_CHAR (conv.DATA_CONFIRMACIO,'YYYY/MM/DD') ) AS RESULT_DATA_RESPOSTA_ORDERBY,
	via_resp.DESCRIPCIO AS RESULT_VIA_RESPOSTA,
	DMDA.DESCRIPCIO AS RESULT_ASSISTENCIA,
	fn_convert_to_vn(conv.CODI_CLASSIFICACIO || ' ' || conv.NOM_CLASSIFICACIO) AS FILTER_CLASSIFICACIO,
	fn_convert_to_vn(conv.PRIORITAT) AS FILTER_PRIORITAT,
	fn_convert_to_vn(conv.entitat) AS FILTER_ENTITAT,
	fn_convert_to_vn(conv.nom || ' ' || conv.cognom1 || ' ' || conv.cognom2 ) AS FILTER_NOM_COMPLET,
	fn_convert_to_vn (TO_CHAR (conv.DATA_CONFIRMACIO,'DD/MM/YYYY') ) AS FILTER_DATA_RESPOSTA,
	conv.TIPUS_VIA_RESPOSTA_ID AS FILTER_VIA_RESPOSTA,
	conv.ESTAT_CONFIRMACIO_ID AS FILTER_ESTAT_CONFIRMACIO,
	acte.ID AS FILTER_ACTE,
	conv.DECISIO_ASSISTENCIA_ID AS FILTER_ASSISTENCIA
FROM CONVIDAT conv
	INNER JOIN ACTE acte ON acte.ID = conv.ACTE_ID
	INNER JOIN DM_ESTAT_CONFIRMACIO est_conf ON est_conf.ID = conv.ESTAT_CONFIRMACIO_ID
	LEFT OUTER JOIN DM_TIPUS_VIA_RESPOSTA via_resp ON via_resp.ID = conv.TIPUS_VIA_RESPOSTA_ID
	LEFT OUTER JOIN DM_DECISIO_ASSISTENCIA DMDA ON DMDA.ID = conv.DECISIO_ASSISTENCIA_ID
WHERE 1=1
and DATA_ENVIAMENT_INVITACIO is not NULL
;
