--------------------------------------------------------
--  DDL for View VIEW_CERCA_ACTES_INV_ASSIS
--------------------------------------------------------

  CREATE OR REPLACE FORCE VIEW "SINTAGMA_U"."VIEW_CERCA_ACTES_INV_ASSIS" ("RESULT_ID", "RESULT_NOM_COMPLET", "RESULT_ENTITAT", "RESULT_CLASSIFICACIO", "RESULT_PRIORITAT", "RESULT_ASSISTENCIA", "FILTER_NOM_COMPLET", "FILTER_ENTITAT", "FILTER_CLASSIFICACIO", "FILTER_PRIORITAT", "FILTER_ACTE", "FILTER_ASSISTENCIA") AS 
  SELECT
C.ID AS RESULT_ID,
C.nom || ' ' || C.cognom1 || ' ' || C.cognom2 AS RESULT_NOM_COMPLET,
C.entitat AS RESULT_ENTITAT,
C.CODI_CLASSIFICACIO || ' ' || C.NOM_CLASSIFICACIO AS RESULT_CLASSIFICACIO,
C.prioritat AS RESULT_PRIORITAT,
DMDA.DESCRIPCIO AS RESULTAT_ASSISTENCIA,
fn_convert_to_vn(C.nom || ' ' || C.cognom1 || ' ' || C.cognom2 ) AS FILTER_NOM_COMPLET,
fn_convert_to_vn(C.entitat) AS FILTER_ENTITAT,
fn_convert_to_vn(C.CODI_CLASSIFICACIO || ' ' || C.NOM_CLASSIFICACIO) AS FILTER_CLASSIFICACIO,
fn_convert_to_vn(C.prioritat) AS FILTER_PRIORITAT,
A.ID AS FILTER_ACTE,
C.DECISIO_ASSISTENCIA_ID AS FILTER_ASSISTENCIA
FROM CONVIDAT C
INNER JOIN ACTE A ON A.ID = C.ACTE_ID
LEFT OUTER JOIN DM_DECISIO_ASSISTENCIA DMDA ON DMDA.ID = C.DECISIO_ASSISTENCIA_ID
WHERE 1=1
and C.ESTAT_CONFIRMACIO_ID IN (2,3)
;
