--------------------------------------------------------
--  DDL for View VIEW_CERCA_CONTACTES_TRUCABLES
--------------------------------------------------------

  CREATE OR REPLACE FORCE VIEW "SINTAGMA_U"."VIEW_CERCA_CONTACTES_TRUCABLES" ("RESULT_ID", "RESULT_NOM_SUBJECTE", "RESULT_COGNOM1_SUBJECTE", "RESULT_COGNOM2_SUBJECTE", "RESULT_ENTITAT_ID", "RESULT_ENTITAT", "RESULT_NUMERO_PRINCIPAL", "RESULT_CARREC", "FILTER_AMBIT_ID", "FILTER_CODI_VISIBILITAT", "FILTER_NOM_SUBJECTE", "FILTER_COGNOM1_SUBJECTE", "FILTER_COGNOM2_SUBJECTE") AS 
  SELECT
	-- Columns to display in frontend
	con.ID AS RESULT_ID,
	vsub.RESULT_NOM AS RESULT_NOM_SUBJECTE,
	vsub.RESULT_COGNOM1 AS RESULT_COGNOM1_SUBJECTE,
	vsub.RESULT_COGNOM2 AS RESULT_COGNOM2_SUBJECTE,
	con.ENTITAT_ID AS RESULT_ENTITAT_ID,
	ent.DESCRIPCIO AS RESULT_ENTITAT,
	contel.NUMERO AS RESULT_NUMERO_PRINCIPAL,
	carr.DESCRIPCIO AS RESULT_CARREC,
	-- Columns from which to filter the search results
	con.AMBIT_ID AS FILTER_AMBIT_ID,
	vis.CODI AS FILTER_CODI_VISIBILITAT,
	vsub.FILTER_NOM AS FILTER_NOM_SUBJECTE,
	vsub.FILTER_COGNOM1 AS FILTER_COGNOM1_SUBJECTE,
	vsub.FILTER_COGNOM2 AS FILTER_COGNOM2_SUBJECTE
FROM CONTACTE con
	INNER JOIN VIEW_SUBJECTE vsub ON vsub.ID = con.SUBJECTE_ID
	INNER JOIN DM_VISIBILITAT vis ON vis.ID = con.VISIBILITAT_ID
	LEFT OUTER JOIN DM_ENTITAT ent ON ent.ID = con.ENTITAT_ID
	LEFT OUTER JOIN CONTACTE_TELEFON contel ON contel.CONTACTE_ID = con.ID AND contel.ES_PRINCIPAL = 1
	LEFT OUTER JOIN DM_CARREC carr ON carr.ID = con.CARREC_ID
WHERE 1=1
	AND con.data_esborrat IS NULL
	
;
