--------------------------------------------------------
--  DDL for View VIEW_CERCA_ACTES
--------------------------------------------------------

  CREATE OR REPLACE FORCE VIEW "SINTAGMA_U"."VIEW_CERCA_ACTES" ("RESULT_ID", "RESULT_TITOL", "RESULT_TECNIC", "RESULT_PETICIONARI", "RESULT_LLOC", "RESULT_ESTAT", "RESULT_DATA_INICI", "RESULT_DATA_INICI_ORDERBY", "RESULT_DATA_FI", "RESULT_DATA_FI_ORDERBY", "FILTER_NOM_ID", "FILTER_DATA_INICI", "FILTER_DATA_FI", "FILTER_TECNIC", "FILTER_PETICIONARI", "FILTER_LLOC", "FILTER_TIPUS", "FILTER_ESTAT") AS 
  SELECT A.ID AS RESULT_ID,
	A.TITOL AS RESULT_TITOL,  
	A.TECNIC_NOM AS RESULT_TECNIC,
	P.DESCRIPCIO AS RESULT_PETICIONARI,
	L.DESCRIPCIO AS RESULT_LLOC,
	EA.DESCRIPCIO AS RESULT_ESTAT,
	fn_convert_to_vn(TO_CHAR (AG.DATA_INICI_ACTE,'DD/MM/YYYY')) AS RESULT_DATA_INICI,
	fn_convert_to_vn(TO_CHAR (AG.DATA_INICI_ACTE,'YYYY/MM/DD')) AS RESULT_DATA_INICI_ORDERBY,
	fn_convert_to_vn(TO_CHAR (AG.DATA_FI_ACTE,'DD/MM/YYYY')) AS RESULT_DATA_FI,
	fn_convert_to_vn(TO_CHAR (AG.DATA_FI_ACTE,'YYYY/MM/DD')) AS RESULT_DATA_FI_ORDERBY,
	fn_convert_to_vn(A.ID || ' ' || A.TITOL) AS FILTER_NOM_ID,
	fn_convert_to_vn(TO_CHAR (AG.DATA_INICI_ACTE,'DD/MM/YYYY')) AS FILTER_DATA_INICI,
	fn_convert_to_vn(TO_CHAR (AG.DATA_FI_ACTE,'DD/MM/YYYY')) AS FILTER_DATA_FI,
	A.TECNIC_MATRICULA AS FILTER_TECNIC,
	A.PETICIONARI_ID AS FILTER_PETICIONARI,
	AG.LLOC_ID AS FILTER_LLOC,
	A.TIPUS_ACTE_ID AS FILTER_TIPUS,
	A.ESTAT_ACTE_ID AS FILTER_ESTAT
FROM ACTE A
INNER JOIN ENTRADA_AGENDA AG ON AG.ELEMENT_PRINCIPAL_ID = A.ELEMENT_PRINCIPAL_ID
LEFT OUTER JOIN DM_LLOC L ON L.ID = AG.LLOC_ID
INNER JOIN DM_ESTAT_ACTE EA ON EA.ID = A.ESTAT_ACTE_ID
INNER JOIN DM_TIPUS_ACTE TA ON TA.ID = A.TIPUS_ACTE_ID
LEFT OUTER JOIN DM_PETICIONARI P ON P.ID = A.PETICIONARI_ID
;
