--------------------------------------------------------
--  DDL for View VIEW_CERCA_ACTES_CONTACTES
--------------------------------------------------------

  CREATE OR REPLACE FORCE VIEW "SINTAGMA_U"."VIEW_CERCA_ACTES_CONTACTES" ("RESULT_ID", "RESULT_TITOL", "RESULT_CLASSIFICACIO", "RESULT_ENTITAT", "RESULT_DATA_ENTRADA", "RESULT_DATA_ENTRADA_ORDERBY", "FILTER_SUBJECTE") AS 
  SELECT
	CN.ID AS RESULT_ID,
	A.TITOL AS RESULT_TITOL,
	v_dm_class.RESULT_CLASSIFICACIO AS RESULT_CLASSIFICACIO,
	CN.ENTITAT AS RESULT_ENTITAT,
	fn_convert_to_vn (TO_CHAR (A.DATA_ENTRADA,'DD/MM/YYYY')) AS RESULT_DATA_ENTRADA,
	fn_convert_to_vn (TO_CHAR (A.DATA_ENTRADA,'YYYY/MM/DD')) AS RESULT_DATA_ENTRADA_ORDERBY,
	C.SUBJECTE_ID AS FILTER_SUBJECTE
FROM
	CONVIDAT CN
	INNER JOIN ACTE A ON A.ID = CN.ACTE_ID
	INNER JOIN CONTACTE_CLASSIFICACIO CC ON CC.ID = CN.CONTACTE_CLASSIFICACIO_ID
	INNER JOIN CONTACTE C ON C.ID = CN.CONTACTE_ID
	INNER JOIN SUBJECTE S ON S.ID = C.SUBJECTE_ID
	INNER JOIN VIEW_DM_CLASSIFICACIO v_dm_class ON v_dm_class.ID = CC.CLASSIFICACIO_ID
	INNER JOIN DM_DECISIO_ASSISTENCIA DMDA ON DMDA.ID = CN.DECISIO_ASSISTENCIA_ID
WHERE
	DMDA.CODI = 'SI' AND A.ESTAT_ACTE_ID != 3

;
