--------------------------------------------------------
--  DDL for View VIEW_RELACIO_ENTRADA
--------------------------------------------------------

  CREATE OR REPLACE FORCE VIEW "SINTAGMA_U"."VIEW_RELACIO_ENTRADA" ("RESULT_ID", "RESULT_TITULAR", "RESULT_CARREC", "RESULT_ENTITAT", "RESULT_DATA_RELACIO", "RESULT_RESPONSABLE", "RESULT_EXTRACTE", "FILTER_TIPUS_ELEMENT_ID", "FILTER_DATA_RELACIO") AS 
  SELECT
  
  -- Columns to display in frontend
	ep.ID AS RESULT_ID,
    tf.NOM AS RESULT_TITULAR,
    tf.CARREC AS RESULT_CARREC,
    tf.ENTITAT AS RESULT_ENTITAT,
	ep.DATA_RELACIO_ENTRADA  AS RESULT_DATA_RELACIO,
	ep.NOM_USUARI_RESPONSABLE AS RESULT_RESPONSABLE,
	asp.DESCRIPCIO AS RESULT_EXTRACTE,
	-- Columns from which to filter the search results
	ep.TIPUS_ELEMENT_ID AS FILTER_TIPUS_ELEMENT_ID,
	fn_convert_to_vn (TO_CHAR (ep.data_relacio_entrada,'DD/MM/YYYY') ) AS filter_data_relacio
FROM ELEMENT_PRINCIPAL ep
INNER JOIN TITULAR_FORA tf ON tf.ASPECTE_ID = EP.ASPECTE_ID
INNER JOIN ASPECTE asp ON asp.ID = ep.ASPECTE_ID

WHERE 1=1
	AND ep.DATA_ESBORRAT IS NULL
	AND ep.ES_RELACIO_ENTRADA = 1

;
