--------------------------------------------------------
--  DDL for View VIEW_CERCA_ACTES_INV_CONV
--------------------------------------------------------

  CREATE OR REPLACE FORCE VIEW "SINTAGMA_U"."VIEW_CERCA_ACTES_INV_CONV" ("RESULT_ID", "RESULT_NOM_COMPLET", "RESULT_ENTITAT", "RESULT_CLASSIFICACIO", "RESULT_PRIORITAT", "RESULT_DATA_ENV_INV", "RESULT_DATA_ENV_INV_ORDERBY", "FILTER_NOM_COMPLET", "FILTER_ENTITAT", "FILTER_CLASSIFICACIO", "FILTER_PRIORITAT", "FILTER_ACTE") AS 
  SELECT
C.ID AS RESULT_ID,
C.nom || ' ' || C.cognom1 || ' ' || C.cognom2 AS RESULT_NOM_COMPLET,
C.entitat AS RESULT_ENTITAT,
C.CODI_CLASSIFICACIO || ' ' || C.NOM_CLASSIFICACIO AS RESULT_CLASSIFICACIO,
C.prioritat AS RESULT_PRIORITAT,
fn_convert_to_vn(TO_CHAR (C.DATA_ENVIAMENT_INVITACIO,'DD/MM/YYYY')) AS RESULT_DATA_ENV_INV,
fn_convert_to_vn(TO_CHAR (C.DATA_ENVIAMENT_INVITACIO,'YYYY/MM/DD')) AS RESULT_DATA_ENV_INV_ORDERBY,
fn_convert_to_vn(C.nom || ' ' || C.cognom1 || ' ' || C.cognom2) AS FILTER_NOM_COMPLET,
fn_convert_to_vn(C.entitat) AS FILTER_ENTITAT,
fn_convert_to_vn(C.CODI_CLASSIFICACIO || ' ' || C.NOM_CLASSIFICACIO) AS FILTER_CLASSIFICACIO,
fn_convert_to_vn(C.prioritat) AS FILTER_PRIORITAT,
A.ID AS FILTER_ACTE
FROM CONVIDAT C
INNER JOIN ACTE A ON A.ID = C.ACTE_ID
WHERE 1=1
;
