--------------------------------------------------------
--  DDL for View VIEW_ELEMENTS_RELACION
--------------------------------------------------------

  CREATE OR REPLACE FORCE VIEW "SINTAGMA_U"."VIEW_ELEMENTS_RELACION" ("RESULT_EP_ID", "RESULT_ASPECTE_ID", "RESULT_EXTRACTE", "RESULT_DATA_ASSENTAMENT", "RESULT_NOM_USUARI_RESPONSABLE", "FILTER_EXTRACTE", "FILTER_AMBIT_ID") AS 
  SELECT
	ep.ID AS RESULT_EP_ID,
	asp.ID AS RESULT_ASPECTE_ID,
	asp.DESCRIPCIO AS RESULT_EXTRACTE,
	asp.DATA_ASSENTAMENT AS RESULT_DATA_ASSENTAMENT,
	ep.NOM_USUARI_RESPONSABLE AS RESULT_NOM_USUARI_RESPONSABLE,
	FN_CONVERT_TO_VN(asp.DESCRIPCIO) AS FILTER_EXTRACTE,
	asp.AMBIT_ID AS FILTER_AMBIT_ID
FROM ELEMENT_PRINCIPAL ep
	INNER JOIN ASPECTE asp ON asp.ID = ep.ASPECTE_ID
WHERE 1=1
	AND ep.DATA_ESBORRAT IS NULL

;
