--------------------------------------------------------
--  DDL for Sequence SEQ_DM_TIPOLOGIA_CLASSIFICACIO
--------------------------------------------------------

   CREATE SEQUENCE  "SINTAGMA_U"."SEQ_DM_TIPOLOGIA_CLASSIFICACIO"  MINVALUE 0 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 312 NOCACHE  NOORDER  NOCYCLE ;
