--------------------------------------------------------
--  Ref Constraints for Table A0_ANNEX_INCIDENT
--------------------------------------------------------

  ALTER TABLE "SINTAGMA_U"."A0_ANNEX_INCIDENT" ADD CONSTRAINT "A0_FKANNEX_INC01" FOREIGN KEY ("INCIDENT_ID")
	  REFERENCES "SINTAGMA_U"."A0_INCIDENTS_ACTE" ("ID") ENABLE;
  ALTER TABLE "SINTAGMA_U"."A0_ANNEX_INCIDENT" ADD CONSTRAINT "A0_FKANNEX_INC02" FOREIGN KEY ("DOCUMENT_ID")
	  REFERENCES "SINTAGMA_U"."A0_DOCUMENT" ("ID") ENABLE;
  ALTER TABLE "SINTAGMA_U"."A0_ANNEX_INCIDENT" ADD CONSTRAINT "A0_FKANNEX_INC03" FOREIGN KEY ("TIPUS_SUPORT_ID")
	  REFERENCES "SINTAGMA_U"."A0_DM_TIPUS_SUPORT" ("ID") ENABLE;
