--------------------------------------------------------
--  Ref Constraints for Table A0_ANNEX_ASPECTE
--------------------------------------------------------

  ALTER TABLE "SINTAGMA_U"."A0_ANNEX_ASPECTE" ADD CONSTRAINT "A0_FKANNEX_ASPE70609" FOREIGN KEY ("ASPECTE_ID")
	  REFERENCES "SINTAGMA_U"."A0_ASPECTE" ("ID") ENABLE;
  ALTER TABLE "SINTAGMA_U"."A0_ANNEX_ASPECTE" ADD CONSTRAINT "A0_FKANNEX_ASPE75374" FOREIGN KEY ("TIPUS_SUPORT_ID")
	  REFERENCES "SINTAGMA_U"."A0_DM_TIPUS_SUPORT" ("ID") ENABLE;
  ALTER TABLE "SINTAGMA_U"."A0_ANNEX_ASPECTE" ADD CONSTRAINT "A0_FKANNEX_ASPE98704" FOREIGN KEY ("DOCUMENT_ID")
	  REFERENCES "SINTAGMA_U"."A0_DOCUMENT" ("ID") ENABLE;
