--------------------------------------------------------
--  Ref Constraints for Table A0_ANNEX_REGISTRE
--------------------------------------------------------

  ALTER TABLE "SINTAGMA_U"."A0_ANNEX_REGISTRE" ADD CONSTRAINT "A0_FKANNEX_REGI550428" FOREIGN KEY ("DOCUMENT_ID")
	  REFERENCES "SINTAGMA_U"."A0_DOCUMENT" ("ID") ENABLE;
  ALTER TABLE "SINTAGMA_U"."A0_ANNEX_REGISTRE" ADD CONSTRAINT "A0_FKANNEX_REGI863017" FOREIGN KEY ("REGISTRE_ID")
	  REFERENCES "SINTAGMA_U"."A0_REGISTRE" ("ID") ENABLE;
