--------------------------------------------------------
--  Ref Constraints for Table A0_ACOMPANYANT
--------------------------------------------------------

  ALTER TABLE "SINTAGMA_U"."A0_ACOMPANYANT" ADD CONSTRAINT "A0_FKACOMPANYANT01" FOREIGN KEY ("TRACTAMENT_ID")
	  REFERENCES "SINTAGMA_U"."A0_DM_TRACTAMENT" ("ID") ENABLE;
  ALTER TABLE "SINTAGMA_U"."A0_ACOMPANYANT" ADD CONSTRAINT "A0_FKACOMPANYANT02" FOREIGN KEY ("CONTACTE_ID")
	  REFERENCES "SINTAGMA_U"."A0_CONTACTE" ("ID") ENABLE;
