--------------------------------------------------------
--  Ref Constraints for Table A0_ACCIO
--------------------------------------------------------

  ALTER TABLE "SINTAGMA_U"."A0_ACCIO" ADD CONSTRAINT "A0_FKACCIO171138" FOREIGN KEY ("ASPECTE_ID")
	  REFERENCES "SINTAGMA_U"."A0_ASPECTE" ("ID") DISABLE;
  ALTER TABLE "SINTAGMA_U"."A0_ACCIO" ADD CONSTRAINT "A0_FKACCIO382248" FOREIGN KEY ("PAS_ACCIO_ID")
	  REFERENCES "SINTAGMA_U"."A0_DM_PAS_ACCIO" ("ID") ENABLE;
  ALTER TABLE "SINTAGMA_U"."A0_ACCIO" ADD CONSTRAINT "A0_FKACCIO632433" FOREIGN KEY ("ELEMENT_PRINCIPAL_ID")
	  REFERENCES "SINTAGMA_U"."A0_ELEMENT_PRINCIPAL" ("ID") ENABLE;
  ALTER TABLE "SINTAGMA_U"."A0_ACCIO" ADD CONSTRAINT "A0_FKACCIO838514" FOREIGN KEY ("SUBTIPUS_ACCIO_ID")
	  REFERENCES "SINTAGMA_U"."A0_DM_SUBTIPUS_ACCIO" ("ID") ENABLE;
  ALTER TABLE "SINTAGMA_U"."A0_ACCIO" ADD CONSTRAINT "A0_FKACCIO96718" FOREIGN KEY ("AMBIT_DESTI_ID")
	  REFERENCES "SINTAGMA_U"."A0_DM_AMBIT" ("ID") ENABLE;
