--------------------------------------------------------
--  Ref Constraints for Table A0_CONVIDAT_ACOMPANYANT
--------------------------------------------------------

  ALTER TABLE "SINTAGMA_U"."A0_CONVIDAT_ACOMPANYANT" ADD CONSTRAINT "A0_FKACOMPANYAN164290" FOREIGN KEY ("CONVIDAT_ID")
	  REFERENCES "SINTAGMA_U"."A0_CONVIDAT" ("ID") ENABLE;
  ALTER TABLE "SINTAGMA_U"."A0_CONVIDAT_ACOMPANYANT" ADD CONSTRAINT "A0_FKACOMPANYAN164291" FOREIGN KEY ("ESTAT_CONFIRMACIO_ID")
	  REFERENCES "SINTAGMA_U"."A0_DM_ESTAT_CONFIRMACIO" ("ID") ENABLE;
  ALTER TABLE "SINTAGMA_U"."A0_CONVIDAT_ACOMPANYANT" ADD CONSTRAINT "A0_FKACOMPANYAN164292" FOREIGN KEY ("DECISIO_ASSISTENCIA_ID")
	  REFERENCES "SINTAGMA_U"."A0_DM_DECISIO_ASSISTENCIA" ("ID") ENABLE;
