--------------------------------------------------------
--  Ref Constraints for Table A0_CONVIDAT
--------------------------------------------------------

  ALTER TABLE "SINTAGMA_U"."A0_CONVIDAT" ADD CONSTRAINT "A0_FKCONVIDAT156941" FOREIGN KEY ("CONTACTE_ID")
	  REFERENCES "SINTAGMA_U"."A0_CONTACTE" ("ID") ENABLE;
  ALTER TABLE "SINTAGMA_U"."A0_CONVIDAT" ADD CONSTRAINT "A0_FKCONVIDAT297469" FOREIGN KEY ("ESTAT_CONFIRMACIO_ID")
	  REFERENCES "SINTAGMA_U"."A0_DM_ESTAT_CONFIRMACIO" ("ID") ENABLE;
  ALTER TABLE "SINTAGMA_U"."A0_CONVIDAT" ADD CONSTRAINT "A0_FKCONVIDAT350170" FOREIGN KEY ("TIPUS_VIA_INVITACIO_ID")
	  REFERENCES "SINTAGMA_U"."A0_DM_TIPUS_VIA_INVITACIO" ("ID") ENABLE;
  ALTER TABLE "SINTAGMA_U"."A0_CONVIDAT" ADD CONSTRAINT "A0_FKCONVIDAT377638" FOREIGN KEY ("TIPUS_VIA_RESPOSTA_ID")
	  REFERENCES "SINTAGMA_U"."A0_DM_TIPUS_VIA_RESPOSTA" ("ID") ENABLE;
  ALTER TABLE "SINTAGMA_U"."A0_CONVIDAT" ADD CONSTRAINT "A0_FKCONVIDAT3776389" FOREIGN KEY ("CLASSIFICACIO_ID")
	  REFERENCES "SINTAGMA_U"."A0_DM_CLASSIFICACIO" ("ID") ENABLE;
  ALTER TABLE "SINTAGMA_U"."A0_CONVIDAT" ADD CONSTRAINT "A0_FKCONVIDAT535871" FOREIGN KEY ("INICIATIVA_RESPOSTA_ID")
	  REFERENCES "SINTAGMA_U"."A0_DM_INICIATIVA_RESPOSTA" ("ID") ENABLE;
  ALTER TABLE "SINTAGMA_U"."A0_CONVIDAT" ADD CONSTRAINT "A0_FKCONVIDAT658217" FOREIGN KEY ("ACTE_ID")
	  REFERENCES "SINTAGMA_U"."A0_ACTE" ("ID") ENABLE;
  ALTER TABLE "SINTAGMA_U"."A0_CONVIDAT" ADD CONSTRAINT "A0_FKCONVIDAT658517" FOREIGN KEY ("DECISIO_ASSISTENCIA_ID")
	  REFERENCES "SINTAGMA_U"."A0_DM_DECISIO_ASSISTENCIA" ("ID") ENABLE;
