--------------------------------------------------------
--  Ref Constraints for Table A0_CONTACTE_CONSENTIMENT
--------------------------------------------------------

  ALTER TABLE "SINTAGMA_U"."A0_CONTACTE_CONSENTIMENT" ADD CONSTRAINT "A0_FKCONTACTE_CON01" FOREIGN KEY ("DOCUMENT_ID")
	  REFERENCES "SINTAGMA_U"."A0_DOCUMENT" ("ID") ENABLE;
  ALTER TABLE "SINTAGMA_U"."A0_CONTACTE_CONSENTIMENT" ADD CONSTRAINT "A0_FKCONTACTE_CON02" FOREIGN KEY ("CONTACTE_ID")
	  REFERENCES "SINTAGMA_U"."A0_CONTACTE" ("ID") ENABLE;
