--------------------------------------------------------
--  Ref Constraints for Table A0_COMANDA
--------------------------------------------------------

  ALTER TABLE "SINTAGMA_U"."A0_COMANDA" ADD CONSTRAINT "A0_FKCOMANDA114314" FOREIGN KEY ("ACTE_ID")
	  REFERENCES "SINTAGMA_U"."A0_ACTE" ("ID") ENABLE;
  ALTER TABLE "SINTAGMA_U"."A0_COMANDA" ADD CONSTRAINT "A0_FKCOMANDA657374" FOREIGN KEY ("TIPUS_SERVEI_ID")
	  REFERENCES "SINTAGMA_U"."A0_DM_TIPUS_SERVEI" ("ID") ENABLE;
  ALTER TABLE "SINTAGMA_U"."A0_COMANDA" ADD CONSTRAINT "A0_FKCOMANDA778890" FOREIGN KEY ("ESTAT_COMANDA_ID")
	  REFERENCES "SINTAGMA_U"."A0_DM_ESTAT_COMANDA" ("ID") ENABLE;
