--------------------------------------------------------
--  Ref Constraints for Table A0_CLASSIFICACIO_ARXIU
--------------------------------------------------------

  ALTER TABLE "SINTAGMA_U"."A0_CLASSIFICACIO_ARXIU" ADD CONSTRAINT "A0_FKCLASSIFICA172830" FOREIGN KEY ("ESPECIFIC_ID")
	  REFERENCES "SINTAGMA_U"."A0_DM_ESPECIFIC" ("ID") ENABLE;
  ALTER TABLE "SINTAGMA_U"."A0_CLASSIFICACIO_ARXIU" ADD CONSTRAINT "A0_FKCLASSIFICA601394" FOREIGN KEY ("SERIE_ID")
	  REFERENCES "SINTAGMA_U"."A0_DM_SERIE" ("ID") ENABLE;
  ALTER TABLE "SINTAGMA_U"."A0_CLASSIFICACIO_ARXIU" ADD CONSTRAINT "A0_FKCLASSIFICA822831" FOREIGN KEY ("ASPECTE_ID")
	  REFERENCES "SINTAGMA_U"."A0_ASPECTE" ("ID") ENABLE;
