--------------------------------------------------------
--  Ref Constraints for Table A0_DM_CLASSIFICACIO
--------------------------------------------------------

  ALTER TABLE "SINTAGMA_U"."A0_DM_CLASSIFICACIO" ADD CONSTRAINT "A0_FKDM_CLASSIF01" FOREIGN KEY ("AMBIT_ID")
	  REFERENCES "SINTAGMA_U"."A0_DM_AMBIT" ("ID") ENABLE;
  ALTER TABLE "SINTAGMA_U"."A0_DM_CLASSIFICACIO" ADD CONSTRAINT "A0_FKDM_CLASSIF02" FOREIGN KEY ("TIPOLOGIA_ID")
	  REFERENCES "SINTAGMA_U"."A0_DM_TIPOLOGIA_CLASSIFICACIO" ("ID") ENABLE;
