--------------------------------------------------------
--  Ref Constraints for Table A0_DOCUMENT_BAIXA_SUBJECTE
--------------------------------------------------------

  ALTER TABLE "SINTAGMA_U"."A0_DOCUMENT_BAIXA_SUBJECTE" ADD CONSTRAINT "A0_FKDOCUMENT_BS01" FOREIGN KEY ("SUBJECTE_ID")
	  REFERENCES "SINTAGMA_U"."A0_SUBJECTE" ("ID") ENABLE;
  ALTER TABLE "SINTAGMA_U"."A0_DOCUMENT_BAIXA_SUBJECTE" ADD CONSTRAINT "A0_FKDOCUMENT_BS02" FOREIGN KEY ("DOCUMENT_ID")
	  REFERENCES "SINTAGMA_U"."A0_DOCUMENT" ("ID") ENABLE;
