--------------------------------------------------------
--  Ref Constraints for Table A0_ESPAI_ACTE_CONFIG
--------------------------------------------------------

  ALTER TABLE "SINTAGMA_U"."A0_ESPAI_ACTE_CONFIG" ADD CONSTRAINT "A0_FKESPAI_ACTE362713" FOREIGN KEY ("ESPAI_ACTE_ID")
	  REFERENCES "SINTAGMA_U"."A0_ESPAI_ACTE" ("ID") ENABLE;
  ALTER TABLE "SINTAGMA_U"."A0_ESPAI_ACTE_CONFIG" ADD CONSTRAINT "A0_FKESPAI_ACTE938901" FOREIGN KEY ("ZONA_ID")
	  REFERENCES "SINTAGMA_U"."A0_ZONA" ("ID") ENABLE;
