--------------------------------------------------------
--  Ref Constraints for Table A0_HISTORIC_TRUCADA
--------------------------------------------------------

  ALTER TABLE "SINTAGMA_U"."A0_HISTORIC_TRUCADA" ADD CONSTRAINT "A0_FKHISTORIC_TR02" FOREIGN KEY ("RAO_ID")
	  REFERENCES "SINTAGMA_U"."A0_DM_RAO" ("ID") ENABLE;
  ALTER TABLE "SINTAGMA_U"."A0_HISTORIC_TRUCADA" ADD CONSTRAINT "A0_FKHISTORIC_TR03" FOREIGN KEY ("ESTAT_TRUCADA_ID")
	  REFERENCES "SINTAGMA_U"."A0_DM_ESTAT_TRUCADA" ("ID") ENABLE;
  ALTER TABLE "SINTAGMA_U"."A0_HISTORIC_TRUCADA" ADD CONSTRAINT "A0_FKHISTORIC_TR04" FOREIGN KEY ("TRUCADA_ID")
	  REFERENCES "SINTAGMA_U"."A0_TRUCADA" ("ID") ENABLE;
  ALTER TABLE "SINTAGMA_U"."A0_HISTORIC_TRUCADA" ADD CONSTRAINT "A0_FKHISTORIC_TR05" FOREIGN KEY ("SENTIT_ID")
	  REFERENCES "SINTAGMA_U"."A0_DM_SENTIT_TRUCADA" ("ID") ENABLE;
