--------------------------------------------------------
--  Ref Constraints for Table A0_RASTRE_ASPECTE
--------------------------------------------------------

  ALTER TABLE "SINTAGMA_U"."A0_RASTRE_ASPECTE" ADD CONSTRAINT "A0_FKRASTRE_ASPECTE561971" FOREIGN KEY ("RASTRE_ID")
	  REFERENCES "SINTAGMA_U"."A0_RASTRE" ("ID") ENABLE;
  ALTER TABLE "SINTAGMA_U"."A0_RASTRE_ASPECTE" ADD CONSTRAINT "A0_FKRASTRE_ASPECTE561972" FOREIGN KEY ("ASPECTE_ID")
	  REFERENCES "SINTAGMA_U"."A0_ASPECTE" ("ID") ENABLE;
