--------------------------------------------------------
--  Ref Constraints for Table A0_RASTRE_ACTE
--------------------------------------------------------

  ALTER TABLE "SINTAGMA_U"."A0_RASTRE_ACTE" ADD CONSTRAINT "A0_FKRASTRE_ACTE561971" FOREIGN KEY ("RASTRE_ID")
	  REFERENCES "SINTAGMA_U"."A0_RASTRE" ("ID") ENABLE;
  ALTER TABLE "SINTAGMA_U"."A0_RASTRE_ACTE" ADD CONSTRAINT "A0_FKRASTRE_ACTE561972" FOREIGN KEY ("ACTE_ID")
	  REFERENCES "SINTAGMA_U"."A0_ACTE" ("ID") ENABLE;
