--------------------------------------------------------
--  Ref Constraints for Table A0_TITULAR_FORA
--------------------------------------------------------

  ALTER TABLE "SINTAGMA_U"."A0_TITULAR_FORA" ADD CONSTRAINT "A0_FKTITULAR_FO01" FOREIGN KEY ("TRACTAMENT_ID")
	  REFERENCES "SINTAGMA_U"."A0_DM_TRACTAMENT" ("ID") ENABLE;
  ALTER TABLE "SINTAGMA_U"."A0_TITULAR_FORA" ADD CONSTRAINT "A0_FKTITULAR_FO620544" FOREIGN KEY ("CONTACTE_ID")
	  REFERENCES "SINTAGMA_U"."A0_CONTACTE" ("ID") ENABLE;
  ALTER TABLE "SINTAGMA_U"."A0_TITULAR_FORA" ADD CONSTRAINT "A0_FKTITULAR_FO877092" FOREIGN KEY ("ASPECTE_ID")
	  REFERENCES "SINTAGMA_U"."A0_ASPECTE" ("ID") ENABLE;
