--------------------------------------------------------
--  Ref Constraints for Table A0_TRUCADA
--------------------------------------------------------

  ALTER TABLE "SINTAGMA_U"."A0_TRUCADA" ADD CONSTRAINT "A0_FKTRUCADA01" FOREIGN KEY ("ENTITAT_ID")
	  REFERENCES "SINTAGMA_U"."A0_DM_ENTITAT" ("ID") ENABLE;
  ALTER TABLE "SINTAGMA_U"."A0_TRUCADA" ADD CONSTRAINT "A0_FKTRUCADA02" FOREIGN KEY ("SENTIT_ID")
	  REFERENCES "SINTAGMA_U"."A0_DM_SENTIT_TRUCADA" ("ID") ENABLE;
  ALTER TABLE "SINTAGMA_U"."A0_TRUCADA" ADD CONSTRAINT "A0_FKTRUCADA03" FOREIGN KEY ("CONTACTE_ID")
	  REFERENCES "SINTAGMA_U"."A0_CONTACTE" ("ID") ENABLE;
  ALTER TABLE "SINTAGMA_U"."A0_TRUCADA" ADD CONSTRAINT "A0_FKTRUCADA04" FOREIGN KEY ("DESTINATARI_PERSONA_ID")
	  REFERENCES "SINTAGMA_U"."A0_DM_DESTINATARI_PERSONA" ("ID") ENABLE;
  ALTER TABLE "SINTAGMA_U"."A0_TRUCADA" ADD CONSTRAINT "A0_FKTRUCADA05" FOREIGN KEY ("ESTAT_TRUCADA_ID")
	  REFERENCES "SINTAGMA_U"."A0_DM_ESTAT_TRUCADA" ("ID") ENABLE;
