--------------------------------------------------------
--  Ref Constraints for Table A0_TITULAR_FORA_TELEFON
--------------------------------------------------------

  ALTER TABLE "SINTAGMA_U"."A0_TITULAR_FORA_TELEFON" ADD CONSTRAINT "A0_FKTITULAR_FO360858" FOREIGN KEY ("TITULAR_FORA_ID")
	  REFERENCES "SINTAGMA_U"."A0_TITULAR_FORA" ("ID") ENABLE;
  ALTER TABLE "SINTAGMA_U"."A0_TITULAR_FORA_TELEFON" ADD CONSTRAINT "A0_FKTITULAR_FO851767" FOREIGN KEY ("TIPUS_TELEFON_ID")
	  REFERENCES "SINTAGMA_U"."A0_DM_TIPUS_TELEFON" ("ID") ENABLE;
