--------------------------------------------------------
--  Ref Constraints for Table A0_TRUCADA_ELEMENT_PRINCIPAL
--------------------------------------------------------

  ALTER TABLE "SINTAGMA_U"."A0_TRUCADA_ELEMENT_PRINCIPAL" ADD CONSTRAINT "A0_FKTRUCADA_EL406176" FOREIGN KEY ("ELEMENT_PRINCIPAL_ID")
	  REFERENCES "SINTAGMA_U"."A0_ELEMENT_PRINCIPAL" ("ID") ENABLE;
  ALTER TABLE "SINTAGMA_U"."A0_TRUCADA_ELEMENT_PRINCIPAL" ADD CONSTRAINT "A0_FKTRUCADA_EL645987" FOREIGN KEY ("TRUCADA_ID")
	  REFERENCES "SINTAGMA_U"."A0_TRUCADA" ("ID") ENABLE;
