--------------------------------------------------------
--  Ref Constraints for Table A1_ACTE
--------------------------------------------------------

  ALTER TABLE "SINTAGMA_U"."A1_ACTE" ADD CONSTRAINT "A1_FKACTE101315" FOREIGN KEY ("CATEGORIA_ID")
	  REFERENCES "SINTAGMA_U"."A1_DM_CATEGORIA" ("ID") ENABLE;
  ALTER TABLE "SINTAGMA_U"."A1_ACTE" ADD CONSTRAINT "A1_FKACTE417776" FOREIGN KEY ("TIPUS_ACTE_ID")
	  REFERENCES "SINTAGMA_U"."A1_DM_TIPUS_ACTE" ("ID") ENABLE;
  ALTER TABLE "SINTAGMA_U"."A1_ACTE" ADD CONSTRAINT "A1_FKACTE422028" FOREIGN KEY ("ESTAT_GESTIO_ESPAIS_ID")
	  REFERENCES "SINTAGMA_U"."A1_DM_ESTAT_GESTIO_ESPAIS" ("ID") ENABLE;
  ALTER TABLE "SINTAGMA_U"."A1_ACTE" ADD CONSTRAINT "A1_FKACTE499691" FOREIGN KEY ("ESTAT_GESTIO_INVITACIO_ID")
	  REFERENCES "SINTAGMA_U"."A1_DM_ESTAT_GESTIO_INVITACIO" ("ID") ENABLE;
  ALTER TABLE "SINTAGMA_U"."A1_ACTE" ADD CONSTRAINT "A1_FKACTE565313" FOREIGN KEY ("PRESIDENT_ID")
	  REFERENCES "SINTAGMA_U"."A1_DM_PRESIDENT" ("ID") ENABLE;
  ALTER TABLE "SINTAGMA_U"."A1_ACTE" ADD CONSTRAINT "A1_FKACTE634685" FOREIGN KEY ("SECTOR_ID")
	  REFERENCES "SINTAGMA_U"."A1_DM_SECTOR" ("ID") ENABLE;
  ALTER TABLE "SINTAGMA_U"."A1_ACTE" ADD CONSTRAINT "A1_FKACTE720609" FOREIGN KEY ("ELEMENT_PRINCIPAL_ID")
	  REFERENCES "SINTAGMA_U"."A1_ELEMENT_PRINCIPAL" ("ID") ENABLE;
  ALTER TABLE "SINTAGMA_U"."A1_ACTE" ADD CONSTRAINT "A1_FKACTE765939" FOREIGN KEY ("PETICIONARI_ID")
	  REFERENCES "SINTAGMA_U"."A1_DM_PETICIONARI" ("ID") ENABLE;
  ALTER TABLE "SINTAGMA_U"."A1_ACTE" ADD CONSTRAINT "A1_FKACTE776168" FOREIGN KEY ("ESTAT_ACTE_ID")
	  REFERENCES "SINTAGMA_U"."A1_DM_ESTAT_ACTE" ("ID") ENABLE;
