--------------------------------------------------------
--  Ref Constraints for Table A1_ANNEX_INCIDENT
--------------------------------------------------------

  ALTER TABLE "SINTAGMA_U"."A1_ANNEX_INCIDENT" ADD CONSTRAINT "A1_FKANNEX_INC01" FOREIGN KEY ("TIPUS_SUPORT_ID")
	  REFERENCES "SINTAGMA_U"."A1_DM_TIPUS_SUPORT" ("ID") ENABLE;
  ALTER TABLE "SINTAGMA_U"."A1_ANNEX_INCIDENT" ADD CONSTRAINT "A1_FKANNEX_INC02" FOREIGN KEY ("INCIDENT_ID")
	  REFERENCES "SINTAGMA_U"."A1_INCIDENTS_ACTE" ("ID") ENABLE;
  ALTER TABLE "SINTAGMA_U"."A1_ANNEX_INCIDENT" ADD CONSTRAINT "A1_FKANNEX_INC03" FOREIGN KEY ("DOCUMENT_ID")
	  REFERENCES "SINTAGMA_U"."A1_DOCUMENT" ("ID") ENABLE;
