--------------------------------------------------------
--  Ref Constraints for Table A1_ANNEX_REGISTRE
--------------------------------------------------------

  ALTER TABLE "SINTAGMA_U"."A1_ANNEX_REGISTRE" ADD CONSTRAINT "A1_FKANNEX_REGI550428" FOREIGN KEY ("DOCUMENT_ID")
	  REFERENCES "SINTAGMA_U"."A1_DOCUMENT" ("ID") ENABLE;
  ALTER TABLE "SINTAGMA_U"."A1_ANNEX_REGISTRE" ADD CONSTRAINT "A1_FKANNEX_REGI863017" FOREIGN KEY ("REGISTRE_ID")
	  REFERENCES "SINTAGMA_U"."A1_REGISTRE" ("ID") ENABLE;
