--------------------------------------------------------
--  Ref Constraints for Table A1_ACOMPANYANT
--------------------------------------------------------

  ALTER TABLE "SINTAGMA_U"."A1_ACOMPANYANT" ADD CONSTRAINT "A1_FKACOMPANYANT01" FOREIGN KEY ("TRACTAMENT_ID")
	  REFERENCES "SINTAGMA_U"."A1_DM_TRACTAMENT" ("ID") ENABLE;
  ALTER TABLE "SINTAGMA_U"."A1_ACOMPANYANT" ADD CONSTRAINT "A1_FKACOMPANYANT02" FOREIGN KEY ("CONTACTE_ID")
	  REFERENCES "SINTAGMA_U"."A1_CONTACTE" ("ID") ENABLE;
