--------------------------------------------------------
--  Ref Constraints for Table A1_CONVIDAT_OBSEQUI
--------------------------------------------------------

  ALTER TABLE "SINTAGMA_U"."A1_CONVIDAT_OBSEQUI" ADD CONSTRAINT "A1_FKOBSEQUI_CO122479" FOREIGN KEY ("CONVIDAT_ID")
	  REFERENCES "SINTAGMA_U"."A1_CONVIDAT" ("ID") ENABLE;
  ALTER TABLE "SINTAGMA_U"."A1_CONVIDAT_OBSEQUI" ADD CONSTRAINT "A1_FKOBSEQUI_CO472489" FOREIGN KEY ("OBSEQUI_ID")
	  REFERENCES "SINTAGMA_U"."A1_DM_OBSEQUI" ("ID") ENABLE;
