--------------------------------------------------------
--  Ref Constraints for Table A1_CONTACTE_CONSENTIMENT
--------------------------------------------------------

  ALTER TABLE "SINTAGMA_U"."A1_CONTACTE_CONSENTIMENT" ADD CONSTRAINT "A1_FKCONTACTE_CON01" FOREIGN KEY ("DOCUMENT_ID")
	  REFERENCES "SINTAGMA_U"."A1_DOCUMENT" ("ID") ENABLE;
  ALTER TABLE "SINTAGMA_U"."A1_CONTACTE_CONSENTIMENT" ADD CONSTRAINT "A1_FKCONTACTE_CON02" FOREIGN KEY ("CONTACTE_ID")
	  REFERENCES "SINTAGMA_U"."A1_CONTACTE" ("ID") ENABLE;
