--------------------------------------------------------
--  Ref Constraints for Table A1_COMENTARI_ASPECTE
--------------------------------------------------------

  ALTER TABLE "SINTAGMA_U"."A1_COMENTARI_ASPECTE" ADD CONSTRAINT "A1_FKCOMENTARI_ASPECTE376237" FOREIGN KEY ("COMENTARI_ID")
	  REFERENCES "SINTAGMA_U"."A1_COMENTARI" ("ID") ENABLE;
  ALTER TABLE "SINTAGMA_U"."A1_COMENTARI_ASPECTE" ADD CONSTRAINT "A1_FKCOMENTARI_ASPECTE423341" FOREIGN KEY ("ASPECTE_ID")
	  REFERENCES "SINTAGMA_U"."A1_ASPECTE" ("ID") ENABLE;
