--------------------------------------------------------
--  Ref Constraints for Table A1_CONVIDAT_ACOMPANYANT
--------------------------------------------------------

  ALTER TABLE "SINTAGMA_U"."A1_CONVIDAT_ACOMPANYANT" ADD CONSTRAINT "A1_FKACOMPANYAN164290" FOREIGN KEY ("CONVIDAT_ID")
	  REFERENCES "SINTAGMA_U"."A1_CONVIDAT" ("ID") ENABLE;
  ALTER TABLE "SINTAGMA_U"."A1_CONVIDAT_ACOMPANYANT" ADD CONSTRAINT "A1_FKACOMPANYAN164291" FOREIGN KEY ("ESTAT_CONFIRMACIO_ID")
	  REFERENCES "SINTAGMA_U"."A1_DM_ESTAT_CONFIRMACIO" ("ID") ENABLE;
  ALTER TABLE "SINTAGMA_U"."A1_CONVIDAT_ACOMPANYANT" ADD CONSTRAINT "A1_FKACOMPANYAN164292" FOREIGN KEY ("DECISIO_ASSISTENCIA_ID")
	  REFERENCES "SINTAGMA_U"."A1_DM_DECISIO_ASSISTENCIA" ("ID") ENABLE;
