--------------------------------------------------------
--  Ref Constraints for Table A1_CLASSIFICACIO_ARXIU
--------------------------------------------------------

  ALTER TABLE "SINTAGMA_U"."A1_CLASSIFICACIO_ARXIU" ADD CONSTRAINT "A1_FKCLASSIFICA172830" FOREIGN KEY ("ESPECIFIC_ID")
	  REFERENCES "SINTAGMA_U"."A1_DM_ESPECIFIC" ("ID") ENABLE;
  ALTER TABLE "SINTAGMA_U"."A1_CLASSIFICACIO_ARXIU" ADD CONSTRAINT "A1_FKCLASSIFICA601394" FOREIGN KEY ("SERIE_ID")
	  REFERENCES "SINTAGMA_U"."A1_DM_SERIE" ("ID") ENABLE;
  ALTER TABLE "SINTAGMA_U"."A1_CLASSIFICACIO_ARXIU" ADD CONSTRAINT "A1_FKCLASSIFICA822831" FOREIGN KEY ("ASPECTE_ID")
	  REFERENCES "SINTAGMA_U"."A1_ASPECTE" ("ID") ENABLE;
