--------------------------------------------------------
--  Ref Constraints for Table A1_DM_DECISIO_AGENDA
--------------------------------------------------------

  ALTER TABLE "SINTAGMA_U"."A1_DM_DECISIO_AGENDA" ADD CONSTRAINT "A1_FKDM_DECISIO00001" FOREIGN KEY ("AFECTA_AGENDA_ID")
	  REFERENCES "SINTAGMA_U"."A1_DM_AFECTA_AGENDA" ("ID") ENABLE;
  ALTER TABLE "SINTAGMA_U"."A1_DM_DECISIO_AGENDA" ADD CONSTRAINT "A1_FKDM_DECISIO81470" FOREIGN KEY ("AMBIT_ID")
	  REFERENCES "SINTAGMA_U"."A1_DM_AMBIT" ("ID") ENABLE;
