--------------------------------------------------------
--  Ref Constraints for Table A1_DM_SUBTIPUS_ACCIO
--------------------------------------------------------

  ALTER TABLE "SINTAGMA_U"."A1_DM_SUBTIPUS_ACCIO" ADD CONSTRAINT "A1_FKDM_SUBTIPU252151" FOREIGN KEY ("AMBIT_ID")
	  REFERENCES "SINTAGMA_U"."A1_DM_AMBIT" ("ID") ENABLE;
  ALTER TABLE "SINTAGMA_U"."A1_DM_SUBTIPUS_ACCIO" ADD CONSTRAINT "A1_FKDM_SUBTIPU602859" FOREIGN KEY ("TIPUS_ACCIO_ID")
	  REFERENCES "SINTAGMA_U"."A1_DM_TIPUS_ACCIO" ("ID") ENABLE;
