--------------------------------------------------------
--  Ref Constraints for Table A1_ELEMENT_PRINCIPAL
--------------------------------------------------------

  ALTER TABLE "SINTAGMA_U"."A1_ELEMENT_PRINCIPAL" ADD CONSTRAINT "A1_FKELEMENT_PR16069" FOREIGN KEY ("ASPECTE_ID")
	  REFERENCES "SINTAGMA_U"."A1_ASPECTE" ("ID") ENABLE;
  ALTER TABLE "SINTAGMA_U"."A1_ELEMENT_PRINCIPAL" ADD CONSTRAINT "A1_FKELEMENT_PR16148" FOREIGN KEY ("AFECTA_AGENDA_ID")
	  REFERENCES "SINTAGMA_U"."A1_DM_AFECTA_AGENDA" ("ID") ENABLE;
  ALTER TABLE "SINTAGMA_U"."A1_ELEMENT_PRINCIPAL" ADD CONSTRAINT "A1_FKELEMENT_PR176225" FOREIGN KEY ("TIPUS_AMBIT_ID")
	  REFERENCES "SINTAGMA_U"."A1_DM_TIPUS_AMBIT" ("ID") ENABLE;
  ALTER TABLE "SINTAGMA_U"."A1_ELEMENT_PRINCIPAL" ADD CONSTRAINT "A1_FKELEMENT_PR18178" FOREIGN KEY ("PRIORITAT_ID")
	  REFERENCES "SINTAGMA_U"."A1_DM_PRIORITAT_ELEMENT" ("ID") ENABLE;
  ALTER TABLE "SINTAGMA_U"."A1_ELEMENT_PRINCIPAL" ADD CONSTRAINT "A1_FKELEMENT_PR20834" FOREIGN KEY ("TIPUS_SUPORT_ID")
	  REFERENCES "SINTAGMA_U"."A1_DM_TIPUS_SUPORT" ("ID") ENABLE;
  ALTER TABLE "SINTAGMA_U"."A1_ELEMENT_PRINCIPAL" ADD CONSTRAINT "A1_FKELEMENT_PR284981" FOREIGN KEY ("TIPUS_ARG_ID")
	  REFERENCES "SINTAGMA_U"."A1_DM_TIPUS_ARG" ("ID") ENABLE;
  ALTER TABLE "SINTAGMA_U"."A1_ELEMENT_PRINCIPAL" ADD CONSTRAINT "A1_FKELEMENT_PR30487" FOREIGN KEY ("ESTAT_ELEMENT_PRINCIPAL_ID")
	  REFERENCES "SINTAGMA_U"."A1_DM_ESTAT_ELEMENT" ("ID") ENABLE;
  ALTER TABLE "SINTAGMA_U"."A1_ELEMENT_PRINCIPAL" ADD CONSTRAINT "A1_FKELEMENT_PR335151" FOREIGN KEY ("TIPUS_ELEMENT_ID")
	  REFERENCES "SINTAGMA_U"."A1_DM_TIPUS_ELEMENT" ("ID") ENABLE;
  ALTER TABLE "SINTAGMA_U"."A1_ELEMENT_PRINCIPAL" ADD CONSTRAINT "A1_FKELEMENT_PR469506" FOREIGN KEY ("NUMERO_REGISTRE_GENERAL_ID")
	  REFERENCES "SINTAGMA_U"."A1_REGISTRE" ("ID") ENABLE;
  ALTER TABLE "SINTAGMA_U"."A1_ELEMENT_PRINCIPAL" ADD CONSTRAINT "A1_FKELEMENT_PR471364" FOREIGN KEY ("ELEMENT_PRINCIPAL_ORIGEN_ID")
	  REFERENCES "SINTAGMA_U"."A1_ELEMENT_PRINCIPAL" ("ID") ENABLE;
  ALTER TABLE "SINTAGMA_U"."A1_ELEMENT_PRINCIPAL" ADD CONSTRAINT "A1_FKELEMENT_PR561971" FOREIGN KEY ("DOSSIER_ID")
	  REFERENCES "SINTAGMA_U"."A1_DOSSIER" ("ID") ENABLE;
  ALTER TABLE "SINTAGMA_U"."A1_ELEMENT_PRINCIPAL" ADD CONSTRAINT "A1_FKELEMENT_PR600648" FOREIGN KEY ("ORIGEN_ID")
	  REFERENCES "SINTAGMA_U"."A1_DM_ORIGEN_ELEMENT" ("ID") ENABLE;
  ALTER TABLE "SINTAGMA_U"."A1_ELEMENT_PRINCIPAL" ADD CONSTRAINT "A1_FKELEMENT_PR634362" FOREIGN KEY ("PREFIX_ID")
	  REFERENCES "SINTAGMA_U"."A1_DM_PREFIX" ("ID") ENABLE;
