--------------------------------------------------------
--  Ref Constraints for Table A1_ELEMENT_SECUNDARI
--------------------------------------------------------

  ALTER TABLE "SINTAGMA_U"."A1_ELEMENT_SECUNDARI" ADD CONSTRAINT "A1_FKELEMENT_SE117582" FOREIGN KEY ("PREFIX_ID")
	  REFERENCES "SINTAGMA_U"."A1_DM_PREFIX" ("ID") ENABLE;
  ALTER TABLE "SINTAGMA_U"."A1_ELEMENT_SECUNDARI" ADD CONSTRAINT "A1_FKELEMENT_SE151296" FOREIGN KEY ("ORIGEN_ID")
	  REFERENCES "SINTAGMA_U"."A1_DM_ORIGEN_ELEMENT" ("ID") ENABLE;
  ALTER TABLE "SINTAGMA_U"."A1_ELEMENT_SECUNDARI" ADD CONSTRAINT "A1_FKELEMENT_SE371596" FOREIGN KEY ("ELEMENT_PRINCIPAL_ID")
	  REFERENCES "SINTAGMA_U"."A1_ELEMENT_PRINCIPAL" ("ID") ENABLE;
  ALTER TABLE "SINTAGMA_U"."A1_ELEMENT_SECUNDARI" ADD CONSTRAINT "A1_FKELEMENT_SE796422" FOREIGN KEY ("ASPECTE_ID")
	  REFERENCES "SINTAGMA_U"."A1_ASPECTE" ("ID") ENABLE;
  ALTER TABLE "SINTAGMA_U"."A1_ELEMENT_SECUNDARI" ADD CONSTRAINT "A1_FKELEMENT_SE801187" FOREIGN KEY ("TIPUS_SUPORT_ID")
	  REFERENCES "SINTAGMA_U"."A1_DM_TIPUS_SUPORT" ("ID") ENABLE;
  ALTER TABLE "SINTAGMA_U"."A1_ELEMENT_SECUNDARI" ADD CONSTRAINT "A1_FKELEMENT_SE808187" FOREIGN KEY ("NUMERO_REGISTRE_GENERAL_ID")
	  REFERENCES "SINTAGMA_U"."A1_REGISTRE" ("ID") ENABLE;
