--------------------------------------------------------
--  Ref Constraints for Table A1_ESPAI_ACTE_CONFIG
--------------------------------------------------------

  ALTER TABLE "SINTAGMA_U"."A1_ESPAI_ACTE_CONFIG" ADD CONSTRAINT "A1_FKESPAI_ACTE362713" FOREIGN KEY ("ESPAI_ACTE_ID")
	  REFERENCES "SINTAGMA_U"."A1_ESPAI_ACTE" ("ID") ENABLE;
  ALTER TABLE "SINTAGMA_U"."A1_ESPAI_ACTE_CONFIG" ADD CONSTRAINT "A1_FKESPAI_ACTE938901" FOREIGN KEY ("ZONA_ID")
	  REFERENCES "SINTAGMA_U"."A1_ZONA" ("ID") ENABLE;
