--------------------------------------------------------
--  Ref Constraints for Table A1_ENTRADA_AGENDA
--------------------------------------------------------

  ALTER TABLE "SINTAGMA_U"."A1_ENTRADA_AGENDA" ADD CONSTRAINT "A1_FKENTRADA_AG385363" FOREIGN KEY ("TIPUS_DATA_ID")
	  REFERENCES "SINTAGMA_U"."A1_DM_TIPUS_DATA" ("ID") ENABLE;
  ALTER TABLE "SINTAGMA_U"."A1_ENTRADA_AGENDA" ADD CONSTRAINT "A1_FKENTRADA_AG443925" FOREIGN KEY ("TIPUS_AGENDA_ID")
	  REFERENCES "SINTAGMA_U"."A1_DM_TIPUS_AGENDA" ("ID") ENABLE;
  ALTER TABLE "SINTAGMA_U"."A1_ENTRADA_AGENDA" ADD CONSTRAINT "A1_FKENTRADA_AG59765" FOREIGN KEY ("ELEMENT_PRINCIPAL_ID")
	  REFERENCES "SINTAGMA_U"."A1_ELEMENT_PRINCIPAL" ("ID") ENABLE;
  ALTER TABLE "SINTAGMA_U"."A1_ENTRADA_AGENDA" ADD CONSTRAINT "A1_FKENTRADA_AG608766" FOREIGN KEY ("DISTRICTE_ID")
	  REFERENCES "SINTAGMA_U"."A1_DM_DISTRICTE" ("ID") ENABLE;
  ALTER TABLE "SINTAGMA_U"."A1_ENTRADA_AGENDA" ADD CONSTRAINT "A1_FKENTRADA_AG642221" FOREIGN KEY ("DECISIO_AGENDA_ID")
	  REFERENCES "SINTAGMA_U"."A1_DM_DECISIO_AGENDA" ("ID") ENABLE;
  ALTER TABLE "SINTAGMA_U"."A1_ENTRADA_AGENDA" ADD CONSTRAINT "A1_FKENTRADA_AG711320" FOREIGN KEY ("LLOC_ID")
	  REFERENCES "SINTAGMA_U"."A1_DM_LLOC" ("ID") ENABLE;
  ALTER TABLE "SINTAGMA_U"."A1_ENTRADA_AGENDA" ADD CONSTRAINT "A1_FKENTRADA_AG971241" FOREIGN KEY ("BARRI_ID")
	  REFERENCES "SINTAGMA_U"."A1_DM_BARRI" ("ID") ENABLE;
