--------------------------------------------------------
--  Ref Constraints for Table A1_HISTORIC_TRUCADA
--------------------------------------------------------

  ALTER TABLE "SINTAGMA_U"."A1_HISTORIC_TRUCADA" ADD CONSTRAINT "A1_FKHISTORIC_TR02" FOREIGN KEY ("RAO_ID")
	  REFERENCES "SINTAGMA_U"."A1_DM_RAO" ("ID") ENABLE;
  ALTER TABLE "SINTAGMA_U"."A1_HISTORIC_TRUCADA" ADD CONSTRAINT "A1_FKHISTORIC_TR03" FOREIGN KEY ("ESTAT_TRUCADA_ID")
	  REFERENCES "SINTAGMA_U"."A1_DM_ESTAT_TRUCADA" ("ID") ENABLE;
  ALTER TABLE "SINTAGMA_U"."A1_HISTORIC_TRUCADA" ADD CONSTRAINT "A1_FKHISTORIC_TR04" FOREIGN KEY ("TRUCADA_ID")
	  REFERENCES "SINTAGMA_U"."A1_TRUCADA" ("ID") ENABLE;
  ALTER TABLE "SINTAGMA_U"."A1_HISTORIC_TRUCADA" ADD CONSTRAINT "A1_FKHISTORIC_TR05" FOREIGN KEY ("SENTIT_ID")
	  REFERENCES "SINTAGMA_U"."A1_DM_SENTIT_TRUCADA" ("ID") ENABLE;
