--------------------------------------------------------
--  Ref Constraints for Table A1_SUBJECTE
--------------------------------------------------------

  ALTER TABLE "SINTAGMA_U"."A1_SUBJECTE" ADD CONSTRAINT "A1_FKSUBJECTE01" FOREIGN KEY ("TRACTAMENT_ID")
	  REFERENCES "SINTAGMA_U"."A1_DM_TRACTAMENT" ("ID") ENABLE;
  ALTER TABLE "SINTAGMA_U"."A1_SUBJECTE" ADD CONSTRAINT "A1_FKSUBJECTE02" FOREIGN KEY ("IDIOMA_ID")
	  REFERENCES "SINTAGMA_U"."A1_DM_IDIOMA" ("ID") ENABLE;
  ALTER TABLE "SINTAGMA_U"."A1_SUBJECTE" ADD CONSTRAINT "A1_FKSUBJECTE03" FOREIGN KEY ("TIPUS_SUBJECTE_ID")
	  REFERENCES "SINTAGMA_U"."A1_DM_TIPUS_SUBJECTE" ("ID") ENABLE;
  ALTER TABLE "SINTAGMA_U"."A1_SUBJECTE" ADD CONSTRAINT "A1_FKSUBJECTE04" FOREIGN KEY ("AMBIT_ID")
	  REFERENCES "SINTAGMA_U"."A1_DM_AMBIT" ("ID") ENABLE;
  ALTER TABLE "SINTAGMA_U"."A1_SUBJECTE" ADD CONSTRAINT "A1_FKSUBJECTE05" FOREIGN KEY ("PRIORITAT_ID")
	  REFERENCES "SINTAGMA_U"."A1_DM_PRIORITAT" ("ID") ENABLE;
  ALTER TABLE "SINTAGMA_U"."A1_SUBJECTE" ADD CONSTRAINT "A1_FKSUBJECTE06" FOREIGN KEY ("ARTICLE_ID")
	  REFERENCES "SINTAGMA_U"."A1_DM_ARTICLE" ("ID") ENABLE;
