--------------------------------------------------------
--  Ref Constraints for Table A1_TRUCADA
--------------------------------------------------------

  ALTER TABLE "SINTAGMA_U"."A1_TRUCADA" ADD CONSTRAINT "A1_FKTRUCADA01" FOREIGN KEY ("ENTITAT_ID")
	  REFERENCES "SINTAGMA_U"."A1_DM_ENTITAT" ("ID") ENABLE;
  ALTER TABLE "SINTAGMA_U"."A1_TRUCADA" ADD CONSTRAINT "A1_FKTRUCADA02" FOREIGN KEY ("SENTIT_ID")
	  REFERENCES "SINTAGMA_U"."A1_DM_SENTIT_TRUCADA" ("ID") ENABLE;
  ALTER TABLE "SINTAGMA_U"."A1_TRUCADA" ADD CONSTRAINT "A1_FKTRUCADA03" FOREIGN KEY ("CONTACTE_ID")
	  REFERENCES "SINTAGMA_U"."A1_CONTACTE" ("ID") ENABLE;
  ALTER TABLE "SINTAGMA_U"."A1_TRUCADA" ADD CONSTRAINT "A1_FKTRUCADA04" FOREIGN KEY ("DESTINATARI_PERSONA_ID")
	  REFERENCES "SINTAGMA_U"."A1_DM_DESTINATARI_PERSONA" ("ID") ENABLE;
  ALTER TABLE "SINTAGMA_U"."A1_TRUCADA" ADD CONSTRAINT "A1_FKTRUCADA05" FOREIGN KEY ("ESTAT_TRUCADA_ID")
	  REFERENCES "SINTAGMA_U"."A1_DM_ESTAT_TRUCADA" ("ID") ENABLE;
