--------------------------------------------------------
--  Ref Constraints for Table A1_TITULAR_FORA
--------------------------------------------------------

  ALTER TABLE "SINTAGMA_U"."A1_TITULAR_FORA" ADD CONSTRAINT "A1_FKTITULAR_FO01" FOREIGN KEY ("TRACTAMENT_ID")
	  REFERENCES "SINTAGMA_U"."A1_DM_TRACTAMENT" ("ID") ENABLE;
  ALTER TABLE "SINTAGMA_U"."A1_TITULAR_FORA" ADD CONSTRAINT "A1_FKTITULAR_FO620544" FOREIGN KEY ("CONTACTE_ID")
	  REFERENCES "SINTAGMA_U"."A1_CONTACTE" ("ID") ENABLE;
  ALTER TABLE "SINTAGMA_U"."A1_TITULAR_FORA" ADD CONSTRAINT "A1_FKTITULAR_FO877092" FOREIGN KEY ("ASPECTE_ID")
	  REFERENCES "SINTAGMA_U"."A1_ASPECTE" ("ID") ENABLE;
