--------------------------------------------------------
--  Ref Constraints for Table A1_TRANSICIO_TRAMITACIO
--------------------------------------------------------

  ALTER TABLE "SINTAGMA_U"."A1_TRANSICIO_TRAMITACIO" ADD CONSTRAINT "A1_FKTRANSICIO_000001" FOREIGN KEY ("AMBIT_ID")
	  REFERENCES "SINTAGMA_U"."A1_DM_AMBIT" ("ID") ENABLE;
  ALTER TABLE "SINTAGMA_U"."A1_TRANSICIO_TRAMITACIO" ADD CONSTRAINT "A1_FKTRANSICIO_143222" FOREIGN KEY ("ACCIO_DESTI_ID")
	  REFERENCES "SINTAGMA_U"."A1_DM_SUBTIPUS_ACCIO" ("ID") ENABLE;
  ALTER TABLE "SINTAGMA_U"."A1_TRANSICIO_TRAMITACIO" ADD CONSTRAINT "A1_FKTRANSICIO_605771" FOREIGN KEY ("ACCIO_ORIGEN_ID")
	  REFERENCES "SINTAGMA_U"."A1_DM_SUBTIPUS_ACCIO" ("ID") ENABLE;
