--------------------------------------------------------
--  Ref Constraints for Table ACCIO
--------------------------------------------------------

  ALTER TABLE "SINTAGMA_U"."ACCIO" ADD CONSTRAINT "FKACCIO171138" FOREIGN KEY ("ASPECTE_ID")
	  REFERENCES "SINTAGMA_U"."ASPECTE" ("ID") ENABLE;
  ALTER TABLE "SINTAGMA_U"."ACCIO" ADD CONSTRAINT "FKACCIO382248" FOREIGN KEY ("PAS_ACCIO_ID")
	  REFERENCES "SINTAGMA_U"."DM_PAS_ACCIO" ("ID") ENABLE;
  ALTER TABLE "SINTAGMA_U"."ACCIO" ADD CONSTRAINT "FKACCIO632433" FOREIGN KEY ("ELEMENT_PRINCIPAL_ID")
	  REFERENCES "SINTAGMA_U"."ELEMENT_PRINCIPAL" ("ID") ENABLE;
  ALTER TABLE "SINTAGMA_U"."ACCIO" ADD CONSTRAINT "FKACCIO838514" FOREIGN KEY ("SUBTIPUS_ACCIO_ID")
	  REFERENCES "SINTAGMA_U"."DM_SUBTIPUS_ACCIO" ("ID") ENABLE;
  ALTER TABLE "SINTAGMA_U"."ACCIO" ADD CONSTRAINT "FKACCIO96718" FOREIGN KEY ("AMBIT_DESTI_ID")
	  REFERENCES "SINTAGMA_U"."DM_AMBIT" ("ID") ENABLE;
