--------------------------------------------------------
--  Ref Constraints for Table ACOMPANYANT
--------------------------------------------------------

  ALTER TABLE "SINTAGMA_U"."ACOMPANYANT" ADD CONSTRAINT "FKACOMPANYANT01" FOREIGN KEY ("TRACTAMENT_ID")
	  REFERENCES "SINTAGMA_U"."DM_TRACTAMENT" ("ID") ENABLE;
  ALTER TABLE "SINTAGMA_U"."ACOMPANYANT" ADD CONSTRAINT "FKACOMPANYANT02" FOREIGN KEY ("CONTACTE_ID")
	  REFERENCES "SINTAGMA_U"."CONTACTE" ("ID") ENABLE;
