--------------------------------------------------------
--  Ref Constraints for Table ACTE
--------------------------------------------------------

  ALTER TABLE "SINTAGMA_U"."ACTE" ADD CONSTRAINT "FKACTE101315" FOREIGN KEY ("CATEGORIA_ID")
	  REFERENCES "SINTAGMA_U"."DM_CATEGORIA" ("ID") ENABLE;
  ALTER TABLE "SINTAGMA_U"."ACTE" ADD CONSTRAINT "FKACTE417776" FOREIGN KEY ("TIPUS_ACTE_ID")
	  REFERENCES "SINTAGMA_U"."DM_TIPUS_ACTE" ("ID") ENABLE;
  ALTER TABLE "SINTAGMA_U"."ACTE" ADD CONSTRAINT "FKACTE422028" FOREIGN KEY ("ESTAT_GESTIO_ESPAIS_ID")
	  REFERENCES "SINTAGMA_U"."DM_ESTAT_GESTIO_ESPAIS" ("ID") ENABLE;
  ALTER TABLE "SINTAGMA_U"."ACTE" ADD CONSTRAINT "FKACTE499691" FOREIGN KEY ("ESTAT_GESTIO_INVITACIO_ID")
	  REFERENCES "SINTAGMA_U"."DM_ESTAT_GESTIO_INVITACIO" ("ID") ENABLE;
  ALTER TABLE "SINTAGMA_U"."ACTE" ADD CONSTRAINT "FKACTE565313" FOREIGN KEY ("PRESIDENT_ID")
	  REFERENCES "SINTAGMA_U"."DM_PRESIDENT" ("ID") ENABLE;
  ALTER TABLE "SINTAGMA_U"."ACTE" ADD CONSTRAINT "FKACTE634685" FOREIGN KEY ("SECTOR_ID")
	  REFERENCES "SINTAGMA_U"."DM_SECTOR" ("ID") ENABLE;
  ALTER TABLE "SINTAGMA_U"."ACTE" ADD CONSTRAINT "FKACTE720609" FOREIGN KEY ("ELEMENT_PRINCIPAL_ID")
	  REFERENCES "SINTAGMA_U"."ELEMENT_PRINCIPAL" ("ID") ENABLE;
  ALTER TABLE "SINTAGMA_U"."ACTE" ADD CONSTRAINT "FKACTE765939" FOREIGN KEY ("PETICIONARI_ID")
	  REFERENCES "SINTAGMA_U"."DM_PETICIONARI" ("ID") ENABLE;
  ALTER TABLE "SINTAGMA_U"."ACTE" ADD CONSTRAINT "FKACTE776168" FOREIGN KEY ("ESTAT_ACTE_ID")
	  REFERENCES "SINTAGMA_U"."DM_ESTAT_ACTE" ("ID") ENABLE;
