--------------------------------------------------------
--  Ref Constraints for Table ANNEX_ASPECTE
--------------------------------------------------------

  ALTER TABLE "SINTAGMA_U"."ANNEX_ASPECTE" ADD CONSTRAINT "FKANNEX_ASPE70609" FOREIGN KEY ("ASPECTE_ID")
	  REFERENCES "SINTAGMA_U"."ASPECTE" ("ID") ENABLE;
  ALTER TABLE "SINTAGMA_U"."ANNEX_ASPECTE" ADD CONSTRAINT "FKANNEX_ASPE75374" FOREIGN KEY ("TIPUS_SUPORT_ID")
	  REFERENCES "SINTAGMA_U"."DM_TIPUS_SUPORT" ("ID") ENABLE;
  ALTER TABLE "SINTAGMA_U"."ANNEX_ASPECTE" ADD CONSTRAINT "FKANNEX_ASPE98704" FOREIGN KEY ("DOCUMENT_ID")
	  REFERENCES "SINTAGMA_U"."DOCUMENT" ("ID") ENABLE;
