--------------------------------------------------------
--  Ref Constraints for Table ANNEX_REGISTRE
--------------------------------------------------------

  ALTER TABLE "SINTAGMA_U"."ANNEX_REGISTRE" ADD CONSTRAINT "FKANNEX_REGI550428" FOREIGN KEY ("DOCUMENT_ID")
	  REFERENCES "SINTAGMA_U"."DOCUMENT" ("ID") ENABLE;
  ALTER TABLE "SINTAGMA_U"."ANNEX_REGISTRE" ADD CONSTRAINT "FKANNEX_REGI863017" FOREIGN KEY ("REGISTRE_ID")
	  REFERENCES "SINTAGMA_U"."REGISTRE" ("ID") ENABLE;
