--------------------------------------------------------
--  Ref Constraints for Table ANNEX_ACTE
--------------------------------------------------------

  ALTER TABLE "SINTAGMA_U"."ANNEX_ACTE" ADD CONSTRAINT "FKANNEX_ACTE323460" FOREIGN KEY ("ACTE_ID")
	  REFERENCES "SINTAGMA_U"."ACTE" ("ID") ENABLE;
  ALTER TABLE "SINTAGMA_U"."ANNEX_ACTE" ADD CONSTRAINT "FKANNEX_ACTE352641" FOREIGN KEY ("DOCUMENT_ID")
	  REFERENCES "SINTAGMA_U"."DOCUMENT" ("ID") ENABLE;
  ALTER TABLE "SINTAGMA_U"."ANNEX_ACTE" ADD CONSTRAINT "FKANNEX_ACTE670688" FOREIGN KEY ("TIPUS_SUPORT_ID")
	  REFERENCES "SINTAGMA_U"."DM_TIPUS_SUPORT" ("ID") ENABLE;
