--------------------------------------------------------
--  Ref Constraints for Table COMENTARI_ACTE
--------------------------------------------------------

  ALTER TABLE "SINTAGMA_U"."COMENTARI_ACTE" ADD CONSTRAINT "FKCOMENTARI_ACTE376237" FOREIGN KEY ("COMENTARI_ID")
	  REFERENCES "SINTAGMA_U"."COMENTARI" ("ID") ENABLE;
  ALTER TABLE "SINTAGMA_U"."COMENTARI_ACTE" ADD CONSTRAINT "FKCOMENTARI_ACTE423341" FOREIGN KEY ("ACTE_ID")
	  REFERENCES "SINTAGMA_U"."ACTE" ("ID") ENABLE;
