--------------------------------------------------------
--  Ref Constraints for Table COMENTARI_ASPECTE
--------------------------------------------------------

  ALTER TABLE "SINTAGMA_U"."COMENTARI_ASPECTE" ADD CONSTRAINT "FKCOMENTARI_ASPECTE376237" FOREIGN KEY ("COMENTARI_ID")
	  REFERENCES "SINTAGMA_U"."COMENTARI" ("ID") ENABLE;
  ALTER TABLE "SINTAGMA_U"."COMENTARI_ASPECTE" ADD CONSTRAINT "FKCOMENTARI_ASPECTE423341" FOREIGN KEY ("ASPECTE_ID")
	  REFERENCES "SINTAGMA_U"."ASPECTE" ("ID") ENABLE;
