--------------------------------------------------------
--  Ref Constraints for Table CONTACTE
--------------------------------------------------------

  ALTER TABLE "SINTAGMA_U"."CONTACTE" ADD CONSTRAINT "FKCONTACTE01" FOREIGN KEY ("CARREC_ID")
	  REFERENCES "SINTAGMA_U"."DM_CARREC" ("ID") ENABLE;
  ALTER TABLE "SINTAGMA_U"."CONTACTE" ADD CONSTRAINT "FKCONTACTE02" FOREIGN KEY ("CONTACTE_ORIGEN_ID")
	  REFERENCES "SINTAGMA_U"."CONTACTE" ("ID") ENABLE;
  ALTER TABLE "SINTAGMA_U"."CONTACTE" ADD CONSTRAINT "FKCONTACTE03" FOREIGN KEY ("SUBJECTE_ID")
	  REFERENCES "SINTAGMA_U"."SUBJECTE" ("ID") ENABLE;
  ALTER TABLE "SINTAGMA_U"."CONTACTE" ADD CONSTRAINT "FKCONTACTE04" FOREIGN KEY ("ADRECA_ID")
	  REFERENCES "SINTAGMA_U"."ADRECA" ("ID") ENABLE;
  ALTER TABLE "SINTAGMA_U"."CONTACTE" ADD CONSTRAINT "FKCONTACTE05" FOREIGN KEY ("TIPUS_CONTACTE_ID")
	  REFERENCES "SINTAGMA_U"."DM_TIPUS_CONTACTE" ("ID") ENABLE;
  ALTER TABLE "SINTAGMA_U"."CONTACTE" ADD CONSTRAINT "FKCONTACTE06" FOREIGN KEY ("AMBIT_ID")
	  REFERENCES "SINTAGMA_U"."DM_AMBIT" ("ID") ENABLE;
  ALTER TABLE "SINTAGMA_U"."CONTACTE" ADD CONSTRAINT "FKCONTACTE07" FOREIGN KEY ("ENTITAT_ID")
	  REFERENCES "SINTAGMA_U"."DM_ENTITAT" ("ID") ENABLE;
  ALTER TABLE "SINTAGMA_U"."CONTACTE" ADD CONSTRAINT "FKCONTACTE08" FOREIGN KEY ("VISIBILITAT_ID")
	  REFERENCES "SINTAGMA_U"."DM_VISIBILITAT" ("ID") ENABLE;
