--------------------------------------------------------
--  Ref Constraints for Table CONTACTE_TELEFON
--------------------------------------------------------

  ALTER TABLE "SINTAGMA_U"."CONTACTE_TELEFON" ADD CONSTRAINT "FKCONTACTE_TEL01" FOREIGN KEY ("TIPUS_TELEFON_ID")
	  REFERENCES "SINTAGMA_U"."DM_TIPUS_TELEFON" ("ID") ENABLE;
  ALTER TABLE "SINTAGMA_U"."CONTACTE_TELEFON" ADD CONSTRAINT "FKCONTACTE_TEL02" FOREIGN KEY ("CONTACTE_ID")
	  REFERENCES "SINTAGMA_U"."CONTACTE" ("ID") ENABLE;
