--------------------------------------------------------
--  Ref Constraints for Table CONTACTE_CONSENTIMENT
--------------------------------------------------------

  ALTER TABLE "SINTAGMA_U"."CONTACTE_CONSENTIMENT" ADD CONSTRAINT "FKCONTACTE_CON01" FOREIGN KEY ("DOCUMENT_ID")
	  REFERENCES "SINTAGMA_U"."DOCUMENT" ("ID") ENABLE;
  ALTER TABLE "SINTAGMA_U"."CONTACTE_CONSENTIMENT" ADD CONSTRAINT "FKCONTACTE_CON02" FOREIGN KEY ("CONTACTE_ID")
	  REFERENCES "SINTAGMA_U"."CONTACTE" ("ID") ENABLE;
