--------------------------------------------------------
--  Ref Constraints for Table CONTACTE_CLASSIFICACIO
--------------------------------------------------------

  ALTER TABLE "SINTAGMA_U"."CONTACTE_CLASSIFICACIO" ADD CONSTRAINT "FKCONTACTE_CL01" FOREIGN KEY ("CONTACTE_ID")
	  REFERENCES "SINTAGMA_U"."CONTACTE" ("ID") ENABLE;
  ALTER TABLE "SINTAGMA_U"."CONTACTE_CLASSIFICACIO" ADD CONSTRAINT "FKCONTACTE_CL02" FOREIGN KEY ("CLASSIFICACIO_ID")
	  REFERENCES "SINTAGMA_U"."DM_CLASSIFICACIO" ("ID") ENABLE;
