--------------------------------------------------------
--  Ref Constraints for Table CONVIDAT_TELEFON
--------------------------------------------------------

  ALTER TABLE "SINTAGMA_U"."CONVIDAT_TELEFON" ADD CONSTRAINT "FKCONVIDAT_T805471" FOREIGN KEY ("CONVIDAT_ID")
	  REFERENCES "SINTAGMA_U"."CONVIDAT" ("ID") ENABLE;
  ALTER TABLE "SINTAGMA_U"."CONVIDAT_TELEFON" ADD CONSTRAINT "FKCONVIDAT_T858558" FOREIGN KEY ("TIPUS_TELEFON_ID")
	  REFERENCES "SINTAGMA_U"."DM_TIPUS_TELEFON" ("ID") ENABLE;
