--------------------------------------------------------
--  Ref Constraints for Table CONVIDAT_OBSEQUI
--------------------------------------------------------

  ALTER TABLE "SINTAGMA_U"."CONVIDAT_OBSEQUI" ADD CONSTRAINT "FKOBSEQUI_CO122479" FOREIGN KEY ("CONVIDAT_ID")
	  REFERENCES "SINTAGMA_U"."CONVIDAT" ("ID") ENABLE;
  ALTER TABLE "SINTAGMA_U"."CONVIDAT_OBSEQUI" ADD CONSTRAINT "FKOBSEQUI_CO472489" FOREIGN KEY ("OBSEQUI_ID")
	  REFERENCES "SINTAGMA_U"."DM_OBSEQUI" ("ID") ENABLE;
