--------------------------------------------------------
--  Ref Constraints for Table CONVIDAT
--------------------------------------------------------

  ALTER TABLE "SINTAGMA_U"."CONVIDAT" ADD CONSTRAINT "FKCONVIDAT156941" FOREIGN KEY ("CONTACTE_ID")
	  REFERENCES "SINTAGMA_U"."CONTACTE" ("ID") ENABLE;
  ALTER TABLE "SINTAGMA_U"."CONVIDAT" ADD CONSTRAINT "FKCONVIDAT297469" FOREIGN KEY ("ESTAT_CONFIRMACIO_ID")
	  REFERENCES "SINTAGMA_U"."DM_ESTAT_CONFIRMACIO" ("ID") ENABLE;
  ALTER TABLE "SINTAGMA_U"."CONVIDAT" ADD CONSTRAINT "FKCONVIDAT350170" FOREIGN KEY ("TIPUS_VIA_INVITACIO_ID")
	  REFERENCES "SINTAGMA_U"."DM_TIPUS_VIA_INVITACIO" ("ID") ENABLE;
  ALTER TABLE "SINTAGMA_U"."CONVIDAT" ADD CONSTRAINT "FKCONVIDAT377638" FOREIGN KEY ("TIPUS_VIA_RESPOSTA_ID")
	  REFERENCES "SINTAGMA_U"."DM_TIPUS_VIA_RESPOSTA" ("ID") ENABLE;
  ALTER TABLE "SINTAGMA_U"."CONVIDAT" ADD CONSTRAINT "FKCONVIDAT535871" FOREIGN KEY ("INICIATIVA_RESPOSTA_ID")
	  REFERENCES "SINTAGMA_U"."DM_INICIATIVA_RESPOSTA" ("ID") ENABLE;
  ALTER TABLE "SINTAGMA_U"."CONVIDAT" ADD CONSTRAINT "FKCONVIDAT658217" FOREIGN KEY ("ACTE_ID")
	  REFERENCES "SINTAGMA_U"."ACTE" ("ID") ENABLE;
  ALTER TABLE "SINTAGMA_U"."CONVIDAT" ADD CONSTRAINT "FKCONVIDAT658517" FOREIGN KEY ("DECISIO_ASSISTENCIA_ID")
	  REFERENCES "SINTAGMA_U"."DM_DECISIO_ASSISTENCIA" ("ID") ENABLE;
  ALTER TABLE "SINTAGMA_U"."CONVIDAT" ADD CONSTRAINT "FKCONVIDAT714461" FOREIGN KEY ("CONTACTE_CLASSIFICACIO_ID")
	  REFERENCES "SINTAGMA_U"."CONTACTE_CLASSIFICACIO" ("ID") ENABLE;
