--------------------------------------------------------
--  Ref Constraints for Table CONVIDAT_ACOMPANYANT
--------------------------------------------------------

  ALTER TABLE "SINTAGMA_U"."CONVIDAT_ACOMPANYANT" ADD CONSTRAINT "FKACOMPANYAN164290" FOREIGN KEY ("CONVIDAT_ID")
	  REFERENCES "SINTAGMA_U"."CONVIDAT" ("ID") ENABLE;
  ALTER TABLE "SINTAGMA_U"."CONVIDAT_ACOMPANYANT" ADD CONSTRAINT "FKACOMPANYAN164291" FOREIGN KEY ("ESTAT_CONFIRMACIO_ID")
	  REFERENCES "SINTAGMA_U"."DM_ESTAT_CONFIRMACIO" ("ID") ENABLE;
  ALTER TABLE "SINTAGMA_U"."CONVIDAT_ACOMPANYANT" ADD CONSTRAINT "FKACOMPANYAN164292" FOREIGN KEY ("DECISIO_ASSISTENCIA_ID")
	  REFERENCES "SINTAGMA_U"."DM_DECISIO_ASSISTENCIA" ("ID") ENABLE;
