--------------------------------------------------------
--  Ref Constraints for Table DM_DECISIO_AGENDA
--------------------------------------------------------

  ALTER TABLE "SINTAGMA_U"."DM_DECISIO_AGENDA" ADD CONSTRAINT "FKDM_DECISIO00001" FOREIGN KEY ("AFECTA_AGENDA_ID")
	  REFERENCES "SINTAGMA_U"."DM_AFECTA_AGENDA" ("ID") ENABLE;
  ALTER TABLE "SINTAGMA_U"."DM_DECISIO_AGENDA" ADD CONSTRAINT "FKDM_DECISIO81470" FOREIGN KEY ("AMBIT_ID")
	  REFERENCES "SINTAGMA_U"."DM_AMBIT" ("ID") ENABLE;
