--------------------------------------------------------
--  Ref Constraints for Table DOCUMENT_BAIXA_SUBJECTE
--------------------------------------------------------

  ALTER TABLE "SINTAGMA_U"."DOCUMENT_BAIXA_SUBJECTE" ADD CONSTRAINT "FKDOCUMENT_BS01" FOREIGN KEY ("SUBJECTE_ID")
	  REFERENCES "SINTAGMA_U"."SUBJECTE" ("ID") ENABLE;
  ALTER TABLE "SINTAGMA_U"."DOCUMENT_BAIXA_SUBJECTE" ADD CONSTRAINT "FKDOCUMENT_BS02" FOREIGN KEY ("DOCUMENT_ID")
	  REFERENCES "SINTAGMA_U"."DOCUMENT" ("ID") ENABLE;
