--------------------------------------------------------
--  Ref Constraints for Table ELEMENTS_RELACIONATS
--------------------------------------------------------

  ALTER TABLE "SINTAGMA_U"."ELEMENTS_RELACIONATS" ADD CONSTRAINT "FKELEMENTS_R413766" FOREIGN KEY ("ELEMENT_PRINCIPAL2_ID")
	  REFERENCES "SINTAGMA_U"."ELEMENT_PRINCIPAL" ("ID") ENABLE;
  ALTER TABLE "SINTAGMA_U"."ELEMENTS_RELACIONATS" ADD CONSTRAINT "FKELEMENTS_R413767" FOREIGN KEY ("ELEMENT_PRINCIPAL1_ID")
	  REFERENCES "SINTAGMA_U"."ELEMENT_PRINCIPAL" ("ID") ENABLE;
