--------------------------------------------------------
--  Ref Constraints for Table ELEMENT_SECUNDARI
--------------------------------------------------------

  ALTER TABLE "SINTAGMA_U"."ELEMENT_SECUNDARI" ADD CONSTRAINT "FKELEMENT_SE117582" FOREIGN KEY ("PREFIX_ID")
	  REFERENCES "SINTAGMA_U"."DM_PREFIX" ("ID") ENABLE;
  ALTER TABLE "SINTAGMA_U"."ELEMENT_SECUNDARI" ADD CONSTRAINT "FKELEMENT_SE151296" FOREIGN KEY ("ORIGEN_ID")
	  REFERENCES "SINTAGMA_U"."DM_ORIGEN_ELEMENT" ("ID") ENABLE;
  ALTER TABLE "SINTAGMA_U"."ELEMENT_SECUNDARI" ADD CONSTRAINT "FKELEMENT_SE371596" FOREIGN KEY ("ELEMENT_PRINCIPAL_ID")
	  REFERENCES "SINTAGMA_U"."ELEMENT_PRINCIPAL" ("ID") ENABLE;
  ALTER TABLE "SINTAGMA_U"."ELEMENT_SECUNDARI" ADD CONSTRAINT "FKELEMENT_SE796422" FOREIGN KEY ("ASPECTE_ID")
	  REFERENCES "SINTAGMA_U"."ASPECTE" ("ID") ENABLE;
  ALTER TABLE "SINTAGMA_U"."ELEMENT_SECUNDARI" ADD CONSTRAINT "FKELEMENT_SE801187" FOREIGN KEY ("TIPUS_SUPORT_ID")
	  REFERENCES "SINTAGMA_U"."DM_TIPUS_SUPORT" ("ID") ENABLE;
  ALTER TABLE "SINTAGMA_U"."ELEMENT_SECUNDARI" ADD CONSTRAINT "FKELEMENT_SE808187" FOREIGN KEY ("NUMERO_REGISTRE_GENERAL_ID")
	  REFERENCES "SINTAGMA_U"."REGISTRE" ("ID") ENABLE;
