--------------------------------------------------------
--  Ref Constraints for Table HISTORIC_TRUCADA
--------------------------------------------------------

  ALTER TABLE "SINTAGMA_U"."HISTORIC_TRUCADA" ADD CONSTRAINT "FKHISTORIC_TR02" FOREIGN KEY ("RAO_ID")
	  REFERENCES "SINTAGMA_U"."DM_RAO" ("ID") ENABLE;
  ALTER TABLE "SINTAGMA_U"."HISTORIC_TRUCADA" ADD CONSTRAINT "FKHISTORIC_TR03" FOREIGN KEY ("ESTAT_TRUCADA_ID")
	  REFERENCES "SINTAGMA_U"."DM_ESTAT_TRUCADA" ("ID") ENABLE;
  ALTER TABLE "SINTAGMA_U"."HISTORIC_TRUCADA" ADD CONSTRAINT "FKHISTORIC_TR04" FOREIGN KEY ("TRUCADA_ID")
	  REFERENCES "SINTAGMA_U"."TRUCADA" ("ID") ENABLE;
  ALTER TABLE "SINTAGMA_U"."HISTORIC_TRUCADA" ADD CONSTRAINT "FKHISTORIC_TR05" FOREIGN KEY ("SENTIT_ID")
	  REFERENCES "SINTAGMA_U"."DM_SENTIT_TRUCADA" ("ID") ENABLE;
