--------------------------------------------------------
--  Ref Constraints for Table RASTRE_ASPECTE
--------------------------------------------------------

  ALTER TABLE "SINTAGMA_U"."RASTRE_ASPECTE" ADD CONSTRAINT "FKRASTRE_ASPECTE561971" FOREIGN KEY ("RASTRE_ID")
	  REFERENCES "SINTAGMA_U"."RASTRE" ("ID") ENABLE;
  ALTER TABLE "SINTAGMA_U"."RASTRE_ASPECTE" ADD CONSTRAINT "FKRASTRE_ASPECTE561972" FOREIGN KEY ("ASPECTE_ID")
	  REFERENCES "SINTAGMA_U"."ASPECTE" ("ID") ENABLE;
