--------------------------------------------------------
--  Ref Constraints for Table SUBJECTE
--------------------------------------------------------

  ALTER TABLE "SINTAGMA_U"."SUBJECTE" ADD CONSTRAINT "FKSUBJECTE01" FOREIGN KEY ("TRACTAMENT_ID")
	  REFERENCES "SINTAGMA_U"."DM_TRACTAMENT" ("ID") ENABLE;
  ALTER TABLE "SINTAGMA_U"."SUBJECTE" ADD CONSTRAINT "FKSUBJECTE02" FOREIGN KEY ("IDIOMA_ID")
	  REFERENCES "SINTAGMA_U"."DM_IDIOMA" ("ID") ENABLE;
  ALTER TABLE "SINTAGMA_U"."SUBJECTE" ADD CONSTRAINT "FKSUBJECTE03" FOREIGN KEY ("TIPUS_SUBJECTE_ID")
	  REFERENCES "SINTAGMA_U"."DM_TIPUS_SUBJECTE" ("ID") ENABLE;
  ALTER TABLE "SINTAGMA_U"."SUBJECTE" ADD CONSTRAINT "FKSUBJECTE04" FOREIGN KEY ("AMBIT_ID")
	  REFERENCES "SINTAGMA_U"."DM_AMBIT" ("ID") ENABLE;
  ALTER TABLE "SINTAGMA_U"."SUBJECTE" ADD CONSTRAINT "FKSUBJECTE05" FOREIGN KEY ("PRIORITAT_ID")
	  REFERENCES "SINTAGMA_U"."DM_PRIORITAT" ("ID") ENABLE;
  ALTER TABLE "SINTAGMA_U"."SUBJECTE" ADD CONSTRAINT "FKSUBJECTE06" FOREIGN KEY ("ARTICLE_ID")
	  REFERENCES "SINTAGMA_U"."DM_ARTICLE" ("ID") ENABLE;
