--------------------------------------------------------
--  Ref Constraints for Table TITULAR_FORA_TELEFON
--------------------------------------------------------

  ALTER TABLE "SINTAGMA_U"."TITULAR_FORA_TELEFON" ADD CONSTRAINT "FKTITULAR_FO360858" FOREIGN KEY ("TITULAR_FORA_ID")
	  REFERENCES "SINTAGMA_U"."TITULAR_FORA" ("ID") ENABLE;
  ALTER TABLE "SINTAGMA_U"."TITULAR_FORA_TELEFON" ADD CONSTRAINT "FKTITULAR_FO851767" FOREIGN KEY ("TIPUS_TELEFON_ID")
	  REFERENCES "SINTAGMA_U"."DM_TIPUS_TELEFON" ("ID") ENABLE;
