--------------------------------------------------------
--  Ref Constraints for Table TITULAR_FORA
--------------------------------------------------------

  ALTER TABLE "SINTAGMA_U"."TITULAR_FORA" ADD CONSTRAINT "FKTITULAR_FO01" FOREIGN KEY ("TRACTAMENT_ID")
	  REFERENCES "SINTAGMA_U"."DM_TRACTAMENT" ("ID") ENABLE;
  ALTER TABLE "SINTAGMA_U"."TITULAR_FORA" ADD CONSTRAINT "FKTITULAR_FO620544" FOREIGN KEY ("CONTACTE_ID")
	  REFERENCES "SINTAGMA_U"."CONTACTE" ("ID") ENABLE;
  ALTER TABLE "SINTAGMA_U"."TITULAR_FORA" ADD CONSTRAINT "FKTITULAR_FO877092" FOREIGN KEY ("ASPECTE_ID")
	  REFERENCES "SINTAGMA_U"."ASPECTE" ("ID") ENABLE;
