--------------------------------------------------------
--  Ref Constraints for Table TRANSICIO_TRAMITACIO
--------------------------------------------------------

  ALTER TABLE "SINTAGMA_U"."TRANSICIO_TRAMITACIO" ADD CONSTRAINT "FKTRANSICIO_000001" FOREIGN KEY ("AMBIT_ID")
	  REFERENCES "SINTAGMA_U"."DM_AMBIT" ("ID") ENABLE;
  ALTER TABLE "SINTAGMA_U"."TRANSICIO_TRAMITACIO" ADD CONSTRAINT "FKTRANSICIO_143222" FOREIGN KEY ("ACCIO_DESTI_ID")
	  REFERENCES "SINTAGMA_U"."DM_SUBTIPUS_ACCIO" ("ID") ENABLE;
  ALTER TABLE "SINTAGMA_U"."TRANSICIO_TRAMITACIO" ADD CONSTRAINT "FKTRANSICIO_605771" FOREIGN KEY ("ACCIO_ORIGEN_ID")
	  REFERENCES "SINTAGMA_U"."DM_SUBTIPUS_ACCIO" ("ID") ENABLE;
