--------------------------------------------------------
--  Ref Constraints for Table TRUCADA
--------------------------------------------------------

  ALTER TABLE "SINTAGMA_U"."TRUCADA" ADD CONSTRAINT "FKTRUCADA01" FOREIGN KEY ("ENTITAT_ID")
	  REFERENCES "SINTAGMA_U"."DM_ENTITAT" ("ID") ENABLE;
  ALTER TABLE "SINTAGMA_U"."TRUCADA" ADD CONSTRAINT "FKTRUCADA02" FOREIGN KEY ("SENTIT_ID")
	  REFERENCES "SINTAGMA_U"."DM_SENTIT_TRUCADA" ("ID") ENABLE;
  ALTER TABLE "SINTAGMA_U"."TRUCADA" ADD CONSTRAINT "FKTRUCADA03" FOREIGN KEY ("CONTACTE_ID")
	  REFERENCES "SINTAGMA_U"."CONTACTE" ("ID") ENABLE;
  ALTER TABLE "SINTAGMA_U"."TRUCADA" ADD CONSTRAINT "FKTRUCADA04" FOREIGN KEY ("DESTINATARI_PERSONA_ID")
	  REFERENCES "SINTAGMA_U"."DM_DESTINATARI_PERSONA" ("ID") ENABLE;
  ALTER TABLE "SINTAGMA_U"."TRUCADA" ADD CONSTRAINT "FKTRUCADA05" FOREIGN KEY ("ESTAT_TRUCADA_ID")
	  REFERENCES "SINTAGMA_U"."DM_ESTAT_TRUCADA" ("ID") ENABLE;
