--------------------------------------------------------
--  Ref Constraints for Table TRUCADA_ELEMENT_PRINCIPAL
--------------------------------------------------------

  ALTER TABLE "SINTAGMA_U"."TRUCADA_ELEMENT_PRINCIPAL" ADD CONSTRAINT "FKTRUCADA_EL406176" FOREIGN KEY ("ELEMENT_PRINCIPAL_ID")
	  REFERENCES "SINTAGMA_U"."ELEMENT_PRINCIPAL" ("ID") ENABLE;
  ALTER TABLE "SINTAGMA_U"."TRUCADA_ELEMENT_PRINCIPAL" ADD CONSTRAINT "FKTRUCADA_EL645987" FOREIGN KEY ("TRUCADA_ID")
	  REFERENCES "SINTAGMA_U"."TRUCADA" ("ID") ENABLE;
