--------------------------------------------------------
--  DDL for Package Body A0_00_TRUNCATES
--------------------------------------------------------

  CREATE OR REPLACE PACKAGE BODY "SINTAGMA_U"."A0_00_TRUNCATES" AS

  PROCEDURE ALTER_DISABLE AS
  BEGIN
    
                            ALTER TABLE A0_ACCIO disable CONSTRAINT A0_FKACCIO171138;										
                        ALTER TABLE A0_ACCIO disable CONSTRAINT A0_FKACCIO632433;										
                        ALTER TABLE A0_ACCIO disable CONSTRAINT A0_FKACCIO838514;										
                        ALTER TABLE A0_ACCIO disable CONSTRAINT A0_FKACCIO382248;										
                        ALTER TABLE A0_ACCIO disable CONSTRAINT A0_FKACCIO96718;											
                        ALTER TABLE A0_ACOMPANYANT disable CONSTRAINT A0_FKACOMPANYANT01;								
                        ALTER TABLE A0_ACOMPANYANT disable CONSTRAINT A0_FKACOMPANYANT02;								
                        --ALTER TABLE A0_ACTE disable CONSTRAINT A0_FKACTE720609;											
                        ALTER TABLE A0_ACTE disable CONSTRAINT A0_FKACTE417776;											
                        ALTER TABLE A0_ACTE disable CONSTRAINT A0_FKACTE101315;											
                        ALTER TABLE A0_ACTE disable CONSTRAINT A0_FKACTE634685;											
                        ALTER TABLE A0_ACTE disable CONSTRAINT A0_FKACTE565313;											
                        ALTER TABLE A0_ACTE disable CONSTRAINT A0_FKACTE765939;											
                        ALTER TABLE A0_ACTE disable CONSTRAINT A0_FKACTE776168;											
                        ALTER TABLE A0_ACTE disable CONSTRAINT A0_FKACTE499691;											
                        ALTER TABLE A0_ACTE disable CONSTRAINT A0_FKACTE422028;											
                        ALTER TABLE A0_AGENDA_DELEGACIO disable CONSTRAINT A0_FKAGENDA_DEL891825;						
                        ALTER TABLE A0_AGENDA_DELEGACIO disable CONSTRAINT A0_FKAGENDA_DEL409051;						
                        ALTER TABLE A0_ANNEX_ACTE disable CONSTRAINT A0_FKANNEX_ACTE323460;								
                        ALTER TABLE A0_ANNEX_ACTE disable CONSTRAINT A0_FKANNEX_ACTE352641;								
                        ALTER TABLE A0_ANNEX_ACTE disable CONSTRAINT A0_FKANNEX_ACTE670688;								
                        ALTER TABLE A0_ANNEX_ASPECTE disable CONSTRAINT A0_FKANNEX_ASPE98704;							
                        ALTER TABLE A0_ANNEX_ASPECTE disable CONSTRAINT A0_FKANNEX_ASPE70609;							
                        ALTER TABLE A0_ANNEX_ASPECTE disable CONSTRAINT A0_FKANNEX_ASPE75374;							
                        ALTER TABLE A0_ANNEX_REGISTRE disable CONSTRAINT A0_FKANNEX_REGI863017;							
                        ALTER TABLE A0_ANNEX_REGISTRE disable CONSTRAINT A0_FKANNEX_REGI550428;							
                        ALTER TABLE A0_ASPECTE disable CONSTRAINT A0_FKASPECTE57560;										
                        ALTER TABLE A0_ASPECTE disable CONSTRAINT A0_FKASPECTE695500;									
                        ALTER TABLE A0_CLASSIFICACIO_ARXIU disable  CONSTRAINT A0_FKCLASSIFICA822831;					
                        ALTER TABLE A0_CLASSIFICACIO_ARXIU disable  CONSTRAINT A0_FKCLASSIFICA172830;					
                        ALTER TABLE A0_CLASSIFICACIO_ARXIU disable  CONSTRAINT A0_FKCLASSIFICA601394;					
                        ALTER TABLE A0_COMANDA disable CONSTRAINT A0_FKCOMANDA114314;									
                        ALTER TABLE A0_COMANDA disable CONSTRAINT A0_FKCOMANDA657374;									
                        ALTER TABLE A0_COMANDA disable CONSTRAINT A0_FKCOMANDA778890;									
                        ALTER TABLE A0_COMENTARI disable CONSTRAINT A0_FKCOMENTARI872492;								
                        ALTER TABLE A0_CONTACTE disable CONSTRAINT A0_FKCONTACTE01;										
                        ALTER TABLE A0_CONTACTE disable CONSTRAINT A0_FKCONTACTE02;										
                        ALTER TABLE A0_CONTACTE disable CONSTRAINT A0_FKCONTACTE03;										
                        ALTER TABLE A0_CONTACTE disable CONSTRAINT A0_FKCONTACTE04;										
                        ALTER TABLE A0_CONTACTE disable CONSTRAINT A0_FKCONTACTE05;										
                        ALTER TABLE A0_CONTACTE disable CONSTRAINT A0_FKCONTACTE06;										
                        ALTER TABLE A0_CONTACTE disable CONSTRAINT A0_FKCONTACTE07;										
                        ALTER TABLE A0_CONTACTE disable CONSTRAINT A0_FKCONTACTE08;										
                        ALTER TABLE A0_CONTACTE_CLASSIFICACIO disable CONSTRAINT A0_FKCONTACTE_CL01;						
                        ALTER TABLE A0_CONTACTE_CLASSIFICACIO disable CONSTRAINT A0_FKCONTACTE_CL02;						
                        ALTER TABLE A0_CONTACTE_CONSENTIMENT disable CONSTRAINT A0_FKCONTACTE_CON01;						
                        ALTER TABLE A0_CONTACTE_CONSENTIMENT disable CONSTRAINT A0_FKCONTACTE_CON02;						
                        ALTER TABLE A0_CONTACTE_CORREU disable CONSTRAINT A0_FKCONTACTE_CO01;							
                        ALTER TABLE A0_CONTACTE_TELEFON disable  CONSTRAINT A0_FKCONTACTE_TEL01;						
                        ALTER TABLE A0_CONTACTE_TELEFON disable  CONSTRAINT A0_FKCONTACTE_TEL02;						
                        ALTER TABLE A0_CONVIDAT disable CONSTRAINT A0_FKCONVIDAT156941;									
                        ALTER TABLE A0_CONVIDAT disable CONSTRAINT A0_FKCONVIDAT658217;									
                        ALTER TABLE A0_CONVIDAT disable CONSTRAINT A0_FKCONVIDAT297469;									
                        ALTER TABLE A0_CONVIDAT disable CONSTRAINT A0_FKCONVIDAT350170;									
                        ALTER TABLE A0_CONVIDAT disable CONSTRAINT A0_FKCONVIDAT535871;									
                        ALTER TABLE A0_CONVIDAT disable CONSTRAINT A0_FKCONVIDAT377638;									
                        --ALTER TABLE A0_CONVIDAT disable CONSTRAINT A0_FKCONVIDAT3776389;									
                        ALTER TABLE A0_CONVIDAT disable CONSTRAINT A0_FKCONVIDAT658517;									
                        ALTER TABLE A0_CONVIDAT_ACOMPANYANT disable CONSTRAINT A0_FKACOMPANYAN164290;					
                        ALTER TABLE A0_CONVIDAT_CORREU disable CONSTRAINT A0_FKCONVIDAT_C759264;							
                        ALTER TABLE A0_CONVIDAT_OBSEQUI disable CONSTRAINT A0_FKOBSEQUI_CO472489;						
                        ALTER TABLE A0_CONVIDAT_OBSEQUI disable CONSTRAINT A0_FKOBSEQUI_CO122479;						
                        ALTER TABLE A0_CONVIDAT_TELEFON disable CONSTRAINT A0_FKCONVIDAT_T858558;						
                        ALTER TABLE A0_CONVIDAT_TELEFON disable CONSTRAINT A0_FKCONVIDAT_T805471;						
                        ALTER TABLE A0_CONVIDAT_ZONA disable CONSTRAINT A0_FKCONVIDAT_Z742497;							
                        ALTER TABLE A0_CONVIDAT_ZONA disable CONSTRAINT A0_FKCONVIDAT_Z173948;							
                        ALTER TABLE A0_DADES_HISTORIC disable CONSTRAINT A0_FKDADES_HIST01;								
                        ALTER TABLE A0_DM_AFECTA_AGENDA disable CONSTRAINT A0_FKDM_AFECTA_AGENDA ;						
                        ALTER TABLE A0_DM_AFECTA_AGENDA disable CONSTRAINT A0_FKDM_AMBIT ;								
                        ALTER TABLE A0_DM_ARTICLE disable  CONSTRAINT A0_FKDM_ARTICLE ;									
                        ALTER TABLE A0_DM_BARRI disable CONSTRAINT A0_FKDM_BARRI ;										
                        ALTER TABLE A0_DM_BARRI disable CONSTRAINT A0_FKDM_BARRI948924;									
                        ALTER TABLE A0_DM_CARREC disable CONSTRAINT A0_FKDM_CARREC ;										
                        ALTER TABLE A0_DM_CATALEG_DOCUMENT disable CONSTRAINT A0_FKDM_CATALEG_DOCUMENT ;					
                        ALTER TABLE A0_DM_CATALEG_DOCUMENT disable CONSTRAINT A0_FKDM_CATALEG772201;						
                        ALTER TABLE A0_DM_CATEGORIA disable CONSTRAINT A0_FKDM_CATEGORIA ;								
                        ALTER TABLE A0_DM_CLASSIFICACIO disable CONSTRAINT A0_FKDM_CLASSIF01;							
                        ALTER TABLE A0_DM_CLASSIFICACIO disable CONSTRAINT A0_FKDM_CLASSIF02;							
                        ALTER TABLE A0_DM_CONTRACTE disable CONSTRAINT A0_FKDM_CONTRACTE ;								
                        ALTER TABLE A0_DM_CONF_FUN_VISUALS disable CONSTRAINT A0_FKDM_FUNVIS01;							
                        ALTER TABLE A0_DM_DECISIO_AGENDA disable CONSTRAINT A0_FKDM_DECISIO_AGENDA ;						
                        ALTER TABLE A0_DM_DECISIO_AGENDA disable CONSTRAINT A0_FKDM_DECISIO81470;						
                        ALTER TABLE A0_DM_DESTINATARI_PERSONA disable CONSTRAINT A0_FKDM_DESTINATARI_PERSONA ;			
                        ALTER TABLE A0_DM_DESTI_DELEGACIO disable CONSTRAINT A0_FKDM_DESTI_DELEGACIO ;					
                        ALTER TABLE A0_DM_DESTI_DELEGACIO disable CONSTRAINT A0_FKDM_DESTI_D256754;						
                        ALTER TABLE A0_DM_DISTRICTE disable  CONSTRAINT A0_FKDM_DISTRICTE ;								
                        ALTER TABLE A0_DM_DISTRICTE disable  CONSTRAINT A0_FKDM_DISTRIC824155;							
                        ALTER TABLE A0_DM_ESPAI disable CONSTRAINT A0_FKDM_ESPAI ;										
                        ALTER TABLE A0_DM_ESPECIFIC disable CONSTRAINT A0_FKDM_ESPECIFIC ;								
                        ALTER TABLE A0_DM_ESPECIFIC disable CONSTRAINT A0_FKDM_ESPECIF772201;							
                        ALTER TABLE A0_DM_ESTAT_ACTE disable CONSTRAINT A0_FKDM_ESTAT_ACTE ;								
                        ALTER TABLE A0_DM_ESTAT_COMANDA disable CONSTRAINT A0_FKDM_ESTAT_COMANDA ;						
                        ALTER TABLE A0_DM_ESTAT_CONFIRMACIO disable CONSTRAINT A0_FKDM_ESTAT_CONFIRMACIO ;				
                        ALTER TABLE A0_DM_ESTAT_ELEMENT disable CONSTRAINT A0_FKDM_ESTAT_ELEMENT ;						
                        ALTER TABLE A0_DM_ESTAT_ELEMENT disable CONSTRAINT A0_FKDM_ESTAT_E718849;						
                        ALTER TABLE A0_DM_ESTAT_GESTIO_ESPAIS disable CONSTRAINT A0_FKDM_ESTAT_GESTIO_ESPAIS ;			
                        ALTER TABLE A0_DM_ESTAT_GESTIO_INVITACIO disable CONSTRAINT A0_FKDM_ESTAT_GESTIO_INVITACIO  ;	
                        ALTER TABLE A0_DM_ESTAT_TRUCADA disable CONSTRAINT A0_FKDM_ESTAT_TRUCADA ;						
                        ALTER TABLE A0_DM_INICIATIVA_RESPOSTA disable CONSTRAINT A0_FKDM_INICIATIVA_RESPOSTA ;			
                        ALTER TABLE A0_DM_LLOC disable CONSTRAINT A0_FKDM_LLOC ;											
                        ALTER TABLE A0_DM_LLOC disable CONSTRAINT A0_FKDM_LLOC112985;									
                        ALTER TABLE A0_DM_OBSEQUI disable CONSTRAINT A0_FKDM_OBSEQUI ;									
                        ALTER TABLE A0_DM_OBSEQUI disable CONSTRAINT A0_FKDM_OBSEQUI01;									
                        ALTER TABLE A0_DM_ORIGEN_ELEMENT disable CONSTRAINT A0_FKDM_ORIGEN_ELEMENT ;						
                        ALTER TABLE A0_DM_ORIGEN_ELEMENT disable CONSTRAINT A0_FKDM_ORIGEN_960643;						
                        ALTER TABLE A0_DM_PAS_ACCIO disable CONSTRAINT A0_FKDM_PAS_ACCIO ;								
                        ALTER TABLE A0_DM_PAS_ACCIO disable CONSTRAINT A0_FKDM_PAS_ACC433894;							
                        ALTER TABLE A0_DM_PAS_ACCIO disable CONSTRAINT A0_FKDM_PAS_ACC332958;							
                        ALTER TABLE A0_DM_PETICIONARI disable CONSTRAINT A0_FKDM_PETICIONARI ;							
                        ALTER TABLE A0_DM_PLANTILLA_ESPAI disable CONSTRAINT A0_FKDM_PLANTILLA_ESPAI ;					
                        ALTER TABLE A0_DM_PLANTILLA_ESPAI disable CONSTRAINT A0_FKDM_PLANTIL403231;						
                        ALTER TABLE A0_DM_PREFIX disable CONSTRAINT A0_FKDM_PREFIX ;										
                        ALTER TABLE A0_DM_PREFIX disable CONSTRAINT A0_FKDM_PREFIX837097;								
                        ALTER TABLE A0_DM_PREFIX_ANY disable CONSTRAINT A0_FKDM_PREFIX_ANY ;								
                        ALTER TABLE A0_DM_PREFIX_ANY disable CONSTRAINT A0_FKDM_PREFIX_824530;							
                        ALTER TABLE A0_DM_PRESIDENT disable CONSTRAINT A0_FKDM_PRESIDENT ;								
                        ALTER TABLE A0_DM_PRIORITAT disable CONSTRAINT A0_FKDM_PRIORITAT ;								
                        ALTER TABLE A0_DM_PRIORITAT disable CONSTRAINT A0_FKDM_PRIORITAT01;								
                        ALTER TABLE A0_DM_PRIORITAT_ELEMENT disable CONSTRAINT A0_FKDM_PRIORITAT_ELEMENT ;				
                        ALTER TABLE A0_DM_PRIORITAT_ELEMENT disable CONSTRAINT A0_FKDM_PRIORIT739647;					
                        ALTER TABLE A0_DM_PROVEIDOR disable CONSTRAINT A0_FKDM_PROVEIDOR ;								
                        ALTER TABLE A0_DM_RAO disable CONSTRAINT A0_FKDM_RAO01;											
                        ALTER TABLE A0_DM_SECTOR disable CONSTRAINT A0_FKDM_SECTOR ;										
                        ALTER TABLE A0_DM_SENTIT_TRUCADA disable CONSTRAINT A0_FKDM_SENTIT_TRUCADA ;						
                        ALTER TABLE A0_DM_SERIE disable CONSTRAINT A0_FKDM_SERIE ;										
                        ALTER TABLE A0_DM_SERIE disable CONSTRAINT A0_FKDM_SERIE767678;									
                        ALTER TABLE A0_DM_SUBTIPUS_ACCIO disable CONSTRAINT A0_FKDM_SUBTIPUS_ACCIO ;						
                        ALTER TABLE A0_DM_SUBTIPUS_ACCIO disable CONSTRAINT A0_FKDM_SUBTIPU602859;						
                        ALTER TABLE A0_DM_SUBTIPUS_ACCIO disable CONSTRAINT A0_FKDM_SUBTIPU252151;						
                        ALTER TABLE A0_DM_TIPOLOGIA_CLASSIFICACIO disable CONSTRAINT A0_FKDM_TIPOLOG01;					
                        ALTER TABLE A0_DM_TIPOLOGIA_OBSEQUI disable CONSTRAINT A0_FKDM_TIPOLOGIA_OBSEQUI ;				
                        ALTER TABLE A0_DM_TIPUS_ACCIO disable CONSTRAINT A0_FKDM_TIPUS_ACCIO ;							
                        ALTER TABLE A0_DM_TIPUS_ACCIO disable CONSTRAINT A0_FKDM_TIPUS_A470625;							
                        ALTER TABLE A0_DM_TIPUS_ACTE disable CONSTRAINT A0_FKDM_TIPUS_ACTE ;								
                        ALTER TABLE A0_DM_TIPUS_AGENDA disable CONSTRAINT A0_FKDM_TIPUS_AGENDA ;							
                        ALTER TABLE A0_DM_TIPUS_AGENDA disable CONSTRAINT A0_FKDM_TIPUS_A563939;							
                        ALTER TABLE A0_DM_TIPUS_AMBIT disable CONSTRAINT A0_FKDM_TIPUS_AMBIT ;							
                        ALTER TABLE A0_DM_TIPUS_AMBIT disable CONSTRAINT A0_FKDM_TIPUS_A173671;							
                        ALTER TABLE A0_DM_TIPUS_ARG disable CONSTRAINT A0_FKDM_TIPUS_ARG ;								
                        ALTER TABLE A0_DM_TIPUS_ARG disable CONSTRAINT A0_FKDM_TIPUS_A982617;							
                        ALTER TABLE A0_DM_TIPUS_CONTACTE disable CONSTRAINT A0_FKDM_TIPUS_CONTACTE ;						
                        ALTER TABLE A0_DM_TIPUS_DATA disable CONSTRAINT A0_FKDM_TIPUS_DATA ;								
                        ALTER TABLE A0_DM_TIPUS_DATA disable CONSTRAINT A0_FKDM_TIPUS_D6766;								
                        ALTER TABLE A0_DM_TIPUS_ELEMENT disable CONSTRAINT A0_FKDM_TIPUS_ELEMENT ;						
                        ALTER TABLE A0_DM_TIPUS_ELEMENT disable CONSTRAINT A0_FKDM_TIPUS_E835726;						
                        ALTER TABLE A0_DM_TIPUS_SERVEI disable CONSTRAINT A0_FKDM_TIPUS_SERVEI ;							
                        ALTER TABLE A0_DM_TIPUS_SERVEI disable CONSTRAINT A0_FKDM_TIPUS_S621794;							
                        ALTER TABLE A0_DM_TIPUS_SERVEI disable CONSTRAINT A0_FKDM_TIPUS_S536825;							
                        ALTER TABLE A0_DM_TIPUS_SUBJECTE disable CONSTRAINT A0_FKDM_TIPUS_SUBJECTE ;						
                        ALTER TABLE A0_DM_TIPUS_SUPORT disable CONSTRAINT A0_FKDM_TIPUS_S980283;							
                        ALTER TABLE A0_DM_TIPUS_TELEFON disable CONSTRAINT A0_FKDM_TIPUS_TELEFON ;						
                        ALTER TABLE A0_DM_TIPUS_TEMA disable CONSTRAINT A0_FKDM_TIPUS_TEMA ;								
                        ALTER TABLE A0_DM_TIPUS_TEMA disable CONSTRAINT A0_FKDM_TIPUS_T526482;							
                        ALTER TABLE A0_DM_TIPUS_VIA_INVITACIO disable CONSTRAINT A0_FKDM_TIPUS_VIA_INVITACIO ;			
                        ALTER TABLE A0_DM_TIPUS_VIA_RESPOSTA disable CONSTRAINT A0_FKDM_TIPUS_VIA_RESPOSTA ;				
                        ALTER TABLE A0_DM_TRACTAMENT disable CONSTRAINT A0_FKDM_TRACTAMENT ;								
                        ALTER TABLE A0_DM_VISIBILITAT disable CONSTRAINT A0_FKDM_VISIBILITAT ;							
                        ALTER TABLE A0_DOCUMENT disable CONSTRAINT A0_FKDOCUMENT01;										
                        ALTER TABLE A0_DOCUMENT_BAIXA_SUBJECTE disable CONSTRAINT A0_FKDOCUMENT_BS01;					
                        ALTER TABLE A0_DOCUMENT_BAIXA_SUBJECTE disable CONSTRAINT A0_FKDOCUMENT_BS02;					
                        ALTER TABLE A0_DOSSIER disable CONSTRAINT A0_FKDOSSIER281181;									
                        ALTER TABLE A0_DOSSIER disable CONSTRAINT A0_FKDOSSIER189288;									
                        ALTER TABLE A0_ELEMENTS_RELACIONATS disable CONSTRAINT A0_FKELEMENTS_R413767;					
                        ALTER TABLE A0_ELEMENTS_RELACIONATS disable CONSTRAINT A0_FKELEMENTS_R413766;					
                        ALTER TABLE A0_ELEMENT_PRINCIPAL disable CONSTRAINT A0_FKELEMENT_PR16069;						
                        ALTER TABLE A0_ELEMENT_PRINCIPAL disable CONSTRAINT A0_FKELEMENT_PR561971;						
                        ALTER TABLE A0_ELEMENT_PRINCIPAL disable CONSTRAINT A0_FKELEMENT_PR600648;						
                        ALTER TABLE A0_ELEMENT_PRINCIPAL disable CONSTRAINT A0_FKELEMENT_PR30487;						
                        ALTER TABLE A0_ELEMENT_PRINCIPAL disable CONSTRAINT A0_FKELEMENT_PR176225;						
                        ALTER TABLE A0_ELEMENT_PRINCIPAL disable CONSTRAINT A0_FKELEMENT_PR18178;						
                        ALTER TABLE A0_ELEMENT_PRINCIPAL disable CONSTRAINT A0_FKELEMENT_PR284981;						
                        ALTER TABLE A0_ELEMENT_PRINCIPAL disable CONSTRAINT A0_FKELEMENT_PR634362;						
                        ALTER TABLE A0_ELEMENT_PRINCIPAL disable CONSTRAINT A0_FKELEMENT_PR335151;						
                        ALTER TABLE A0_ELEMENT_PRINCIPAL disable CONSTRAINT A0_FKELEMENT_PR469506;						
                        ALTER TABLE A0_ELEMENT_PRINCIPAL disable CONSTRAINT A0_FKELEMENT_PR471364;						
                        ALTER TABLE A0_ELEMENT_PRINCIPAL disable CONSTRAINT A0_FKELEMENT_PR20834;						
                        ALTER TABLE A0_ELEMENT_PRINCIPAL disable CONSTRAINT A0_FKELEMENT_PR16148;						
                        ALTER TABLE A0_ELEMENT_SECUNDARI disable CONSTRAINT A0_FKELEMENT_SE371596;						
                        ALTER TABLE A0_ELEMENT_SECUNDARI disable CONSTRAINT A0_FKELEMENT_SE796422;						
                        ALTER TABLE A0_ELEMENT_SECUNDARI disable CONSTRAINT A0_FKELEMENT_SE151296;						
                        ALTER TABLE A0_ELEMENT_SECUNDARI disable CONSTRAINT A0_FKELEMENT_SE117582;						
                        ALTER TABLE A0_ELEMENT_SECUNDARI disable CONSTRAINT A0_FKELEMENT_SE808187;						
                        ALTER TABLE A0_ELEMENT_SECUNDARI disable CONSTRAINT A0_FKELEMENT_SE801187;						
                        ALTER TABLE A0_ENTRADA_AGENDA disable CONSTRAINT A0_FKENTRADA_AG59765;							
                        ALTER TABLE A0_ENTRADA_AGENDA disable CONSTRAINT A0_FKENTRADA_AG443925;							
                        ALTER TABLE A0_ENTRADA_AGENDA disable CONSTRAINT A0_FKENTRADA_AG642221;							
                        ALTER TABLE A0_ENTRADA_AGENDA disable CONSTRAINT A0_FKENTRADA_AG385363;							
                        ALTER TABLE A0_ENTRADA_AGENDA disable CONSTRAINT A0_FKENTRADA_AG711320;							
                        ALTER TABLE A0_ENTRADA_AGENDA disable CONSTRAINT A0_FKENTRADA_AG608766;							
                        ALTER TABLE A0_ENTRADA_AGENDA disable CONSTRAINT A0_FKENTRADA_AG971241;							
                        ALTER TABLE A0_ESPAI_ACTE disable CONSTRAINT A0_FKESPAI_ACTE423341;								
                        ALTER TABLE A0_ESPAI_ACTE disable CONSTRAINT A0_FKESPAI_ACTE376237;								
                        ALTER TABLE A0_ESPAI_ACTE_CONFIG disable CONSTRAINT A0_FKESPAI_ACTE362713;						
                        ALTER TABLE A0_ESPAI_ACTE_CONFIG disable CONSTRAINT A0_FKESPAI_ACTE938901;						
                        ALTER TABLE A0_HISTORIC_TRUCADA disable CONSTRAINT A0_FKHISTORIC_TR02;							
                        ALTER TABLE A0_HISTORIC_TRUCADA disable CONSTRAINT A0_FKHISTORIC_TR03;							
                        ALTER TABLE A0_HISTORIC_TRUCADA disable CONSTRAINT A0_FKHISTORIC_TR04;							
                        ALTER TABLE A0_HISTORIC_TRUCADA disable CONSTRAINT A0_FKHISTORIC_TR05;							
                        ALTER TABLE A0_MANTENIMENT_DM disable CONSTRAINT A0_FKMANTENIMENT362713;							
                        ALTER TABLE A0_OBSEQUI_ENTREGAT disable CONSTRAINT A0_FKOBSEQUI_EN611806;						
                        ALTER TABLE A0_OBSEQUI_INVENTARI disable CONSTRAINT A0_FKINVENTARI01;							
                        ALTER TABLE A0_PARAMETRE disable CONSTRAINT A0_FKPARAMETRE ;										
                        ALTER TABLE A0_PERSONA_RELACIONADA disable CONSTRAINT A0_FKPERSONA_REL01;						
                        ALTER TABLE A0_PLANTILLA_CONFIG_ESPAI disable CONSTRAINT A0_FKPLANTILLA_348577;					
                        ALTER TABLE A0_RASTRE disable CONSTRAINT A0_FKRASTRE714460;										
                        ALTER TABLE A0_SUBJECTE disable CONSTRAINT A0_FKSUBJECTE01;										
                        ALTER TABLE A0_SUBJECTE disable CONSTRAINT A0_FKSUBJECTE02;										
                        ALTER TABLE A0_SUBJECTE disable CONSTRAINT A0_FKSUBJECTE03;										
                        ALTER TABLE A0_SUBJECTE disable CONSTRAINT A0_FKSUBJECTE04;										
                        ALTER TABLE A0_SUBJECTE disable CONSTRAINT A0_FKSUBJECTE05;										
                        ALTER TABLE A0_SUBJECTE disable CONSTRAINT A0_FKSUBJECTE06;										
                        ALTER TABLE A0_TITULAR_DINS disable CONSTRAINT A0_FKTITULAR_DI811638;							
                        ALTER TABLE A0_TITULAR_FORA disable CONSTRAINT A0_FKTITULAR_FO877092;							
                        ALTER TABLE A0_TITULAR_FORA disable CONSTRAINT A0_FKTITULAR_FO620544;							
                        ALTER TABLE A0_TITULAR_FORA_CORREU disable CONSTRAINT A0_FKTITULAR_FO509608;						
                        ALTER TABLE A0_TITULAR_FORA_TELEFON disable CONSTRAINT A0_FKTITULAR_FO851767;					
                        ALTER TABLE A0_TITULAR_FORA_TELEFON disable CONSTRAINT A0_FKTITULAR_FO360858;					
                        ALTER TABLE A0_TRANSICIO_TRAMITACIO disable CONSTRAINT A0_FKTRANSICIO_TRAMITACIO ;				
                        ALTER TABLE A0_TRANSICIO_TRAMITACIO disable CONSTRAINT A0_FKTRANSICIO_605771;					
                        ALTER TABLE A0_TRANSICIO_TRAMITACIO disable CONSTRAINT A0_FKTRANSICIO_143222;					
                        ALTER TABLE A0_TRUCADA disable CONSTRAINT A0_FKTRUCADA01;										
                        ALTER TABLE A0_TRUCADA disable CONSTRAINT A0_FKTRUCADA02;										
                        ALTER TABLE A0_TRUCADA disable CONSTRAINT A0_FKTRUCADA03;										
                        ALTER TABLE A0_TRUCADA disable CONSTRAINT A0_FKTRUCADA04;										
                        ALTER TABLE A0_TRUCADA disable CONSTRAINT A0_FKTRUCADA05;										
                        ALTER TABLE A0_TRUCADA_ELEMENT_PRINCIPAL disable CONSTRAINT A0_FKTRUCADA_EL406176;				
                        ALTER TABLE A0_TRUCADA_ELEMENT_PRINCIPAL disable CONSTRAINT A0_FKTRUCADA_EL645987;				
                        ALTER TABLE A0_ZONA disable CONSTRAINT A0_FKZONA544016;		  
    
  COMMIT;  
  END;

  PROCEDURE TRUNCATES AS
  BEGIN
                            TRUNCATE TABLE  A0_ACCIO;
                            TRUNCATE TABLE  A0_ACOMPANYANT;
                            
                            
                            TRUNCATE TABLE  A0_AGENDA_DELEGACIO;
                            TRUNCATE TABLE  A0_ANNEX_ACTE;
                            TRUNCATE TABLE  A0_ANNEX_ASPECTE;
                            TRUNCATE TABLE  A0_ANNEX_REGISTRE;
                            TRUNCATE TABLE  A0_ASPECTE;
                            TRUNCATE TABLE  A0_CLASSIFICACIO_ARXIU;
                            TRUNCATE TABLE  A0_COMANDA;
                            TRUNCATE TABLE  A0_COMENTARI;
                            
                            
                            TRUNCATE TABLE  A0_CONTACTE_CONSENTIMENT;
                            TRUNCATE TABLE  A0_CONTACTE_CORREU;
                            TRUNCATE TABLE  A0_CONTACTE_TELEFON;
                            TRUNCATE TABLE  A0_CONVIDAT;
                            TRUNCATE TABLE  A0_CONVIDAT_ACOMPANYANT;
                            TRUNCATE TABLE  A0_CONVIDAT_CORREU;
                            TRUNCATE TABLE  A0_CONVIDAT_OBSEQUI;
                            TRUNCATE TABLE  A0_CONVIDAT_TELEFON;
                            TRUNCATE TABLE  A0_CONVIDAT_ZONA;
                            TRUNCATE TABLE  A0_DADES_HISTORIC;
                            
                            TRUNCATE TABLE  A0_DOCUMENT;
                            TRUNCATE TABLE  A0_DOCUMENT_BAIXA_SUBJECTE;
                            TRUNCATE TABLE  A0_DOSSIER;
                            TRUNCATE TABLE  A0_ELEMENTS_RELACIONATS;
                            TRUNCATE TABLE  A0_ELEMENT_PRINCIPAL;
                            TRUNCATE TABLE  A0_ELEMENT_SECUNDARI;
                            TRUNCATE TABLE  A0_ENTRADA_AGENDA;
                            TRUNCATE TABLE  A0_ESPAI_ACTE;
                            TRUNCATE TABLE  A0_ESPAI_ACTE_CONFIG;
                            TRUNCATE TABLE  A0_HISTORIC_TRUCADA;
                            TRUNCATE TABLE  A0_MANTENIMENT_DM;
                            TRUNCATE TABLE  A0_OBSEQUI_ENTREGAT;
                            TRUNCATE TABLE  A0_OBSEQUI_INVENTARI;
                            TRUNCATE TABLE  A0_PARAMETRE;
                            TRUNCATE TABLE  A0_PERSONA_RELACIONADA;
                            TRUNCATE TABLE  A0_PLANTILLA_CONFIG_ESPAI;
                            TRUNCATE TABLE  A0_RASTRE;
                            TRUNCATE TABLE  A0_REGISTRE;
                            
                            TRUNCATE TABLE  A0_SUBJECTES_ARTICLE;
                            TRUNCATE TABLE  A0_TITULAR_DINS;
                            TRUNCATE TABLE  A0_TITULAR_FORA;
                            TRUNCATE TABLE  A0_TITULAR_FORA_CORREU;
                            TRUNCATE TABLE  A0_TITULAR_FORA_TELEFON;
                            TRUNCATE TABLE  A0_TRANSICIO_TRAMITACIO;
                            
                            TRUNCATE TABLE  A0_ZONA;
                            
                            TRUNCATE TABLE  A0_CONTACTE_CLASSIFICACIO;
                            TRUNCATE TABLE  A0_DM_CLASSIFICACIO;
                            
                            
                            
                            TRUNCATE TABLE  A0_CONTACTE;
                            TRUNCATE TABLE  A0_ACTE;
                            TRUNCATE TABLE  A0_SUBJECTE;
                            
                            TRUNCATE TABLE  A0_DM_CARREC;
                            TRUNCATE TABLE  A0_ADRECA;
                            
                            TRUNCATE TABLE  A0_DM_AFECTA_AGENDA;
                            
                            TRUNCATE TABLE  A0_DM_ARTICLE;
                            TRUNCATE TABLE  A0_DM_BARRI;
                            
                            TRUNCATE TABLE  A0_DM_CATALEG_DOCUMENT;
                            TRUNCATE TABLE  A0_DM_CATEGORIA;
                            
                            TRUNCATE TABLE  A0_DM_CONF_FUN_VISUALS;
                            TRUNCATE TABLE  A0_DM_CONTRACTE;
                            TRUNCATE TABLE  A0_DM_DECISIO_AGENDA;
                            TRUNCATE TABLE  A0_DM_DECISIO_ASSISTENCIA;
                            TRUNCATE TABLE  A0_DM_DESTINATARI_PERSONA;
                            TRUNCATE TABLE  A0_DM_DESTI_DELEGACIO;
                            TRUNCATE TABLE  A0_DM_DISTRICTE;
                            TRUNCATE TABLE  A0_DM_ENTITAT;
                            TRUNCATE TABLE  A0_DM_ESPAI;
                            TRUNCATE TABLE  A0_DM_ESPECIFIC;
                            TRUNCATE TABLE  A0_DM_ESTAT_ACTE;
                            TRUNCATE TABLE  A0_DM_ESTAT_COMANDA;
                            TRUNCATE TABLE  A0_DM_ESTAT_CONFIRMACIO;
                            TRUNCATE TABLE  A0_DM_ESTAT_ELEMENT;
                            TRUNCATE TABLE  A0_DM_ESTAT_GESTIO_ESPAIS;
                            TRUNCATE TABLE  A0_DM_ESTAT_GESTIO_INVITACIO;
                            TRUNCATE TABLE  A0_DM_ESTAT_TRUCADA;
                            TRUNCATE TABLE  A0_DM_IDIOMA;
                            TRUNCATE TABLE  A0_DM_INICIATIVA_RESPOSTA;
                            TRUNCATE TABLE  A0_DM_LLOC;
                            TRUNCATE TABLE  A0_DM_OBSEQUI;
                            TRUNCATE TABLE  A0_DM_ORIGEN_ELEMENT;
                            TRUNCATE TABLE  A0_DM_PAS_ACCIO;
                            TRUNCATE TABLE  A0_DM_PETICIONARI;
                            TRUNCATE TABLE  A0_DM_PLANTILLA_ESPAI;
                            TRUNCATE TABLE  A0_DM_PREFIX;
                            TRUNCATE TABLE  A0_DM_PREFIX_ANY;
                            TRUNCATE TABLE  A0_DM_PRESIDENT;
                            TRUNCATE TABLE  A0_DM_PRIORITAT;
                            TRUNCATE TABLE  A0_DM_PRIORITAT_ELEMENT;
                            TRUNCATE TABLE  A0_DM_PROVEIDOR;
                            TRUNCATE TABLE  A0_DM_RAO;
                            TRUNCATE TABLE  A0_DM_SECTOR;
                            TRUNCATE TABLE  A0_DM_SENTIT_TRUCADA;
                            TRUNCATE TABLE  A0_DM_SERIE;
                            TRUNCATE TABLE  A0_DM_SUBTIPUS_ACCIO;
                            TRUNCATE TABLE  A0_DM_TIPOLOGIA_CLASSIFICACIO;
                            TRUNCATE TABLE  A0_DM_TIPOLOGIA_OBSEQUI;
                            TRUNCATE TABLE  A0_DM_TIPUS_ACCIO;
                            TRUNCATE TABLE  A0_DM_TIPUS_ACTE;
                            TRUNCATE TABLE  A0_DM_TIPUS_AGENDA;
                            TRUNCATE TABLE  A0_DM_TIPUS_AMBIT;
                            TRUNCATE TABLE  A0_DM_TIPUS_ARG;
                            TRUNCATE TABLE  A0_DM_TIPUS_CONTACTE;
                            TRUNCATE TABLE  A0_DM_TIPUS_DATA;
                            TRUNCATE TABLE  A0_DM_TIPUS_ELEMENT;
                            TRUNCATE TABLE  A0_DM_TIPUS_SERVEI;
                            TRUNCATE TABLE  A0_DM_TIPUS_SUBJECTE;
                            TRUNCATE TABLE  A0_DM_TIPUS_SUPORT;
                            TRUNCATE TABLE  A0_DM_TIPUS_TELEFON;
                            TRUNCATE TABLE  A0_DM_TIPUS_TEMA;
                            TRUNCATE TABLE  A0_DM_TIPUS_VIA_INVITACIO;
                            TRUNCATE TABLE  A0_DM_TIPUS_VIA_RESPOSTA;
                            TRUNCATE TABLE  A0_DM_TRACTAMENT;
                            TRUNCATE TABLE  A0_DM_VISIBILITAT;
                            
                            TRUNCATE TABLE  A0_TRUCADA;
                            TRUNCATE TABLE  A0_TRUCADA_ELEMENT_PRINCIPAL;
                            TRUNCATE TABLE  A0_TRUCADA_TEMA;
                            TRUNCATE TABLE  A0_DM_AMBIT;
  COMMIT;  
  END;

  PROCEDURE ALTER_ENABLE AS
  BEGIN
                                    ALTER TABLE A0_ACCIO ENABLE CONSTRAINT A0_FKACCIO171138;										
                                    ALTER TABLE A0_ACCIO ENABLE CONSTRAINT A0_FKACCIO632433;										
                                    ALTER TABLE A0_ACCIO ENABLE CONSTRAINT A0_FKACCIO838514;										
                                    ALTER TABLE A0_ACCIO ENABLE CONSTRAINT A0_FKACCIO382248;										
                                    ALTER TABLE A0_ACCIO ENABLE CONSTRAINT A0_FKACCIO96718;											
                                    ALTER TABLE A0_ACOMPANYANT ENABLE CONSTRAINT A0_FKACOMPANYANT01;								
                                    ALTER TABLE A0_ACOMPANYANT ENABLE CONSTRAINT A0_FKACOMPANYANT02;								
                                    --ALTER TABLE A0_ACTE ENABLE CONSTRAINT A0_FKACTE720609;											
                                    ALTER TABLE A0_ACTE ENABLE CONSTRAINT A0_FKACTE417776;											
                                    ALTER TABLE A0_ACTE ENABLE CONSTRAINT A0_FKACTE101315;											
                                    ALTER TABLE A0_ACTE ENABLE CONSTRAINT A0_FKACTE634685;											
                                    ALTER TABLE A0_ACTE ENABLE CONSTRAINT A0_FKACTE565313;											
                                    ALTER TABLE A0_ACTE ENABLE CONSTRAINT A0_FKACTE765939;											
                                    ALTER TABLE A0_ACTE ENABLE CONSTRAINT A0_FKACTE776168;											
                                    ALTER TABLE A0_ACTE ENABLE CONSTRAINT A0_FKACTE499691;											
                                    ALTER TABLE A0_ACTE ENABLE CONSTRAINT A0_FKACTE422028;											
                                    ALTER TABLE A0_AGENDA_DELEGACIO ENABLE CONSTRAINT A0_FKAGENDA_DEL891825;						
                                    ALTER TABLE A0_AGENDA_DELEGACIO ENABLE CONSTRAINT A0_FKAGENDA_DEL409051;						
                                    ALTER TABLE A0_ANNEX_ACTE ENABLE CONSTRAINT A0_FKANNEX_ACTE323460;								
                                    ALTER TABLE A0_ANNEX_ACTE ENABLE CONSTRAINT A0_FKANNEX_ACTE352641;								
                                    ALTER TABLE A0_ANNEX_ACTE ENABLE CONSTRAINT A0_FKANNEX_ACTE670688;								
                                    ALTER TABLE A0_ANNEX_ASPECTE ENABLE CONSTRAINT A0_FKANNEX_ASPE98704;							
                                    ALTER TABLE A0_ANNEX_ASPECTE ENABLE CONSTRAINT A0_FKANNEX_ASPE70609;							
                                    ALTER TABLE A0_ANNEX_ASPECTE ENABLE CONSTRAINT A0_FKANNEX_ASPE75374;							
                                    ALTER TABLE A0_ANNEX_REGISTRE ENABLE CONSTRAINT A0_FKANNEX_REGI863017;							
                                    ALTER TABLE A0_ANNEX_REGISTRE ENABLE CONSTRAINT A0_FKANNEX_REGI550428;							
                                    ALTER TABLE A0_ASPECTE ENABLE CONSTRAINT A0_FKASPECTE57560;										
                                    ALTER TABLE A0_ASPECTE ENABLE CONSTRAINT A0_FKASPECTE695500;									
                                    ALTER TABLE A0_CLASSIFICACIO_ARXIU ENABLE  CONSTRAINT A0_FKCLASSIFICA822831;					
                                    ALTER TABLE A0_CLASSIFICACIO_ARXIU ENABLE  CONSTRAINT A0_FKCLASSIFICA172830;					
                                    ALTER TABLE A0_CLASSIFICACIO_ARXIU ENABLE  CONSTRAINT A0_FKCLASSIFICA601394;					
                                    ALTER TABLE A0_COMANDA ENABLE CONSTRAINT A0_FKCOMANDA114314;									
                                    ALTER TABLE A0_COMANDA ENABLE CONSTRAINT A0_FKCOMANDA657374;									
                                    ALTER TABLE A0_COMANDA ENABLE CONSTRAINT A0_FKCOMANDA778890;									
                                    ALTER TABLE A0_COMENTARI ENABLE CONSTRAINT A0_FKCOMENTARI872492;								
                                    ALTER TABLE A0_CONTACTE ENABLE CONSTRAINT A0_FKCONTACTE01;										
                                    ALTER TABLE A0_CONTACTE ENABLE CONSTRAINT A0_FKCONTACTE02;										
                                    ALTER TABLE A0_CONTACTE ENABLE CONSTRAINT A0_FKCONTACTE03;										
                                    ALTER TABLE A0_CONTACTE ENABLE CONSTRAINT A0_FKCONTACTE04;										
                                    ALTER TABLE A0_CONTACTE ENABLE CONSTRAINT A0_FKCONTACTE05;										
                                    ALTER TABLE A0_CONTACTE ENABLE CONSTRAINT A0_FKCONTACTE06;										
                                    ALTER TABLE A0_CONTACTE ENABLE CONSTRAINT A0_FKCONTACTE07;										
                                    ALTER TABLE A0_CONTACTE ENABLE CONSTRAINT A0_FKCONTACTE08;										
                                    ALTER TABLE A0_CONTACTE_CLASSIFICACIO ENABLE CONSTRAINT A0_FKCONTACTE_CL01;						
                                    ALTER TABLE A0_CONTACTE_CLASSIFICACIO ENABLE CONSTRAINT A0_FKCONTACTE_CL02;						
                                    ALTER TABLE A0_CONTACTE_CONSENTIMENT ENABLE CONSTRAINT A0_FKCONTACTE_CON01;						
                                    ALTER TABLE A0_CONTACTE_CONSENTIMENT ENABLE CONSTRAINT A0_FKCONTACTE_CON02;						
                                    ALTER TABLE A0_CONTACTE_CORREU ENABLE CONSTRAINT A0_FKCONTACTE_CO01;							
                                    ALTER TABLE A0_CONTACTE_TELEFON ENABLE  CONSTRAINT A0_FKCONTACTE_TEL01;						
                                    ALTER TABLE A0_CONTACTE_TELEFON ENABLE  CONSTRAINT A0_FKCONTACTE_TEL02;						
                                    ALTER TABLE A0_CONVIDAT ENABLE CONSTRAINT A0_FKCONVIDAT156941;									
                                    ALTER TABLE A0_CONVIDAT ENABLE CONSTRAINT A0_FKCONVIDAT658217;									
                                    ALTER TABLE A0_CONVIDAT ENABLE CONSTRAINT A0_FKCONVIDAT297469;									
                                    ALTER TABLE A0_CONVIDAT ENABLE CONSTRAINT A0_FKCONVIDAT350170;									
                                    ALTER TABLE A0_CONVIDAT ENABLE CONSTRAINT A0_FKCONVIDAT535871;									
                                    ALTER TABLE A0_CONVIDAT ENABLE CONSTRAINT A0_FKCONVIDAT377638;									
                                    --ALTER TABLE A0_CONVIDAT ENABLE CONSTRAINT A0_FKCONVIDAT3776389;									
                                    ALTER TABLE A0_CONVIDAT ENABLE CONSTRAINT A0_FKCONVIDAT658517;									
                                    ALTER TABLE A0_CONVIDAT_ACOMPANYANT ENABLE CONSTRAINT A0_FKACOMPANYAN164290;					
                                    ALTER TABLE A0_CONVIDAT_CORREU ENABLE CONSTRAINT A0_FKCONVIDAT_C759264;							
                                    ALTER TABLE A0_CONVIDAT_OBSEQUI ENABLE CONSTRAINT A0_FKOBSEQUI_CO472489;						
                                    ALTER TABLE A0_CONVIDAT_OBSEQUI ENABLE CONSTRAINT A0_FKOBSEQUI_CO122479;						
                                    ALTER TABLE A0_CONVIDAT_TELEFON ENABLE CONSTRAINT A0_FKCONVIDAT_T858558;						
                                    ALTER TABLE A0_CONVIDAT_TELEFON ENABLE CONSTRAINT A0_FKCONVIDAT_T805471;						
                                    ALTER TABLE A0_CONVIDAT_ZONA ENABLE CONSTRAINT A0_FKCONVIDAT_Z742497;							
                                    ALTER TABLE A0_CONVIDAT_ZONA ENABLE CONSTRAINT A0_FKCONVIDAT_Z173948;							
                                    ALTER TABLE A0_DADES_HISTORIC ENABLE CONSTRAINT A0_FKDADES_HIST01;								
                                    ALTER TABLE A0_DM_AFECTA_AGENDA ENABLE CONSTRAINT A0_FKDM_AFECTA_AGENDA ;						
                                    ALTER TABLE A0_DM_AFECTA_AGENDA ENABLE CONSTRAINT A0_FKDM_AMBIT ;								
                                    ALTER TABLE A0_DM_ARTICLE ENABLE  CONSTRAINT A0_FKDM_ARTICLE ;									
                                    ALTER TABLE A0_DM_BARRI ENABLE CONSTRAINT A0_FKDM_BARRI ;										
                                    ALTER TABLE A0_DM_BARRI ENABLE CONSTRAINT A0_FKDM_BARRI948924;									
                                    ALTER TABLE A0_DM_CARREC ENABLE CONSTRAINT A0_FKDM_CARREC ;										
                                    ALTER TABLE A0_DM_CATALEG_DOCUMENT ENABLE CONSTRAINT A0_FKDM_CATALEG_DOCUMENT ;					
                                    ALTER TABLE A0_DM_CATALEG_DOCUMENT ENABLE CONSTRAINT A0_FKDM_CATALEG772201;						
                                    ALTER TABLE A0_DM_CATEGORIA ENABLE CONSTRAINT A0_FKDM_CATEGORIA ;								
                                    ALTER TABLE A0_DM_CLASSIFICACIO ENABLE CONSTRAINT A0_FKDM_CLASSIF01;							
                                    ALTER TABLE A0_DM_CLASSIFICACIO ENABLE CONSTRAINT A0_FKDM_CLASSIF02;							
                                    ALTER TABLE A0_DM_CONTRACTE ENABLE CONSTRAINT A0_FKDM_CONTRACTE ;								
                                    ALTER TABLE A0_DM_CONF_FUN_VISUALS ENABLE CONSTRAINT A0_FKDM_FUNVIS01;							
                                    ALTER TABLE A0_DM_DECISIO_AGENDA ENABLE CONSTRAINT A0_FKDM_DECISIO_AGENDA ;						
                                    ALTER TABLE A0_DM_DECISIO_AGENDA ENABLE CONSTRAINT A0_FKDM_DECISIO81470;						
                                    ALTER TABLE A0_DM_DESTINATARI_PERSONA ENABLE CONSTRAINT A0_FKDM_DESTINATARI_PERSONA ;			
                                    ALTER TABLE A0_DM_DESTI_DELEGACIO ENABLE CONSTRAINT A0_FKDM_DESTI_DELEGACIO ;					
                                    ALTER TABLE A0_DM_DESTI_DELEGACIO ENABLE CONSTRAINT A0_FKDM_DESTI_D256754;						
                                    ALTER TABLE A0_DM_DISTRICTE ENABLE  CONSTRAINT A0_FKDM_DISTRICTE ;								
                                    ALTER TABLE A0_DM_DISTRICTE ENABLE  CONSTRAINT A0_FKDM_DISTRIC824155;							
                                    ALTER TABLE A0_DM_ESPAI ENABLE CONSTRAINT A0_FKDM_ESPAI ;										
                                    ALTER TABLE A0_DM_ESPECIFIC ENABLE CONSTRAINT A0_FKDM_ESPECIFIC ;								
                                    ALTER TABLE A0_DM_ESPECIFIC ENABLE CONSTRAINT A0_FKDM_ESPECIF772201;							
                                    ALTER TABLE A0_DM_ESTAT_ACTE ENABLE CONSTRAINT A0_FKDM_ESTAT_ACTE ;								
                                    ALTER TABLE A0_DM_ESTAT_COMANDA ENABLE CONSTRAINT A0_FKDM_ESTAT_COMANDA ;						
                                    ALTER TABLE A0_DM_ESTAT_CONFIRMACIO ENABLE CONSTRAINT A0_FKDM_ESTAT_CONFIRMACIO ;				
                                    ALTER TABLE A0_DM_ESTAT_ELEMENT ENABLE CONSTRAINT A0_FKDM_ESTAT_ELEMENT ;						
                                    ALTER TABLE A0_DM_ESTAT_ELEMENT ENABLE CONSTRAINT A0_FKDM_ESTAT_E718849;						
                                    ALTER TABLE A0_DM_ESTAT_GESTIO_ESPAIS ENABLE CONSTRAINT A0_FKDM_ESTAT_GESTIO_ESPAIS ;			
                                    ALTER TABLE A0_DM_ESTAT_GESTIO_INVITACIO ENABLE CONSTRAINT A0_FKDM_ESTAT_GESTIO_INVITACIO  ;	
                                    ALTER TABLE A0_DM_ESTAT_TRUCADA ENABLE CONSTRAINT A0_FKDM_ESTAT_TRUCADA ;						
                                    ALTER TABLE A0_DM_INICIATIVA_RESPOSTA ENABLE CONSTRAINT A0_FKDM_INICIATIVA_RESPOSTA ;			
                                    ALTER TABLE A0_DM_LLOC ENABLE CONSTRAINT A0_FKDM_LLOC ;											
                                    ALTER TABLE A0_DM_LLOC ENABLE CONSTRAINT A0_FKDM_LLOC112985;									
                                    ALTER TABLE A0_DM_OBSEQUI ENABLE CONSTRAINT A0_FKDM_OBSEQUI ;									
                                    ALTER TABLE A0_DM_OBSEQUI ENABLE CONSTRAINT A0_FKDM_OBSEQUI01;									
                                    ALTER TABLE A0_DM_ORIGEN_ELEMENT ENABLE CONSTRAINT A0_FKDM_ORIGEN_ELEMENT ;						
                                    ALTER TABLE A0_DM_ORIGEN_ELEMENT ENABLE CONSTRAINT A0_FKDM_ORIGEN_960643;						
                                    ALTER TABLE A0_DM_PAS_ACCIO ENABLE CONSTRAINT A0_FKDM_PAS_ACCIO ;								
                                    ALTER TABLE A0_DM_PAS_ACCIO ENABLE CONSTRAINT A0_FKDM_PAS_ACC433894;							
                                    ALTER TABLE A0_DM_PAS_ACCIO ENABLE CONSTRAINT A0_FKDM_PAS_ACC332958;							
                                    ALTER TABLE A0_DM_PETICIONARI ENABLE CONSTRAINT A0_FKDM_PETICIONARI ;							
                                    ALTER TABLE A0_DM_PLANTILLA_ESPAI ENABLE CONSTRAINT A0_FKDM_PLANTILLA_ESPAI ;					
                                    ALTER TABLE A0_DM_PLANTILLA_ESPAI ENABLE CONSTRAINT A0_FKDM_PLANTIL403231;						
                                    ALTER TABLE A0_DM_PREFIX ENABLE CONSTRAINT A0_FKDM_PREFIX ;										
                                    ALTER TABLE A0_DM_PREFIX ENABLE CONSTRAINT A0_FKDM_PREFIX837097;								
                                    ALTER TABLE A0_DM_PREFIX_ANY ENABLE CONSTRAINT A0_FKDM_PREFIX_ANY ;								
                                    ALTER TABLE A0_DM_PREFIX_ANY ENABLE CONSTRAINT A0_FKDM_PREFIX_824530;							
                                    ALTER TABLE A0_DM_PRESIDENT ENABLE CONSTRAINT A0_FKDM_PRESIDENT ;								
                                    ALTER TABLE A0_DM_PRIORITAT ENABLE CONSTRAINT A0_FKDM_PRIORITAT ;								
                                    ALTER TABLE A0_DM_PRIORITAT ENABLE CONSTRAINT A0_FKDM_PRIORITAT01;								
                                    ALTER TABLE A0_DM_PRIORITAT_ELEMENT ENABLE CONSTRAINT A0_FKDM_PRIORITAT_ELEMENT ;				
                                    ALTER TABLE A0_DM_PRIORITAT_ELEMENT ENABLE CONSTRAINT A0_FKDM_PRIORIT739647;					
                                    ALTER TABLE A0_DM_PROVEIDOR ENABLE CONSTRAINT A0_FKDM_PROVEIDOR ;								
                                    ALTER TABLE A0_DM_RAO ENABLE CONSTRAINT A0_FKDM_RAO01;											
                                    ALTER TABLE A0_DM_SECTOR ENABLE CONSTRAINT A0_FKDM_SECTOR ;										
                                    ALTER TABLE A0_DM_SENTIT_TRUCADA ENABLE CONSTRAINT A0_FKDM_SENTIT_TRUCADA ;						
                                    ALTER TABLE A0_DM_SERIE ENABLE CONSTRAINT A0_FKDM_SERIE ;										
                                    ALTER TABLE A0_DM_SERIE ENABLE CONSTRAINT A0_FKDM_SERIE767678;									
                                    ALTER TABLE A0_DM_SUBTIPUS_ACCIO ENABLE CONSTRAINT A0_FKDM_SUBTIPUS_ACCIO ;						
                                    ALTER TABLE A0_DM_SUBTIPUS_ACCIO ENABLE CONSTRAINT A0_FKDM_SUBTIPU602859;						
                                    ALTER TABLE A0_DM_SUBTIPUS_ACCIO ENABLE CONSTRAINT A0_FKDM_SUBTIPU252151;						
                                    --ALTER TABLE A0_DM_TIPOLOGIA_CLASSIFICACIO ENABLE CONSTRAINT A0_FKDM_TIPOLOGIA_CLASSIFICACIO ;	
                                    ALTER TABLE A0_DM_TIPOLOGIA_CLASSIFICACIO ENABLE CONSTRAINT A0_FKDM_TIPOLOG01;					
                                    ALTER TABLE A0_DM_TIPOLOGIA_OBSEQUI ENABLE CONSTRAINT A0_FKDM_TIPOLOGIA_OBSEQUI ;				
                                    ALTER TABLE A0_DM_TIPUS_ACCIO ENABLE CONSTRAINT A0_FKDM_TIPUS_ACCIO ;							
                                    ALTER TABLE A0_DM_TIPUS_ACCIO ENABLE CONSTRAINT A0_FKDM_TIPUS_A470625;							
                                    ALTER TABLE A0_DM_TIPUS_ACTE ENABLE CONSTRAINT A0_FKDM_TIPUS_ACTE ;								
                                    ALTER TABLE A0_DM_TIPUS_AGENDA ENABLE CONSTRAINT A0_FKDM_TIPUS_AGENDA ;							
                                    ALTER TABLE A0_DM_TIPUS_AGENDA ENABLE CONSTRAINT A0_FKDM_TIPUS_A563939;							
                                    ALTER TABLE A0_DM_TIPUS_AMBIT ENABLE CONSTRAINT A0_FKDM_TIPUS_AMBIT ;							
                                    ALTER TABLE A0_DM_TIPUS_AMBIT ENABLE CONSTRAINT A0_FKDM_TIPUS_A173671;							
                                    ALTER TABLE A0_DM_TIPUS_ARG ENABLE CONSTRAINT A0_FKDM_TIPUS_ARG ;								
                                    ALTER TABLE A0_DM_TIPUS_ARG ENABLE CONSTRAINT A0_FKDM_TIPUS_A982617;							
                                    ALTER TABLE A0_DM_TIPUS_CONTACTE ENABLE CONSTRAINT A0_FKDM_TIPUS_CONTACTE ;						
                                    ALTER TABLE A0_DM_TIPUS_DATA ENABLE CONSTRAINT A0_FKDM_TIPUS_DATA ;								
                                    ALTER TABLE A0_DM_TIPUS_DATA ENABLE CONSTRAINT A0_FKDM_TIPUS_D6766;								
                                    ALTER TABLE A0_DM_TIPUS_ELEMENT ENABLE CONSTRAINT A0_FKDM_TIPUS_ELEMENT ;						
                                    ALTER TABLE A0_DM_TIPUS_ELEMENT ENABLE CONSTRAINT A0_FKDM_TIPUS_E835726;						
                                    ALTER TABLE A0_DM_TIPUS_SERVEI ENABLE CONSTRAINT A0_FKDM_TIPUS_SERVEI ;							
                                    ALTER TABLE A0_DM_TIPUS_SERVEI ENABLE CONSTRAINT A0_FKDM_TIPUS_S621794;							
                                    ALTER TABLE A0_DM_TIPUS_SERVEI ENABLE CONSTRAINT A0_FKDM_TIPUS_S536825;							
                                    ALTER TABLE A0_DM_TIPUS_SUBJECTE ENABLE CONSTRAINT A0_FKDM_TIPUS_SUBJECTE ;						
                                    ALTER TABLE A0_DM_TIPUS_SUPORT ENABLE CONSTRAINT A0_FKDM_TIPUS_S980283;							
                                    ALTER TABLE A0_DM_TIPUS_TELEFON ENABLE CONSTRAINT A0_FKDM_TIPUS_TELEFON ;						
                                    ALTER TABLE A0_DM_TIPUS_TEMA ENABLE CONSTRAINT A0_FKDM_TIPUS_TEMA ;								
                                    ALTER TABLE A0_DM_TIPUS_TEMA ENABLE CONSTRAINT A0_FKDM_TIPUS_T526482;							
                                    ALTER TABLE A0_DM_TIPUS_VIA_INVITACIO ENABLE CONSTRAINT A0_FKDM_TIPUS_VIA_INVITACIO ;			
                                    ALTER TABLE A0_DM_TIPUS_VIA_RESPOSTA ENABLE CONSTRAINT A0_FKDM_TIPUS_VIA_RESPOSTA ;				
                                    ALTER TABLE A0_DM_TRACTAMENT ENABLE CONSTRAINT A0_FKDM_TRACTAMENT ;								
                                    ALTER TABLE A0_DM_VISIBILITAT ENABLE CONSTRAINT A0_FKDM_VISIBILITAT ;							
                                    ALTER TABLE A0_DOCUMENT ENABLE CONSTRAINT A0_FKDOCUMENT01;										
                                    ALTER TABLE A0_DOCUMENT_BAIXA_SUBJECTE ENABLE CONSTRAINT A0_FKDOCUMENT_BS01;					
                                    ALTER TABLE A0_DOCUMENT_BAIXA_SUBJECTE ENABLE CONSTRAINT A0_FKDOCUMENT_BS02;					
                                    ALTER TABLE A0_DOSSIER ENABLE CONSTRAINT A0_FKDOSSIER281181;									
                                    ALTER TABLE A0_DOSSIER ENABLE CONSTRAINT A0_FKDOSSIER189288;									
                                    ALTER TABLE A0_ELEMENTS_RELACIONATS ENABLE CONSTRAINT A0_FKELEMENTS_R413767;					
                                    ALTER TABLE A0_ELEMENTS_RELACIONATS ENABLE CONSTRAINT A0_FKELEMENTS_R413766;					
                                    ALTER TABLE A0_ELEMENT_PRINCIPAL ENABLE CONSTRAINT A0_FKELEMENT_PR16069;						
                                    ALTER TABLE A0_ELEMENT_PRINCIPAL ENABLE CONSTRAINT A0_FKELEMENT_PR561971;						
                                    ALTER TABLE A0_ELEMENT_PRINCIPAL ENABLE CONSTRAINT A0_FKELEMENT_PR600648;						
                                    ALTER TABLE A0_ELEMENT_PRINCIPAL ENABLE CONSTRAINT A0_FKELEMENT_PR30487;						
                                    ALTER TABLE A0_ELEMENT_PRINCIPAL ENABLE CONSTRAINT A0_FKELEMENT_PR176225;						
                                    ALTER TABLE A0_ELEMENT_PRINCIPAL ENABLE CONSTRAINT A0_FKELEMENT_PR18178;						
                                    ALTER TABLE A0_ELEMENT_PRINCIPAL ENABLE CONSTRAINT A0_FKELEMENT_PR284981;						
                                    ALTER TABLE A0_ELEMENT_PRINCIPAL ENABLE CONSTRAINT A0_FKELEMENT_PR634362;						
                                    ALTER TABLE A0_ELEMENT_PRINCIPAL ENABLE CONSTRAINT A0_FKELEMENT_PR335151;						
                                    ALTER TABLE A0_ELEMENT_PRINCIPAL ENABLE CONSTRAINT A0_FKELEMENT_PR469506;						
                                    ALTER TABLE A0_ELEMENT_PRINCIPAL ENABLE CONSTRAINT A0_FKELEMENT_PR471364;						
                                    ALTER TABLE A0_ELEMENT_PRINCIPAL ENABLE CONSTRAINT A0_FKELEMENT_PR20834;						
                                    ALTER TABLE A0_ELEMENT_PRINCIPAL ENABLE CONSTRAINT A0_FKELEMENT_PR16148;						
                                    ALTER TABLE A0_ELEMENT_SECUNDARI ENABLE CONSTRAINT A0_FKELEMENT_SE371596;						
                                    ALTER TABLE A0_ELEMENT_SECUNDARI ENABLE CONSTRAINT A0_FKELEMENT_SE796422;						
                                    ALTER TABLE A0_ELEMENT_SECUNDARI ENABLE CONSTRAINT A0_FKELEMENT_SE151296;						
                                    ALTER TABLE A0_ELEMENT_SECUNDARI ENABLE CONSTRAINT A0_FKELEMENT_SE117582;						
                                    ALTER TABLE A0_ELEMENT_SECUNDARI ENABLE CONSTRAINT A0_FKELEMENT_SE808187;						
                                    ALTER TABLE A0_ELEMENT_SECUNDARI ENABLE CONSTRAINT A0_FKELEMENT_SE801187;						
                                    ALTER TABLE A0_ENTRADA_AGENDA ENABLE CONSTRAINT A0_FKENTRADA_AG59765;							
                                    ALTER TABLE A0_ENTRADA_AGENDA ENABLE CONSTRAINT A0_FKENTRADA_AG443925;							
                                    ALTER TABLE A0_ENTRADA_AGENDA ENABLE CONSTRAINT A0_FKENTRADA_AG642221;							
                                    ALTER TABLE A0_ENTRADA_AGENDA ENABLE CONSTRAINT A0_FKENTRADA_AG385363;							
                                    ALTER TABLE A0_ENTRADA_AGENDA ENABLE CONSTRAINT A0_FKENTRADA_AG711320;							
                                    ALTER TABLE A0_ENTRADA_AGENDA ENABLE CONSTRAINT A0_FKENTRADA_AG608766;							
                                    ALTER TABLE A0_ENTRADA_AGENDA ENABLE CONSTRAINT A0_FKENTRADA_AG971241;							
                                    ALTER TABLE A0_ESPAI_ACTE ENABLE CONSTRAINT A0_FKESPAI_ACTE423341;								
                                    ALTER TABLE A0_ESPAI_ACTE ENABLE CONSTRAINT A0_FKESPAI_ACTE376237;								
                                    ALTER TABLE A0_ESPAI_ACTE_CONFIG ENABLE CONSTRAINT A0_FKESPAI_ACTE362713;						
                                    ALTER TABLE A0_ESPAI_ACTE_CONFIG ENABLE CONSTRAINT A0_FKESPAI_ACTE938901;						
                                    ALTER TABLE A0_HISTORIC_TRUCADA ENABLE CONSTRAINT A0_FKHISTORIC_TR02;							
                                    ALTER TABLE A0_HISTORIC_TRUCADA ENABLE CONSTRAINT A0_FKHISTORIC_TR03;							
                                    ALTER TABLE A0_HISTORIC_TRUCADA ENABLE CONSTRAINT A0_FKHISTORIC_TR04;							
                                    ALTER TABLE A0_HISTORIC_TRUCADA ENABLE CONSTRAINT A0_FKHISTORIC_TR05;							
                                    ALTER TABLE A0_MANTENIMENT_DM ENABLE CONSTRAINT A0_FKMANTENIMENT362713;							
                                    ALTER TABLE A0_OBSEQUI_ENTREGAT ENABLE CONSTRAINT A0_FKOBSEQUI_EN611806;						
                                    ALTER TABLE A0_OBSEQUI_INVENTARI ENABLE CONSTRAINT A0_FKINVENTARI01;							
                                    ALTER TABLE A0_PARAMETRE ENABLE CONSTRAINT A0_FKPARAMETRE ;										
                                    ALTER TABLE A0_PERSONA_RELACIONADA ENABLE CONSTRAINT A0_FKPERSONA_REL01;						
                                    ALTER TABLE A0_PLANTILLA_CONFIG_ESPAI ENABLE CONSTRAINT A0_FKPLANTILLA_348577;					
                                    ALTER TABLE A0_RASTRE ENABLE CONSTRAINT A0_FKRASTRE714460;										
                                    ALTER TABLE A0_SUBJECTE ENABLE CONSTRAINT A0_FKSUBJECTE01;										
                                    ALTER TABLE A0_SUBJECTE ENABLE CONSTRAINT A0_FKSUBJECTE02;										
                                    ALTER TABLE A0_SUBJECTE ENABLE CONSTRAINT A0_FKSUBJECTE03;										
                                    ALTER TABLE A0_SUBJECTE ENABLE CONSTRAINT A0_FKSUBJECTE04;										
                                    ALTER TABLE A0_SUBJECTE ENABLE CONSTRAINT A0_FKSUBJECTE05;										
                                    ALTER TABLE A0_SUBJECTE ENABLE CONSTRAINT A0_FKSUBJECTE06;										
                                    ALTER TABLE A0_TITULAR_DINS ENABLE CONSTRAINT A0_FKTITULAR_DI811638;							
                                    ALTER TABLE A0_TITULAR_FORA ENABLE CONSTRAINT A0_FKTITULAR_FO877092;							
                                    ALTER TABLE A0_TITULAR_FORA ENABLE CONSTRAINT A0_FKTITULAR_FO620544;							
                                    ALTER TABLE A0_TITULAR_FORA_CORREU ENABLE CONSTRAINT A0_FKTITULAR_FO509608;						
                                    ALTER TABLE A0_TITULAR_FORA_TELEFON ENABLE CONSTRAINT A0_FKTITULAR_FO851767;					
                                    ALTER TABLE A0_TITULAR_FORA_TELEFON ENABLE CONSTRAINT A0_FKTITULAR_FO360858;					
                                    ALTER TABLE A0_TRANSICIO_TRAMITACIO ENABLE CONSTRAINT A0_FKTRANSICIO_TRAMITACIO ;				
                                    ALTER TABLE A0_TRANSICIO_TRAMITACIO ENABLE CONSTRAINT A0_FKTRANSICIO_605771;					
                                    ALTER TABLE A0_TRANSICIO_TRAMITACIO ENABLE CONSTRAINT A0_FKTRANSICIO_143222;					
                                    ALTER TABLE A0_TRUCADA ENABLE CONSTRAINT A0_FKTRUCADA01;										
                                    ALTER TABLE A0_TRUCADA ENABLE CONSTRAINT A0_FKTRUCADA02;										
                                    ALTER TABLE A0_TRUCADA ENABLE CONSTRAINT A0_FKTRUCADA03;										
                                    ALTER TABLE A0_TRUCADA ENABLE CONSTRAINT A0_FKTRUCADA04;										
                                    ALTER TABLE A0_TRUCADA ENABLE CONSTRAINT A0_FKTRUCADA05;										
                                    ALTER TABLE A0_TRUCADA_ELEMENT_PRINCIPAL ENABLE CONSTRAINT A0_FKTRUCADA_EL406176;				
                                    ALTER TABLE A0_TRUCADA_ELEMENT_PRINCIPAL ENABLE CONSTRAINT A0_FKTRUCADA_EL645987;				
                                    ALTER TABLE A0_ZONA ENABLE CONSTRAINT A0_FKZONA544016;											
  COMMIT; 
  END;

END A0_00_TRUNCATES;

/
