--------------------------------------------------------
--  DDL for Package Body Z_05_ERRORES_SIAP
--------------------------------------------------------

  CREATE OR REPLACE PACKAGE BODY "SINTAGMA_U"."Z_05_ERRORES_SIAP" AS


  --GUARDAMOS LAS CLASIFICACIONES CUYO NOMBRE ES NULL
 PROCEDURE ERR_SIAP01_CLASSIFICACION_NULL IS
 BEGIN
 
    INSERT INTO ERR_SIAP01_CLASSIFICACION_NULL (ID, CODI, CLASSIFICACIO)
            SELECT ID, CODI, CLASSIFICACIO
              FROM Z_T_SIAP_CLASSIFICACIONS
             WHERE FUNC_NORMALITZAR(CLASSIFICACIO) IS NULL;
 
 COMMIT;
 END;



  PROCEDURE RESETEATOR_TABLAS IS
  BEGIN
  
    DELETE FROM ERR_SIAP01_CLASSIFICACION_NULL;
    
  
  END RESETEATOR_TABLAS;

END Z_05_ERRORES_SIAP;

/
