--------------------------------------------------------
--  DDL for Package Body Z_Z99_SECUENCIAS
--------------------------------------------------------

  CREATE OR REPLACE PACKAGE BODY "SINTAGMA_U"."Z_Z99_SECUENCIAS" AS

  PROCEDURE A0_SEQ_ACOMPANYANT IS
        Max_SEQ_ACOMPANYANT number;       
  BEGIN
    
     SELECT MAX(ID) INTO Max_SEQ_ACOMPANYANT FROM A0_ACOMPANYANT;
            
     Max_SEQ_ACOMPANYANT := Max_SEQ_ACOMPANYANT +1;
            
     SET_SEQ('A0_SEQ_ACOMPANYANT',Max_SEQ_ACOMPANYANT);    
    
  END A0_SEQ_ACOMPANYANT;



  PROCEDURE A0_SEQ_ADRECA IS
        Max_SEQ_ADRECA number;       
  BEGIN
    
     SELECT MAX(ID) INTO Max_SEQ_ADRECA FROM A0_ADRECA;
            
     Max_SEQ_ADRECA := Max_SEQ_ADRECA +1;
            
     SET_SEQ('A0_SEQ_ADRECA',Max_SEQ_ADRECA);     
   
  END A0_SEQ_ADRECA;



  PROCEDURE A0_SEQ_AGENDA_DELEGACIO IS   
        Max_SEQ_AGENDA_DELEGACIO number;       
  BEGIN
  
     SELECT MAX(ID) INTO Max_SEQ_AGENDA_DELEGACIO FROM A0_AGENDA_DELEGACIO;
            
     Max_SEQ_AGENDA_DELEGACIO := Max_SEQ_AGENDA_DELEGACIO +1;
            
     SET_SEQ('A0_SEQ_AGENDA_DELEGACIO',Max_SEQ_AGENDA_DELEGACIO);    
     
     
  END;  
  
  
  PROCEDURE A0_SEQ_CONTACTE IS   
        Max_SEQ_CONTACTE number;       
  BEGIN
  
     SELECT MAX(ID) INTO Max_SEQ_CONTACTE FROM A0_CONTACTE;
            
     Max_SEQ_CONTACTE := Max_SEQ_CONTACTE +1;
            
     SET_SEQ('A0_SEQ_CONTACTE',Max_SEQ_CONTACTE);    
     
     
  END;  
  
  
  PROCEDURE A0_SEQ_CONTACTE_CLASSIFICACIO IS   
        Max_SEQ_CONTACTE_CLASSIFICACIO number;       
  BEGIN
  
     SELECT MAX(ID) INTO Max_SEQ_CONTACTE_CLASSIFICACIO FROM A0_CONTACTE_CLASSIFICACIO;
            
     Max_SEQ_CONTACTE_CLASSIFICACIO := Max_SEQ_CONTACTE_CLASSIFICACIO +1;
            
     SET_SEQ('A0_SEQ_CONTACTE_CLASSIFICACIO',Max_SEQ_CONTACTE_CLASSIFICACIO);         
     
  END;  
  
  
  PROCEDURE A0_SEQ_CONTACTE_CORREU IS   
        Max_SEQ_CONTACTE_CORREU number;       
  BEGIN
  
     SELECT MAX(ID) INTO Max_SEQ_CONTACTE_CORREU FROM A0_CONTACTE_CORREU;
            
     Max_SEQ_CONTACTE_CORREU := Max_SEQ_CONTACTE_CORREU +1;
            
     SET_SEQ('A0_SEQ_CONTACTE_CORREU',Max_SEQ_CONTACTE_CORREU);         
     
  END;  

 
  PROCEDURE A0_SEQ_CONTACTE_TELEFON IS   
        Max_SEQ_CONTACTE_TELEFON number;       
  BEGIN
  
     SELECT MAX(ID) INTO Max_SEQ_CONTACTE_TELEFON FROM A0_CONTACTE_TELEFON;
            
     Max_SEQ_CONTACTE_TELEFON := Max_SEQ_CONTACTE_TELEFON +1;
            
     SET_SEQ('A0_SEQ_CONTACTE_TELEFON',Max_SEQ_CONTACTE_TELEFON);
     
  END;  



  PROCEDURE A0_SEQ_CONVIDAT IS   
        Max_SEQ_CONVIDAT number;       
  BEGIN
  
     SELECT MAX(ID) INTO Max_SEQ_CONVIDAT FROM A0_CONVIDAT;
            
     Max_SEQ_CONVIDAT := Max_SEQ_CONVIDAT +1;
            
     SET_SEQ('A0_SEQ_CONVIDAT',Max_SEQ_CONVIDAT);         
     
  END;  


  PROCEDURE A0_SEQ_CONVIDAT_CORREU IS   
        Max_SEQ_CONVIDAT_CORREU number;       
  BEGIN
  
     SELECT MAX(ID) INTO Max_SEQ_CONVIDAT_CORREU FROM A0_CONVIDAT_CORREU;
            
     Max_SEQ_CONVIDAT_CORREU := Max_SEQ_CONVIDAT_CORREU +1;
            
     SET_SEQ('A0_SEQ_CONVIDAT_CORREU',Max_SEQ_CONVIDAT_CORREU);         
     
  END;
  
  PROCEDURE A0_SEQ_DM_CARREC IS   
        Max_SEQ_DM_CARREC number;       
  BEGIN
  
     SELECT MAX(ID) INTO Max_SEQ_DM_CARREC FROM A0_DM_CARREC;
            
     Max_SEQ_DM_CARREC := Max_SEQ_DM_CARREC +1;
            
     SET_SEQ('A0_SEQ_DM_CARREC',Max_SEQ_DM_CARREC);         
     
  END;
  
  PROCEDURE A0_SEQ_DM_CLASSIFICACIO IS   
        Max_SEQ_DM_CLASSIFICACIO number;       
  BEGIN
  
     SELECT MAX(ID) INTO Max_SEQ_DM_CLASSIFICACIO FROM A0_DM_CLASSIFICACIO;
            
     Max_SEQ_DM_CLASSIFICACIO := Max_SEQ_DM_CLASSIFICACIO +1;
            
     SET_SEQ('A0_SEQ_DM_CLASSIFICACIO',Max_SEQ_DM_CLASSIFICACIO);         
     
  END;
  
  
    PROCEDURE A0_SEQ_DM_CONF_FUN_VISUALS IS
        Max_SEQ_DM_CONF_FUN_VISUALS number;       
  BEGIN
  
     SELECT MAX(ID) INTO Max_SEQ_DM_CONF_FUN_VISUALS FROM A0_DM_CONF_FUN_VISUALS;
            
     Max_SEQ_DM_CONF_FUN_VISUALS := Max_SEQ_DM_CONF_FUN_VISUALS +1;
            
     SET_SEQ('A0_SEQ_DM_CONF_FUN_VISUALS',Max_SEQ_DM_CONF_FUN_VISUALS);
     
  END;
  
  
  PROCEDURE A0_SEQ_DM_DESTINATARI_PERSONA IS   
        Max_SEQ_DM_DESTINATARI_PERSONA number;       
  BEGIN
  
     SELECT MAX(ID) INTO Max_SEQ_DM_DESTINATARI_PERSONA FROM A0_DM_DESTINATARI_PERSONA;
            
     Max_SEQ_DM_DESTINATARI_PERSONA := Max_SEQ_DM_DESTINATARI_PERSONA +1;
            
     SET_SEQ('A0_SEQ_DM_DESTINATARI_PERSONA',Max_SEQ_DM_DESTINATARI_PERSONA);
     
  END;
  
  
  PROCEDURE A0_SEQ_DM_ENTITAT IS   
        Max_SEQ_DM_ENTITAT number;       
  BEGIN
  
     SELECT MAX(ID) INTO Max_SEQ_DM_ENTITAT FROM A0_DM_ENTITAT;
            
     Max_SEQ_DM_ENTITAT := Max_SEQ_DM_ENTITAT +1;
            
     SET_SEQ('A0_SEQ_DM_ENTITAT',Max_SEQ_DM_ENTITAT);
     
  END;
  
  
  
  PROCEDURE A0_SEQ_DM_ESTAT_ACTE IS   
        Max_SEQ_DM_ESTAT_ACTE number;       
  BEGIN
  
     SELECT MAX(ID) INTO Max_SEQ_DM_ESTAT_ACTE FROM A0_DM_ESTAT_ACTE;
            
     Max_SEQ_DM_ESTAT_ACTE := Max_SEQ_DM_ESTAT_ACTE +1;
            
     SET_SEQ('A0_SEQ_DM_ESTAT_ACTE',Max_SEQ_DM_ESTAT_ACTE);
     
  END;
  
  
  
  
  PROCEDURE A0_SEQ_DM_ESTAT_ELEMENT IS   
        Max_SEQ_DM_ESTAT_ELEMENT number;       
  BEGIN
  
     SELECT MAX(ID) INTO Max_SEQ_DM_ESTAT_ELEMENT FROM A0_DM_ESTAT_ELEMENT;
            
     Max_SEQ_DM_ESTAT_ELEMENT := Max_SEQ_DM_ESTAT_ELEMENT +1;
            
     SET_SEQ('A0_SEQ_DM_ESTAT_ELEMENT',Max_SEQ_DM_ESTAT_ELEMENT);
     
  END;
  
  
  
  PROCEDURE A0_SEQ_DM_ORIGEN_ELEMENT IS   
        Max_SEQ_DM_ORIGEN_ELEMENT number;       
  BEGIN
  
     SELECT MAX(ID) INTO Max_SEQ_DM_ORIGEN_ELEMENT FROM A0_DM_ORIGEN_ELEMENT;
            
     Max_SEQ_DM_ORIGEN_ELEMENT := Max_SEQ_DM_ORIGEN_ELEMENT +1;
            
     SET_SEQ('A0_SEQ_DM_ORIGEN_ELEMENT',Max_SEQ_DM_ORIGEN_ELEMENT);
     
  END;
  
  
  PROCEDURE A0_SEQ_DM_PAS_ACCIO IS   
        Max_SEQ_DM_PAS_ACCIO number;       
  BEGIN
  
     SELECT MAX(ID) INTO Max_SEQ_DM_PAS_ACCIO FROM A0_DM_PAS_ACCIO;
            
     Max_SEQ_DM_PAS_ACCIO := Max_SEQ_DM_PAS_ACCIO +1;
            
     SET_SEQ('A0_SEQ_DM_PAS_ACCIO',Max_SEQ_DM_PAS_ACCIO);
     
  END;
  
  
  PROCEDURE A0_SEQ_DM_PRIORITAT_ELEMENT IS   
        Max_SEQ_DM_PRIORITAT_ELEMENT number;       
  BEGIN
  
     SELECT MAX(ID) INTO Max_SEQ_DM_PRIORITAT_ELEMENT FROM A0_DM_PRIORITAT_ELEMENT;
            
     Max_SEQ_DM_PRIORITAT_ELEMENT := Max_SEQ_DM_PRIORITAT_ELEMENT +1;
            
     SET_SEQ('A0_SEQ_DM_PRIORITAT_ELEMENT',Max_SEQ_DM_PRIORITAT_ELEMENT);
     
  END;
  
  
  PROCEDURE A0_SEQ_DM_SERIE IS   
        Max_SEQ_DM_SERIE number;       
  BEGIN
  
     SELECT MAX(ID) INTO Max_SEQ_DM_SERIE FROM A0_DM_SERIE;
            
     Max_SEQ_DM_SERIE := Max_SEQ_DM_SERIE +1;
            
     SET_SEQ('A0_SEQ_DM_SERIE',Max_SEQ_DM_SERIE);
     
  END;

  
  PROCEDURE A0_SEQ_DM_TIPUS_ACCIO IS   
        Max_SEQ_DM_TIPUS_ACCIO number;       
  BEGIN
  
     SELECT MAX(ID) INTO Max_SEQ_DM_TIPUS_ACCIO FROM A0_DM_TIPUS_ACCIO;
            
     Max_SEQ_DM_TIPUS_ACCIO := Max_SEQ_DM_TIPUS_ACCIO +1;
            
     SET_SEQ('A0_SEQ_DM_TIPUS_ACCIO',Max_SEQ_DM_TIPUS_ACCIO);
     
  END;
  

  PROCEDURE A0_SEQ_DM_TIPUS_ACTE IS   
        Max_SEQ_DM_TIPUS_ACTE number;       
  BEGIN
  
     SELECT MAX(ID) INTO Max_SEQ_DM_TIPUS_ACTE FROM A0_DM_TIPUS_ACTE;
            
     Max_SEQ_DM_TIPUS_ACTE := Max_SEQ_DM_TIPUS_ACTE +1;
            
     SET_SEQ('A0_SEQ_DM_TIPUS_ACTE',Max_SEQ_DM_TIPUS_ACTE);
     
  END;

  
  PROCEDURE A0_SEQ_DM_TIPUS_AGENDA IS   
        Max_SEQ_DM_TIPUS_AGENDA number;       
  BEGIN
  
     SELECT MAX(ID) INTO Max_SEQ_DM_TIPUS_AGENDA FROM A0_DM_TIPUS_AGENDA;
            
     Max_SEQ_DM_TIPUS_AGENDA := Max_SEQ_DM_TIPUS_AGENDA +1;
            
     SET_SEQ('A0_SEQ_DM_TIPUS_AGENDA',Max_SEQ_DM_TIPUS_AGENDA);
     
  END;
  

  PROCEDURE A0_SEQ_DM_TIPUS_DATA IS   
        Max_SEQ_DM_TIPUS_DATA number;       
  BEGIN
  
     SELECT MAX(ID) INTO Max_SEQ_DM_TIPUS_DATA FROM A0_DM_TIPUS_DATA;
            
     Max_SEQ_DM_TIPUS_DATA := Max_SEQ_DM_TIPUS_DATA +1;
            
     SET_SEQ('A0_SEQ_DM_TIPUS_DATA',Max_SEQ_DM_TIPUS_DATA);
     
  END;


  PROCEDURE A0_SEQ_DM_TIPUS_TEMA IS   
        Max_SEQ_DM_TIPUS_TEMA number;       
  BEGIN
  
     SELECT MAX(ID) INTO Max_SEQ_DM_TIPUS_TEMA FROM A0_DM_TIPUS_TEMA;
            
     Max_SEQ_DM_TIPUS_TEMA := Max_SEQ_DM_TIPUS_TEMA +1;
            
     SET_SEQ('A0_SEQ_DM_TIPUS_TEMA',Max_SEQ_DM_TIPUS_TEMA);
     
  END;
  
  PROCEDURE A0_SEQ_DM_TRACTAMENT AS
        Max_SEQ_DM_TRACTAMENT number;       
  BEGIN
    
     SELECT MAX(ID) INTO Max_SEQ_DM_TRACTAMENT FROM A0_DM_TRACTAMENT;
            
     Max_SEQ_DM_TRACTAMENT := Max_SEQ_DM_TRACTAMENT +1;
            
     SET_SEQ('A0_SEQ_DM_TRACTAMENT',Max_SEQ_DM_TRACTAMENT);    
  
  END;
  
  
    
  PROCEDURE A0_SEQ_DOSSIER IS   
        Max_SEQ_DOSSIER number;       
  BEGIN
  
     SELECT MAX(ID) INTO Max_SEQ_DOSSIER FROM A0_DOSSIER;
            
     Max_SEQ_DOSSIER := Max_SEQ_DOSSIER +1;
            
     SET_SEQ('A0_SEQ_DOSSIER',Max_SEQ_DOSSIER);
     
  END;
  
  
  
  PROCEDURE A0_SEQ_REGISTRE IS   
        Max_SEQ_REGISTRE number;       
  BEGIN
  
     SELECT MAX(ID) INTO Max_SEQ_REGISTRE FROM A0_REGISTRE;
            
     Max_SEQ_REGISTRE := Max_SEQ_REGISTRE +1;
            
     SET_SEQ('A0_SEQ_REGISTRE',Max_SEQ_REGISTRE);
     
  END;



  PROCEDURE A0_SEQ_SUBJECTE IS   
        Max_SEQ_SUBJECTE number;       
  BEGIN
  
     SELECT MAX(ID) INTO Max_SEQ_SUBJECTE FROM A0_SUBJECTE;
            
     Max_SEQ_SUBJECTE := Max_SEQ_SUBJECTE +1;
            
     SET_SEQ('A0_SEQ_SUBJECTE',Max_SEQ_SUBJECTE);
     
  END;



  PROCEDURE A0_SEQ_TITULAR_DINS IS   
        Max_SEQ_TITULAR_DINS number;       
  BEGIN
  
     SELECT MAX(ID) INTO Max_SEQ_TITULAR_DINS FROM A0_TITULAR_DINS;
            
     Max_SEQ_TITULAR_DINS := Max_SEQ_TITULAR_DINS +1;
            
     SET_SEQ('A0_SEQ_TITULAR_DINS',Max_SEQ_TITULAR_DINS);
     
  END;

END Z_Z99_SECUENCIAS;

/
