--------------------------------------------------------
--  DDL for Index A1_IX_UNIQUE
--------------------------------------------------------

  CREATE UNIQUE INDEX "SINTAGMA_U"."A1_IX_UNIQUE" ON "SINTAGMA_U"."A1_DM_PAS_ACCIO" ("CODI", "TIPUS_ACCIO_ID", "AMBIT_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "T_SINTAGMA" ;
