--------------------------------------------------------
--  DDL for Index ER_RELACIO_UNIQUE
--------------------------------------------------------

  CREATE UNIQUE INDEX "SINTAGMA_U"."ER_RELACIO_UNIQUE" ON "SINTAGMA_U"."ELEMENTS_RELACIONATS" ("ELEMENT_PRINCIPAL1_ID", "ELEMENT_PRINCIPAL2_ID", "DATA_ESBORRAT") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "T_SINTAGMA" ;
