--------------------------------------------------------
--  DDL for Index ES_ASPECTE_UNIQUE
--------------------------------------------------------

  CREATE UNIQUE INDEX "SINTAGMA_U"."ES_ASPECTE_UNIQUE" ON "SINTAGMA_U"."ELEMENT_SECUNDARI" ("ASPECTE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "T_SINTAGMA" ;
