--------------------------------------------------------
--  DDL for Index IX_UNIQUE
--------------------------------------------------------

  CREATE UNIQUE INDEX "SINTAGMA_U"."IX_UNIQUE" ON "SINTAGMA_U"."DM_PAS_ACCIO" ("DESCRIPCIO", "AMBIT_ID", "TIPUS_ACCIO_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "T_SINTAGMA" ;
