--------------------------------------------------------
--  Constraints for Table A0_ANNEX_REGISTRE
--------------------------------------------------------

  ALTER TABLE "SINTAGMA_U"."A0_ANNEX_REGISTRE" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "T_SINTAGMA"  ENABLE;
  ALTER TABLE "SINTAGMA_U"."A0_ANNEX_REGISTRE" MODIFY ("DOCUMENT_ID" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."A0_ANNEX_REGISTRE" MODIFY ("REGISTRE_ID" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."A0_ANNEX_REGISTRE" MODIFY ("ES_CARPETA_ALCALDE" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."A0_ANNEX_REGISTRE" MODIFY ("TITOL" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."A0_ANNEX_REGISTRE" MODIFY ("ID" NOT NULL ENABLE);
