--------------------------------------------------------
--  Constraints for Table A0_ACCIO
--------------------------------------------------------

  ALTER TABLE "SINTAGMA_U"."A0_ACCIO" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "T_SINTAGMA"  ENABLE;
  ALTER TABLE "SINTAGMA_U"."A0_ACCIO" MODIFY ("AMBIT_DESTI_ID" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."A0_ACCIO" MODIFY ("ASPECTE_ID" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."A0_ACCIO" MODIFY ("SUBTIPUS_ACCIO_ID" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."A0_ACCIO" MODIFY ("USUARI_CREACIO" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."A0_ACCIO" MODIFY ("DATA_CREACIO" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."A0_ACCIO" MODIFY ("NOM_USUARI_ACCIO" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."A0_ACCIO" MODIFY ("ID" NOT NULL ENABLE);
