--------------------------------------------------------
--  Constraints for Table A0_ASPECTE
--------------------------------------------------------

  ALTER TABLE "SINTAGMA_U"."A0_ASPECTE" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "T_SINTAGMA"  ENABLE;
  ALTER TABLE "SINTAGMA_U"."A0_ASPECTE" MODIFY ("AMBIT_ID" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."A0_ASPECTE" MODIFY ("TIPUS_TEMA_ID" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."A0_ASPECTE" MODIFY ("USUARI_CREACIO" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."A0_ASPECTE" MODIFY ("DATA_CREACIO" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."A0_ASPECTE" MODIFY ("USUARI_ASSENTAMENT" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."A0_ASPECTE" MODIFY ("DATA_ASSENTAMENT" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."A0_ASPECTE" MODIFY ("DESCRIPCIO" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."A0_ASPECTE" MODIFY ("ID" NOT NULL ENABLE);
