--------------------------------------------------------
--  Constraints for Table A0_COMENTARI
--------------------------------------------------------

  ALTER TABLE "SINTAGMA_U"."A0_COMENTARI" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "T_SINTAGMA"  ENABLE;
  ALTER TABLE "SINTAGMA_U"."A0_COMENTARI" MODIFY ("ASPECTE_ID" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."A0_COMENTARI" MODIFY ("USUARI_CREACIO" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."A0_COMENTARI" MODIFY ("DATA_CREACIO" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."A0_COMENTARI" MODIFY ("DATA_COMENTARI" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."A0_COMENTARI" MODIFY ("COMENTARI" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."A0_COMENTARI" MODIFY ("MATRICULA_USUARI" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."A0_COMENTARI" MODIFY ("NOM_USUARI" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."A0_COMENTARI" MODIFY ("ID" NOT NULL ENABLE);
