--------------------------------------------------------
--  Constraints for Table A0_COMENTARI_ACTE
--------------------------------------------------------

  ALTER TABLE "SINTAGMA_U"."A0_COMENTARI_ACTE" MODIFY ("USUARI_CREACIO" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."A0_COMENTARI_ACTE" MODIFY ("DATA_CREACIO" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."A0_COMENTARI_ACTE" MODIFY ("ACTE_ID" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."A0_COMENTARI_ACTE" MODIFY ("COMENTARI_ID" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."A0_COMENTARI_ACTE" MODIFY ("ID" NOT NULL ENABLE);
