--------------------------------------------------------
--  Constraints for Table A0_CONVIDAT_CORREU
--------------------------------------------------------

  ALTER TABLE "SINTAGMA_U"."A0_CONVIDAT_CORREU" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "T_SINTAGMA"  ENABLE;
  ALTER TABLE "SINTAGMA_U"."A0_CONVIDAT_CORREU" MODIFY ("CONVIDAT_ID" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."A0_CONVIDAT_CORREU" MODIFY ("USUARI_CREACIO" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."A0_CONVIDAT_CORREU" MODIFY ("DATA_CREACIO" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."A0_CONVIDAT_CORREU" MODIFY ("CORREU_ELECTRONIC" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."A0_CONVIDAT_CORREU" MODIFY ("ID" NOT NULL ENABLE);
