--------------------------------------------------------
--  Constraints for Table A0_CONVIDAT
--------------------------------------------------------

  ALTER TABLE "SINTAGMA_U"."A0_CONVIDAT" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "T_SINTAGMA"  ENABLE;
  ALTER TABLE "SINTAGMA_U"."A0_CONVIDAT" MODIFY ("ESTAT_CONFIRMACIO_ID" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."A0_CONVIDAT" MODIFY ("ACTE_ID" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."A0_CONVIDAT" MODIFY ("USUARI_CREACIO" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."A0_CONVIDAT" MODIFY ("DATA_CREACIO" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."A0_CONVIDAT" MODIFY ("NOM_CARRER" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."A0_CONVIDAT" MODIFY ("NOM" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."A0_CONVIDAT" MODIFY ("ID" NOT NULL ENABLE);
