--------------------------------------------------------
--  Constraints for Table A0_CONTACTE_CLASSIFICACIO
--------------------------------------------------------

  ALTER TABLE "SINTAGMA_U"."A0_CONTACTE_CLASSIFICACIO" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "T_SINTAGMA"  ENABLE;
  ALTER TABLE "SINTAGMA_U"."A0_CONTACTE_CLASSIFICACIO" MODIFY ("CONTACTE_ID" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."A0_CONTACTE_CLASSIFICACIO" MODIFY ("CLASSIFICACIO_ID" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."A0_CONTACTE_CLASSIFICACIO" MODIFY ("USUARI_CREACIO" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."A0_CONTACTE_CLASSIFICACIO" MODIFY ("DATA_CREACIO" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."A0_CONTACTE_CLASSIFICACIO" MODIFY ("PRELACIO" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."A0_CONTACTE_CLASSIFICACIO" MODIFY ("ID" NOT NULL ENABLE);
