--------------------------------------------------------
--  Constraints for Table A0_CONVIDAT_ZONA
--------------------------------------------------------

  ALTER TABLE "SINTAGMA_U"."A0_CONVIDAT_ZONA" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "T_SINTAGMA"  ENABLE;
  ALTER TABLE "SINTAGMA_U"."A0_CONVIDAT_ZONA" MODIFY ("CONVIDAT_ID" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."A0_CONVIDAT_ZONA" MODIFY ("ZONA_ID" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."A0_CONVIDAT_ZONA" MODIFY ("USUARI_CREACIO" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."A0_CONVIDAT_ZONA" MODIFY ("DATA_CREACIO" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."A0_CONVIDAT_ZONA" MODIFY ("ID" NOT NULL ENABLE);
