--------------------------------------------------------
--  Constraints for Table A0_DOSSIER
--------------------------------------------------------

  ALTER TABLE "SINTAGMA_U"."A0_DOSSIER" MODIFY ("NUMERO_REGISTRE" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."A0_DOSSIER" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "T_SINTAGMA"  ENABLE;
  ALTER TABLE "SINTAGMA_U"."A0_DOSSIER" MODIFY ("ASPECTE_ID" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."A0_DOSSIER" MODIFY ("PREFIX_ANY_ID" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."A0_DOSSIER" MODIFY ("ID" NOT NULL ENABLE);
