--------------------------------------------------------
--  Constraints for Table A0_DM_PREFIX_ANY
--------------------------------------------------------

  ALTER TABLE "SINTAGMA_U"."A0_DM_PREFIX_ANY" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "T_SINTAGMA"  ENABLE;
  ALTER TABLE "SINTAGMA_U"."A0_DM_PREFIX_ANY" MODIFY ("AMBIT_ID" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."A0_DM_PREFIX_ANY" MODIFY ("DATA_CREACIO" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."A0_DM_PREFIX_ANY" MODIFY ("CONTADOR" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."A0_DM_PREFIX_ANY" MODIFY ("DESCRIPCIO" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."A0_DM_PREFIX_ANY" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."A0_DM_PREFIX_ANY" ADD CONSTRAINT "A0_FKDM_PREFIX_ANY" UNIQUE ("DESCRIPCIO", "AMBIT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "T_SINTAGMA"  ENABLE;
