--------------------------------------------------------
--  Constraints for Table A0_DM_PLANTILLA_ESPAI
--------------------------------------------------------

  ALTER TABLE "SINTAGMA_U"."A0_DM_PLANTILLA_ESPAI" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "T_SINTAGMA"  ENABLE;
  ALTER TABLE "SINTAGMA_U"."A0_DM_PLANTILLA_ESPAI" MODIFY ("ESPAI_ID" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."A0_DM_PLANTILLA_ESPAI" MODIFY ("USUARI_CREACIO" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."A0_DM_PLANTILLA_ESPAI" MODIFY ("DATA_CREACIO" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."A0_DM_PLANTILLA_ESPAI" MODIFY ("DESCRIPCIO" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."A0_DM_PLANTILLA_ESPAI" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."A0_DM_PLANTILLA_ESPAI" ADD CONSTRAINT "A0_FKDM_PLANTILLA_ESPAI" UNIQUE ("DESCRIPCIO", "ESPAI_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "T_SINTAGMA"  ENABLE;
