--------------------------------------------------------
--  Constraints for Table A0_ESPAI_ACTE_CONFIG
--------------------------------------------------------

  ALTER TABLE "SINTAGMA_U"."A0_ESPAI_ACTE_CONFIG" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "T_SINTAGMA"  ENABLE;
  ALTER TABLE "SINTAGMA_U"."A0_ESPAI_ACTE_CONFIG" MODIFY ("ZONA_ID" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."A0_ESPAI_ACTE_CONFIG" MODIFY ("ESPAI_ACTE_ID" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."A0_ESPAI_ACTE_CONFIG" MODIFY ("USUARI_CREACIO" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."A0_ESPAI_ACTE_CONFIG" MODIFY ("DATA_CREACIO" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."A0_ESPAI_ACTE_CONFIG" MODIFY ("ES_HABILITAT" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."A0_ESPAI_ACTE_CONFIG" MODIFY ("COLUMNA" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."A0_ESPAI_ACTE_CONFIG" MODIFY ("FILA" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."A0_ESPAI_ACTE_CONFIG" MODIFY ("ID" NOT NULL ENABLE);
