--------------------------------------------------------
--  Constraints for Table A0_ENTRADA_AGENDA
--------------------------------------------------------

  ALTER TABLE "SINTAGMA_U"."A0_ENTRADA_AGENDA" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "T_SINTAGMA"  ENABLE;
  ALTER TABLE "SINTAGMA_U"."A0_ENTRADA_AGENDA" MODIFY ("BARRI_ID" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."A0_ENTRADA_AGENDA" MODIFY ("DISTRICTE_ID" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."A0_ENTRADA_AGENDA" MODIFY ("ELEMENT_PRINCIPAL_ID" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."A0_ENTRADA_AGENDA" MODIFY ("USUARI_CREACIO" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."A0_ENTRADA_AGENDA" MODIFY ("DATA_CREACIO" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."A0_ENTRADA_AGENDA" MODIFY ("DATA_FI_ACTE" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."A0_ENTRADA_AGENDA" MODIFY ("DATA_INICI_ACTE" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."A0_ENTRADA_AGENDA" MODIFY ("ID" NOT NULL ENABLE);
