--------------------------------------------------------
--  Constraints for Table A0_PLANTILLA_CONFIG_ESPAI
--------------------------------------------------------

  ALTER TABLE "SINTAGMA_U"."A0_PLANTILLA_CONFIG_ESPAI" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "T_SINTAGMA"  ENABLE;
  ALTER TABLE "SINTAGMA_U"."A0_PLANTILLA_CONFIG_ESPAI" MODIFY ("USUARI_CREACIO" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."A0_PLANTILLA_CONFIG_ESPAI" MODIFY ("DATA_CREACIO" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."A0_PLANTILLA_CONFIG_ESPAI" MODIFY ("PLANTILLA_ID" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."A0_PLANTILLA_CONFIG_ESPAI" MODIFY ("ES_HABILITAT" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."A0_PLANTILLA_CONFIG_ESPAI" MODIFY ("COLUMNA" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."A0_PLANTILLA_CONFIG_ESPAI" MODIFY ("FILA" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."A0_PLANTILLA_CONFIG_ESPAI" MODIFY ("ID" NOT NULL ENABLE);
