--------------------------------------------------------
--  Constraints for Table A0_RASTRE
--------------------------------------------------------

  ALTER TABLE "SINTAGMA_U"."A0_RASTRE" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "T_SINTAGMA"  ENABLE;
  ALTER TABLE "SINTAGMA_U"."A0_RASTRE" MODIFY ("USUARI_CREACIO" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."A0_RASTRE" MODIFY ("DATA_CREACIO" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."A0_RASTRE" MODIFY ("RESPONSABLE" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."A0_RASTRE" MODIFY ("DATA_INICI" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."A0_RASTRE" MODIFY ("ACCIO" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."A0_RASTRE" MODIFY ("TIPUS_ACCIO" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."A0_RASTRE" MODIFY ("ID" NOT NULL ENABLE);
