--------------------------------------------------------
--  Constraints for Table A0_TRANSICIO_TRAMITACIO
--------------------------------------------------------

  ALTER TABLE "SINTAGMA_U"."A0_TRANSICIO_TRAMITACIO" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "T_SINTAGMA"  ENABLE;
  ALTER TABLE "SINTAGMA_U"."A0_TRANSICIO_TRAMITACIO" MODIFY ("USUARI_CREACIO" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."A0_TRANSICIO_TRAMITACIO" MODIFY ("DATA_CREACIO" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."A0_TRANSICIO_TRAMITACIO" MODIFY ("ACCIO_DESTI_ID" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."A0_TRANSICIO_TRAMITACIO" MODIFY ("ACCIO_ORIGEN_ID" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."A0_TRANSICIO_TRAMITACIO" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."A0_TRANSICIO_TRAMITACIO" ADD CONSTRAINT "A0_FKTRANSICIO_TRAMITACIO" UNIQUE ("ACCIO_ORIGEN_ID", "ACCIO_DESTI_ID", "AMBIT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "T_SINTAGMA"  ENABLE;
