--------------------------------------------------------
--  Constraints for Table A0_TITULAR_FORA_TELEFON
--------------------------------------------------------

  ALTER TABLE "SINTAGMA_U"."A0_TITULAR_FORA_TELEFON" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "T_SINTAGMA"  ENABLE;
  ALTER TABLE "SINTAGMA_U"."A0_TITULAR_FORA_TELEFON" MODIFY ("TIPUS_TELEFON_ID" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."A0_TITULAR_FORA_TELEFON" MODIFY ("TITULAR_FORA_ID" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."A0_TITULAR_FORA_TELEFON" MODIFY ("USUARI_CREACIO" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."A0_TITULAR_FORA_TELEFON" MODIFY ("DATA_CREACIO" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."A0_TITULAR_FORA_TELEFON" MODIFY ("NUMERO" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."A0_TITULAR_FORA_TELEFON" MODIFY ("ID" NOT NULL ENABLE);
