--------------------------------------------------------
--  Constraints for Table A1_ANNEX_INCIDENT
--------------------------------------------------------

  ALTER TABLE "SINTAGMA_U"."A1_ANNEX_INCIDENT" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "T_SINTAGMA"  ENABLE;
  ALTER TABLE "SINTAGMA_U"."A1_ANNEX_INCIDENT" MODIFY ("USUARI_CREACIO" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."A1_ANNEX_INCIDENT" MODIFY ("DATA_CREACIO" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."A1_ANNEX_INCIDENT" MODIFY ("TIPUS_SUPORT_ID" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."A1_ANNEX_INCIDENT" MODIFY ("DOCUMENT_ID" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."A1_ANNEX_INCIDENT" MODIFY ("INCIDENT_ID" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."A1_ANNEX_INCIDENT" MODIFY ("TITOL" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."A1_ANNEX_INCIDENT" MODIFY ("ID" NOT NULL ENABLE);
