--------------------------------------------------------
--  Constraints for Table A1_ANNEX_ASPECTE
--------------------------------------------------------

  ALTER TABLE "SINTAGMA_U"."A1_ANNEX_ASPECTE" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "T_SINTAGMA"  ENABLE;
  ALTER TABLE "SINTAGMA_U"."A1_ANNEX_ASPECTE" MODIFY ("TIPUS_SUPORT_ID" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."A1_ANNEX_ASPECTE" MODIFY ("DOCUMENT_ID" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."A1_ANNEX_ASPECTE" MODIFY ("ASPECTE_ID" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."A1_ANNEX_ASPECTE" MODIFY ("ES_CARPETA_ALCALDE" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."A1_ANNEX_ASPECTE" MODIFY ("TITOL" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."A1_ANNEX_ASPECTE" MODIFY ("ID" NOT NULL ENABLE);
