--------------------------------------------------------
--  Constraints for Table A1_CLASSIFICACIO_ARXIU
--------------------------------------------------------

  ALTER TABLE "SINTAGMA_U"."A1_CLASSIFICACIO_ARXIU" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "T_SINTAGMA"  ENABLE;
  ALTER TABLE "SINTAGMA_U"."A1_CLASSIFICACIO_ARXIU" MODIFY ("USUARI_CREACIO" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."A1_CLASSIFICACIO_ARXIU" MODIFY ("DATA_CREACIO" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."A1_CLASSIFICACIO_ARXIU" MODIFY ("ID" NOT NULL ENABLE);
