--------------------------------------------------------
--  Constraints for Table A1_COMANDA
--------------------------------------------------------

  ALTER TABLE "SINTAGMA_U"."A1_COMANDA" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "T_SINTAGMA"  ENABLE;
  ALTER TABLE "SINTAGMA_U"."A1_COMANDA" MODIFY ("ESTAT_COMANDA_ID" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."A1_COMANDA" MODIFY ("ACTE_ID" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."A1_COMANDA" MODIFY ("TIPUS_SERVEI_ID" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."A1_COMANDA" MODIFY ("USUARI_CREACIO" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."A1_COMANDA" MODIFY ("DATA_CREACIO" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."A1_COMANDA" MODIFY ("COST_APROXIMAT" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."A1_COMANDA" MODIFY ("TITOL" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."A1_COMANDA" MODIFY ("DATA_PETICIO" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."A1_COMANDA" MODIFY ("ID" NOT NULL ENABLE);
