--------------------------------------------------------
--  Constraints for Table A1_CONTACTE
--------------------------------------------------------

  ALTER TABLE "SINTAGMA_U"."A1_CONTACTE" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "T_SINTAGMA"  ENABLE;
  ALTER TABLE "SINTAGMA_U"."A1_CONTACTE" MODIFY ("AMBIT_ID" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."A1_CONTACTE" MODIFY ("VISIBILITAT_ID" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."A1_CONTACTE" MODIFY ("ADRECA_ID" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."A1_CONTACTE" MODIFY ("SUBJECTE_ID" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."A1_CONTACTE" MODIFY ("TIPUS_CONTACTE_ID" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."A1_CONTACTE" MODIFY ("USUARI_CREACIO" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."A1_CONTACTE" MODIFY ("DATA_CREACIO" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."A1_CONTACTE" MODIFY ("ID" NOT NULL ENABLE);
