--------------------------------------------------------
--  Constraints for Table A1_CONVIDAT_ACOMPANYANT
--------------------------------------------------------

  ALTER TABLE "SINTAGMA_U"."A1_CONVIDAT_ACOMPANYANT" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "T_SINTAGMA"  ENABLE;
  ALTER TABLE "SINTAGMA_U"."A1_CONVIDAT_ACOMPANYANT" MODIFY ("CONVIDAT_ID" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."A1_CONVIDAT_ACOMPANYANT" MODIFY ("USUARI_CREACIO" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."A1_CONVIDAT_ACOMPANYANT" MODIFY ("DATA_CREACIO" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."A1_CONVIDAT_ACOMPANYANT" MODIFY ("NOM" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."A1_CONVIDAT_ACOMPANYANT" MODIFY ("ID" NOT NULL ENABLE);
