--------------------------------------------------------
--  Constraints for Table A1_DM_ESPAI
--------------------------------------------------------

  ALTER TABLE "SINTAGMA_U"."A1_DM_ESPAI" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "T_SINTAGMA"  ENABLE;
  ALTER TABLE "SINTAGMA_U"."A1_DM_ESPAI" MODIFY ("USUARI_CREACIO" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."A1_DM_ESPAI" MODIFY ("DATA_CREACIO" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."A1_DM_ESPAI" MODIFY ("NUMERO_COLUMNES" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."A1_DM_ESPAI" MODIFY ("NUMERO_FILES" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."A1_DM_ESPAI" MODIFY ("DESCRIPCIO" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."A1_DM_ESPAI" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."A1_DM_ESPAI" ADD CONSTRAINT "A1_FKDM_ESPAI" UNIQUE ("DESCRIPCIO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "T_SINTAGMA"  ENABLE;
