--------------------------------------------------------
--  Constraints for Table A1_ELEMENTS_RELACIONATS
--------------------------------------------------------

  ALTER TABLE "SINTAGMA_U"."A1_ELEMENTS_RELACIONATS" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "T_SINTAGMA"  ENABLE;
  ALTER TABLE "SINTAGMA_U"."A1_ELEMENTS_RELACIONATS" MODIFY ("ELEMENT_PRINCIPAL2" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."A1_ELEMENTS_RELACIONATS" MODIFY ("ELEMENT_PRINCIPAL1" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."A1_ELEMENTS_RELACIONATS" MODIFY ("ID" NOT NULL ENABLE);
