--------------------------------------------------------
--  Constraints for Table A1_MANTENIMENT_DM
--------------------------------------------------------

  ALTER TABLE "SINTAGMA_U"."A1_MANTENIMENT_DM" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "T_SINTAGMA"  ENABLE;
  ALTER TABLE "SINTAGMA_U"."A1_MANTENIMENT_DM" MODIFY ("AMBIT_ID" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."A1_MANTENIMENT_DM" MODIFY ("TABLE_NAME" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."A1_MANTENIMENT_DM" MODIFY ("ID" NOT NULL ENABLE);
