--------------------------------------------------------
--  Constraints for Table A1_TRUCADA_ELEMENT_PRINCIPAL
--------------------------------------------------------

  ALTER TABLE "SINTAGMA_U"."A1_TRUCADA_ELEMENT_PRINCIPAL" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "T_SINTAGMA"  ENABLE;
  ALTER TABLE "SINTAGMA_U"."A1_TRUCADA_ELEMENT_PRINCIPAL" MODIFY ("USUARI_CREACIO" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."A1_TRUCADA_ELEMENT_PRINCIPAL" MODIFY ("DATA_CREACIO" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."A1_TRUCADA_ELEMENT_PRINCIPAL" MODIFY ("ELEMENT_PRINCIPAL_ID" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."A1_TRUCADA_ELEMENT_PRINCIPAL" MODIFY ("TRUCADA_ID" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."A1_TRUCADA_ELEMENT_PRINCIPAL" MODIFY ("ID" NOT NULL ENABLE);
