--------------------------------------------------------
--  Constraints for Table A1_TITULAR_DINS
--------------------------------------------------------

  ALTER TABLE "SINTAGMA_U"."A1_TITULAR_DINS" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "T_SINTAGMA"  ENABLE;
  ALTER TABLE "SINTAGMA_U"."A1_TITULAR_DINS" MODIFY ("ASPECTE_ID" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."A1_TITULAR_DINS" MODIFY ("USUARI_CREACIO" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."A1_TITULAR_DINS" MODIFY ("DATA_CREACIO" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."A1_TITULAR_DINS" MODIFY ("MATRICULA_USUARI" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."A1_TITULAR_DINS" MODIFY ("NOM_USUARI" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."A1_TITULAR_DINS" MODIFY ("ID" NOT NULL ENABLE);
