--------------------------------------------------------
--  Constraints for Table ANNEX_ACTE
--------------------------------------------------------

  ALTER TABLE "SINTAGMA_U"."ANNEX_ACTE" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "T_SINTAGMA"  ENABLE;
  ALTER TABLE "SINTAGMA_U"."ANNEX_ACTE" MODIFY ("TIPUS_SUPORT_ID" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."ANNEX_ACTE" MODIFY ("DOCUMENT_ID" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."ANNEX_ACTE" MODIFY ("ACTE_ID" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."ANNEX_ACTE" MODIFY ("ID" NOT NULL ENABLE);
