--------------------------------------------------------
--  Constraints for Table ANNEX_REGISTRE
--------------------------------------------------------

  ALTER TABLE "SINTAGMA_U"."ANNEX_REGISTRE" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "T_SINTAGMA"  ENABLE;
  ALTER TABLE "SINTAGMA_U"."ANNEX_REGISTRE" MODIFY ("DOCUMENT_ID" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."ANNEX_REGISTRE" MODIFY ("REGISTRE_ID" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."ANNEX_REGISTRE" MODIFY ("ES_CARPETA_ALCALDE" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."ANNEX_REGISTRE" MODIFY ("TITOL" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."ANNEX_REGISTRE" MODIFY ("ID" NOT NULL ENABLE);
