--------------------------------------------------------
--  Constraints for Table ANNEX_ASPECTE
--------------------------------------------------------

  ALTER TABLE "SINTAGMA_U"."ANNEX_ASPECTE" MODIFY ("USUARI_CREACIO" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."ANNEX_ASPECTE" MODIFY ("DATA_CREACIO" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."ANNEX_ASPECTE" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "T_SINTAGMA"  ENABLE;
  ALTER TABLE "SINTAGMA_U"."ANNEX_ASPECTE" MODIFY ("TIPUS_SUPORT_ID" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."ANNEX_ASPECTE" MODIFY ("DOCUMENT_ID" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."ANNEX_ASPECTE" MODIFY ("ASPECTE_ID" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."ANNEX_ASPECTE" MODIFY ("ES_CARPETA_ALCALDE" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."ANNEX_ASPECTE" MODIFY ("TITOL" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."ANNEX_ASPECTE" MODIFY ("ID" NOT NULL ENABLE);
