--------------------------------------------------------
--  Constraints for Table AUX_ACCIONS
--------------------------------------------------------

  ALTER TABLE "SINTAGMA_U"."AUX_ACCIONS" MODIFY ("ESASSABENTAT" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."AUX_ACCIONS" MODIFY ("ESPERARESPOSTA" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."AUX_ACCIONS" MODIFY ("PRIORITATID" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."AUX_ACCIONS" MODIFY ("SUBTIPUSACCIOID" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."AUX_ACCIONS" MODIFY ("DATAINICI" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."AUX_ACCIONS" MODIFY ("ASPECTEID" NOT NULL ENABLE);
