--------------------------------------------------------
--  Constraints for Table BCK_SUBJECTE20180830
--------------------------------------------------------

  ALTER TABLE "SINTAGMA_U"."BCK_SUBJECTE20180830" MODIFY ("AMBIT_ID" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."BCK_SUBJECTE20180830" MODIFY ("TIPUS_SUBJECTE_ID" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."BCK_SUBJECTE20180830" MODIFY ("USUARI_CREACIO" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."BCK_SUBJECTE20180830" MODIFY ("DATA_CREACIO" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."BCK_SUBJECTE20180830" MODIFY ("NOM" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."BCK_SUBJECTE20180830" MODIFY ("ID" NOT NULL ENABLE);
