--------------------------------------------------------
--  Constraints for Table COMANDA
--------------------------------------------------------

  ALTER TABLE "SINTAGMA_U"."COMANDA" MODIFY ("CODI_CONTRACTE" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."COMANDA" MODIFY ("MATRICULA_TECNIC_RESPONSABLE" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."COMANDA" MODIFY ("NOM_TECNIC_RESPONSABLE" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."COMANDA" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "T_SINTAGMA"  ENABLE;
  ALTER TABLE "SINTAGMA_U"."COMANDA" MODIFY ("ESTAT_COMANDA_ID" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."COMANDA" MODIFY ("ACTE_ID" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."COMANDA" MODIFY ("TIPUS_SERVEI_ID" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."COMANDA" MODIFY ("USUARI_CREACIO" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."COMANDA" MODIFY ("DATA_CREACIO" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."COMANDA" MODIFY ("COST_APROXIMAT" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."COMANDA" MODIFY ("TITOL" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."COMANDA" MODIFY ("DATA_PETICIO" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."COMANDA" MODIFY ("ID" NOT NULL ENABLE);
