--------------------------------------------------------
--  Constraints for Table DADES_HISTORIC
--------------------------------------------------------

  ALTER TABLE "SINTAGMA_U"."DADES_HISTORIC" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "T_SINTAGMA"  ENABLE;
  ALTER TABLE "SINTAGMA_U"."DADES_HISTORIC" MODIFY ("CONTACTE_ID" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."DADES_HISTORIC" MODIFY ("DATA_CREACIO" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."DADES_HISTORIC" MODIFY ("USUARI_CREACIO" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."DADES_HISTORIC" MODIFY ("VALOR" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."DADES_HISTORIC" MODIFY ("CAMP" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."DADES_HISTORIC" MODIFY ("TAULA" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."DADES_HISTORIC" MODIFY ("ID" NOT NULL ENABLE);
