--------------------------------------------------------
--  Constraints for Table DOCUMENT_BAIXA_SUBJECTE
--------------------------------------------------------

  ALTER TABLE "SINTAGMA_U"."DOCUMENT_BAIXA_SUBJECTE" MODIFY ("USUARI_CREACIO" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."DOCUMENT_BAIXA_SUBJECTE" MODIFY ("DATA_CREACIO" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."DOCUMENT_BAIXA_SUBJECTE" MODIFY ("DOCUMENT_ID" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."DOCUMENT_BAIXA_SUBJECTE" MODIFY ("SUBJECTE_ID" NOT NULL ENABLE);
