--------------------------------------------------------
--  Constraints for Table ELEMENTS_RELACIONATS
--------------------------------------------------------

  ALTER TABLE "SINTAGMA_U"."ELEMENTS_RELACIONATS" MODIFY ("USUARI_CREACIO" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."ELEMENTS_RELACIONATS" MODIFY ("DATA_CREACIO" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."ELEMENTS_RELACIONATS" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "T_SINTAGMA"  ENABLE;
  ALTER TABLE "SINTAGMA_U"."ELEMENTS_RELACIONATS" MODIFY ("ELEMENT_PRINCIPAL2_ID" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."ELEMENTS_RELACIONATS" MODIFY ("ELEMENT_PRINCIPAL1_ID" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."ELEMENTS_RELACIONATS" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."ELEMENTS_RELACIONATS" ADD CONSTRAINT "ER_RELACIO_UNIQUE" UNIQUE ("ELEMENT_PRINCIPAL1_ID", "ELEMENT_PRINCIPAL2_ID", "DATA_ESBORRAT")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "T_SINTAGMA"  ENABLE;
