--------------------------------------------------------
--  Constraints for Table ENTRADA_AGENDA
--------------------------------------------------------

  ALTER TABLE "SINTAGMA_U"."ENTRADA_AGENDA" MODIFY ("ES_DECISIO" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."ENTRADA_AGENDA" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "T_SINTAGMA"  ENABLE;
  ALTER TABLE "SINTAGMA_U"."ENTRADA_AGENDA" MODIFY ("ELEMENT_PRINCIPAL_ID" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."ENTRADA_AGENDA" MODIFY ("USUARI_CREACIO" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."ENTRADA_AGENDA" MODIFY ("DATA_CREACIO" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."ENTRADA_AGENDA" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."ENTRADA_AGENDA" ADD CONSTRAINT "EA_EP_UNIQUE" UNIQUE ("ELEMENT_PRINCIPAL_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "T_SINTAGMA"  ENABLE;
