--------------------------------------------------------
--  Constraints for Table ERR_ENTITAT_DESCR_REPE
--------------------------------------------------------

  ALTER TABLE "SINTAGMA_U"."ERR_ENTITAT_DESCR_REPE" MODIFY ("USUARI_CREACIO" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."ERR_ENTITAT_DESCR_REPE" MODIFY ("DATA_CREACIO" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."ERR_ENTITAT_DESCR_REPE" MODIFY ("DESCRIPCIO" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."ERR_ENTITAT_DESCR_REPE" MODIFY ("ID" NOT NULL ENABLE);
