--------------------------------------------------------
--  Constraints for Table ERR_SUBJECTE_NOMS_REP
--------------------------------------------------------

  ALTER TABLE "SINTAGMA_U"."ERR_SUBJECTE_NOMS_REP" MODIFY ("AMBIT_ID" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."ERR_SUBJECTE_NOMS_REP" MODIFY ("TIPUS_SUBJECTE_ID" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."ERR_SUBJECTE_NOMS_REP" MODIFY ("USUARI_CREACIO" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."ERR_SUBJECTE_NOMS_REP" MODIFY ("DATA_CREACIO" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."ERR_SUBJECTE_NOMS_REP" MODIFY ("NOM" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."ERR_SUBJECTE_NOMS_REP" MODIFY ("ID" NOT NULL ENABLE);
