--------------------------------------------------------
--  Constraints for Table ERR_ABREUJADA_NULL
--------------------------------------------------------

  ALTER TABLE "SINTAGMA_U"."ERR_ABREUJADA_NULL" MODIFY ("USUARI_CREACIO" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."ERR_ABREUJADA_NULL" MODIFY ("DATA_CREACIO" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."ERR_ABREUJADA_NULL" MODIFY ("DESCRIPCIO" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."ERR_ABREUJADA_NULL" MODIFY ("ID" NOT NULL ENABLE);
