--------------------------------------------------------
--  Constraints for Table OBSEQUI_ENTREGAT
--------------------------------------------------------

  ALTER TABLE "SINTAGMA_U"."OBSEQUI_ENTREGAT" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "T_SINTAGMA"  ENABLE;
  ALTER TABLE "SINTAGMA_U"."OBSEQUI_ENTREGAT" MODIFY ("OBSEQUI_ID" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."OBSEQUI_ENTREGAT" MODIFY ("USUARI_CREACIO" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."OBSEQUI_ENTREGAT" MODIFY ("DATA_CREACIO" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."OBSEQUI_ENTREGAT" MODIFY ("DATA_ENTREGA" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."OBSEQUI_ENTREGAT" MODIFY ("NOM" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."OBSEQUI_ENTREGAT" MODIFY ("ID" NOT NULL ENABLE);
