--------------------------------------------------------
--  Constraints for Table OBSEQUI_INVENTARI
--------------------------------------------------------

  ALTER TABLE "SINTAGMA_U"."OBSEQUI_INVENTARI" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "T_SINTAGMA"  ENABLE;
  ALTER TABLE "SINTAGMA_U"."OBSEQUI_INVENTARI" MODIFY ("OBSEQUI_ID" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."OBSEQUI_INVENTARI" MODIFY ("USUARI_CREACIO" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."OBSEQUI_INVENTARI" MODIFY ("DATA_CREACIO" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."OBSEQUI_INVENTARI" MODIFY ("ID" NOT NULL ENABLE);
