--------------------------------------------------------
--  Constraints for Table TITULAR_DINS
--------------------------------------------------------

  ALTER TABLE "SINTAGMA_U"."TITULAR_DINS" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "T_SINTAGMA"  ENABLE;
  ALTER TABLE "SINTAGMA_U"."TITULAR_DINS" MODIFY ("ASPECTE_ID" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."TITULAR_DINS" MODIFY ("USUARI_CREACIO" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."TITULAR_DINS" MODIFY ("DATA_CREACIO" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."TITULAR_DINS" MODIFY ("MATRICULA_USUARI" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."TITULAR_DINS" MODIFY ("NOM_USUARI" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."TITULAR_DINS" MODIFY ("ID" NOT NULL ENABLE);
