--------------------------------------------------------
--  Constraints for Table Z_B99_CONTACTE_CLASSIFICACIO
--------------------------------------------------------

  ALTER TABLE "SINTAGMA_U"."Z_B99_CONTACTE_CLASSIFICACIO" MODIFY ("CONTACTE_ID" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."Z_B99_CONTACTE_CLASSIFICACIO" MODIFY ("CLASSIFICACIO_ID" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."Z_B99_CONTACTE_CLASSIFICACIO" MODIFY ("USUARI_CREACIO" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."Z_B99_CONTACTE_CLASSIFICACIO" MODIFY ("DATA_CREACIO" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."Z_B99_CONTACTE_CLASSIFICACIO" MODIFY ("PRELACIO" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."Z_B99_CONTACTE_CLASSIFICACIO" MODIFY ("ID" NOT NULL ENABLE);
