--------------------------------------------------------
--  Constraints for Table Z_B99_CONTACTE_TELEFON
--------------------------------------------------------

  ALTER TABLE "SINTAGMA_U"."Z_B99_CONTACTE_TELEFON" MODIFY ("TIPUS_TELEFON_ID" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."Z_B99_CONTACTE_TELEFON" MODIFY ("CONTACTE_ID" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."Z_B99_CONTACTE_TELEFON" MODIFY ("USUARI_CREACIO" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."Z_B99_CONTACTE_TELEFON" MODIFY ("DATA_CREACIO" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."Z_B99_CONTACTE_TELEFON" MODIFY ("NUMERO" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."Z_B99_CONTACTE_TELEFON" MODIFY ("ID" NOT NULL ENABLE);
