--------------------------------------------------------
--  Constraints for Table Z_B99_SUBJECTE
--------------------------------------------------------

  ALTER TABLE "SINTAGMA_U"."Z_B99_SUBJECTE" MODIFY ("AMBIT_ID" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."Z_B99_SUBJECTE" MODIFY ("TIPUS_SUBJECTE_ID" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."Z_B99_SUBJECTE" MODIFY ("USUARI_CREACIO" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."Z_B99_SUBJECTE" MODIFY ("DATA_CREACIO" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."Z_B99_SUBJECTE" MODIFY ("NOM" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."Z_B99_SUBJECTE" MODIFY ("ID" NOT NULL ENABLE);
