--------------------------------------------------------
--  Constraints for Table Z_B99_DM_TRACTAMENT
--------------------------------------------------------

  ALTER TABLE "SINTAGMA_U"."Z_B99_DM_TRACTAMENT" MODIFY ("USUARI_CREACIO" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."Z_B99_DM_TRACTAMENT" MODIFY ("DATA_CREACIO" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."Z_B99_DM_TRACTAMENT" MODIFY ("DESCRIPCIO" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."Z_B99_DM_TRACTAMENT" MODIFY ("ID" NOT NULL ENABLE);
