--------------------------------------------------------
--  Constraints for Table Z_B99_CONTACTE_CORREU
--------------------------------------------------------

  ALTER TABLE "SINTAGMA_U"."Z_B99_CONTACTE_CORREU" MODIFY ("CONTACTE_ID" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."Z_B99_CONTACTE_CORREU" MODIFY ("USUARI_CREACIO" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."Z_B99_CONTACTE_CORREU" MODIFY ("DATA_CREACIO" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."Z_B99_CONTACTE_CORREU" MODIFY ("CORREU_ELECTRONIC" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."Z_B99_CONTACTE_CORREU" MODIFY ("ID" NOT NULL ENABLE);
