--------------------------------------------------------
--  Constraints for Table Z_B99_ACOMPANYANT
--------------------------------------------------------

  ALTER TABLE "SINTAGMA_U"."Z_B99_ACOMPANYANT" MODIFY ("CONTACTE_ID" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."Z_B99_ACOMPANYANT" MODIFY ("USUARI_CREACIO" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."Z_B99_ACOMPANYANT" MODIFY ("DATA_CREACIO" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."Z_B99_ACOMPANYANT" MODIFY ("COGNOM1" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."Z_B99_ACOMPANYANT" MODIFY ("NOM" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."Z_B99_ACOMPANYANT" MODIFY ("ID" NOT NULL ENABLE);
