--------------------------------------------------------
--  Constraints for Table Z_B99_CONTACTE
--------------------------------------------------------

  ALTER TABLE "SINTAGMA_U"."Z_B99_CONTACTE" MODIFY ("AMBIT_ID" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."Z_B99_CONTACTE" MODIFY ("VISIBILITAT_ID" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."Z_B99_CONTACTE" MODIFY ("ADRECA_ID" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."Z_B99_CONTACTE" MODIFY ("SUBJECTE_ID" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."Z_B99_CONTACTE" MODIFY ("TIPUS_CONTACTE_ID" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."Z_B99_CONTACTE" MODIFY ("USUARI_CREACIO" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."Z_B99_CONTACTE" MODIFY ("DATA_CREACIO" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."Z_B99_CONTACTE" MODIFY ("ID" NOT NULL ENABLE);
