--------------------------------------------------------
--  Constraints for Table Z_B99_DM_ENTITAT
--------------------------------------------------------

  ALTER TABLE "SINTAGMA_U"."Z_B99_DM_ENTITAT" MODIFY ("USUARI_CREACIO" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."Z_B99_DM_ENTITAT" MODIFY ("DATA_CREACIO" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."Z_B99_DM_ENTITAT" MODIFY ("DESCRIPCIO" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."Z_B99_DM_ENTITAT" MODIFY ("CODI" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."Z_B99_DM_ENTITAT" MODIFY ("ID" NOT NULL ENABLE);
