--------------------------------------------------------
--  Constraints for Table Z_B99_DM_CLASSIFICACIO
--------------------------------------------------------

  ALTER TABLE "SINTAGMA_U"."Z_B99_DM_CLASSIFICACIO" MODIFY ("AMBIT_ID" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."Z_B99_DM_CLASSIFICACIO" MODIFY ("TIPOLOGIA_ID" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."Z_B99_DM_CLASSIFICACIO" MODIFY ("USUARI_CREACIO" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."Z_B99_DM_CLASSIFICACIO" MODIFY ("DATA_CREACIO" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."Z_B99_DM_CLASSIFICACIO" MODIFY ("PRELACIO" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."Z_B99_DM_CLASSIFICACIO" MODIFY ("CODI" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."Z_B99_DM_CLASSIFICACIO" MODIFY ("DESCRIPCIO" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."Z_B99_DM_CLASSIFICACIO" MODIFY ("ID" NOT NULL ENABLE);
