--------------------------------------------------------
--  Constraints for Table Z_D99_CONTACTES
--------------------------------------------------------

  ALTER TABLE "SINTAGMA_U"."Z_D99_CONTACTES" MODIFY ("AMBIT_ID" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."Z_D99_CONTACTES" MODIFY ("VISIBILITAT_ID" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."Z_D99_CONTACTES" MODIFY ("ADRECA_ID" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."Z_D99_CONTACTES" MODIFY ("SUBJECTE_ID" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."Z_D99_CONTACTES" MODIFY ("TIPUS_CONTACTE_ID" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."Z_D99_CONTACTES" MODIFY ("USUARI_CREACIO" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."Z_D99_CONTACTES" MODIFY ("DATA_CREACIO" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."Z_D99_CONTACTES" MODIFY ("ID" NOT NULL ENABLE);
