--------------------------------------------------------
--  Constraints for Table Z_E002_INSTALACIO_AMBIT_PART
--------------------------------------------------------

  ALTER TABLE "SINTAGMA_U"."Z_E002_INSTALACIO_AMBIT_PART" MODIFY ("DATACREACIO" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."Z_E002_INSTALACIO_AMBIT_PART" MODIFY ("NOM" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."Z_E002_INSTALACIO_AMBIT_PART" MODIFY ("INSTALACIOID" NOT NULL ENABLE);
