--------------------------------------------------------
--  Constraints for Table Z_E164_ACCIONS_PART4
--------------------------------------------------------

  ALTER TABLE "SINTAGMA_U"."Z_E164_ACCIONS_PART4" MODIFY ("AMBIT_ORIGEN_ID" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."Z_E164_ACCIONS_PART4" MODIFY ("ASPECTE_ID" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."Z_E164_ACCIONS_PART4" MODIFY ("SUBTIPUS_ACCIO_ID" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."Z_E164_ACCIONS_PART4" MODIFY ("DATA_CREACIO" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."Z_E164_ACCIONS_PART4" MODIFY ("ES_NECESSITA_RESPOSTA" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."Z_E164_ACCIONS_PART4" MODIFY ("ACCION_ID" NOT NULL ENABLE);
