--------------------------------------------------------
--  Constraints for Table Z_E999_DM_ORIGEN_ELEMENT
--------------------------------------------------------

  ALTER TABLE "SINTAGMA_U"."Z_E999_DM_ORIGEN_ELEMENT" MODIFY ("AMBIT_ID" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."Z_E999_DM_ORIGEN_ELEMENT" MODIFY ("USUARI_CREACIO" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."Z_E999_DM_ORIGEN_ELEMENT" MODIFY ("DATA_CREACIO" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."Z_E999_DM_ORIGEN_ELEMENT" MODIFY ("DESCRIPCIO" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."Z_E999_DM_ORIGEN_ELEMENT" MODIFY ("ID" NOT NULL ENABLE);
