--------------------------------------------------------
--  Constraints for Table Z_E999_DM_TIPUS_ARG
--------------------------------------------------------

  ALTER TABLE "SINTAGMA_U"."Z_E999_DM_TIPUS_ARG" MODIFY ("AMBIT_ID" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."Z_E999_DM_TIPUS_ARG" MODIFY ("USUARI_CREACIO" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."Z_E999_DM_TIPUS_ARG" MODIFY ("DATA_CREACIO" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."Z_E999_DM_TIPUS_ARG" MODIFY ("DESCRIPCIO" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."Z_E999_DM_TIPUS_ARG" MODIFY ("ID" NOT NULL ENABLE);
