--------------------------------------------------------
--  Constraints for Table Z_G001_YA_EXISTS_CLASIFFICACIO
--------------------------------------------------------

  ALTER TABLE "SINTAGMA_U"."Z_G001_YA_EXISTS_CLASIFFICACIO" MODIFY ("DM_DESCRIPCIO" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."Z_G001_YA_EXISTS_CLASIFFICACIO" MODIFY ("DM_CODI" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."Z_G001_YA_EXISTS_CLASIFFICACIO" MODIFY ("ID_SIAP" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."Z_G001_YA_EXISTS_CLASIFFICACIO" MODIFY ("ID_SINTAGMA" NOT NULL ENABLE);
