--------------------------------------------------------
--  Constraints for Table Z_G117_CONVIDAT_PASO3
--------------------------------------------------------

  ALTER TABLE "SINTAGMA_U"."Z_G117_CONVIDAT_PASO3" MODIFY ("ESTAT_CONFIRMACIO_ID" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."Z_G117_CONVIDAT_PASO3" MODIFY ("ACTE_ID" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."Z_G117_CONVIDAT_PASO3" MODIFY ("USUARI_CREACIO" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."Z_G117_CONVIDAT_PASO3" MODIFY ("DATA_CREACIO" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."Z_G117_CONVIDAT_PASO3" MODIFY ("NOM_CARRER" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."Z_G117_CONVIDAT_PASO3" MODIFY ("NOM" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."Z_G117_CONVIDAT_PASO3" MODIFY ("ID" NOT NULL ENABLE);
