--------------------------------------------------------
--  Constraints for Table Z_G118_CONVIDAT_FINAL
--------------------------------------------------------

  ALTER TABLE "SINTAGMA_U"."Z_G118_CONVIDAT_FINAL" MODIFY ("ESTAT_CONFIRMACIO_ID" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."Z_G118_CONVIDAT_FINAL" MODIFY ("ACTE_ID" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."Z_G118_CONVIDAT_FINAL" MODIFY ("USUARI_CREACIO" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."Z_G118_CONVIDAT_FINAL" MODIFY ("DATA_CREACIO" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."Z_G118_CONVIDAT_FINAL" MODIFY ("NOM_CARRER" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."Z_G118_CONVIDAT_FINAL" MODIFY ("NOM" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."Z_G118_CONVIDAT_FINAL" MODIFY ("ID" NOT NULL ENABLE);
