--------------------------------------------------------
--  Constraints for Table Z_SB130_CLASSIF_CONTACTE
--------------------------------------------------------

  ALTER TABLE "SINTAGMA_U"."Z_SB130_CLASSIF_CONTACTE" MODIFY ("ID_ORIGINAL" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."Z_SB130_CLASSIF_CONTACTE" MODIFY ("ID_CLASSIFICACIO" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."Z_SB130_CLASSIF_CONTACTE" MODIFY ("CLASSIFICACIO_CODI" NOT NULL ENABLE);
