--------------------------------------------------------
--  Constraints for Table Z_SB140_ACOMPANYANTS_VIPS
--------------------------------------------------------

  ALTER TABLE "SINTAGMA_U"."Z_SB140_ACOMPANYANTS_VIPS" MODIFY ("ID_ORIGINAL" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."Z_SB140_ACOMPANYANTS_VIPS" MODIFY ("CONTACTE_ID" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."Z_SB140_ACOMPANYANTS_VIPS" MODIFY ("SUBJECTE_ID" NOT NULL ENABLE);
