--------------------------------------------------------
--  Constraints for Table Z_SD000_CONTACTES
--------------------------------------------------------

  ALTER TABLE "SINTAGMA_U"."Z_SD000_CONTACTES" MODIFY ("INSTALACIOID" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."Z_SD000_CONTACTES" MODIFY ("PERTANYREPOSITORI" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."Z_SD000_CONTACTES" MODIFY ("COGNOMS" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."Z_SD000_CONTACTES" MODIFY ("NOM" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."Z_SD000_CONTACTES" MODIFY ("CONTACTEID" NOT NULL ENABLE);
