--------------------------------------------------------
--  Constraints for Table Z_SD010_ENTITAT_EXISTENTE
--------------------------------------------------------

  ALTER TABLE "SINTAGMA_U"."Z_SD010_ENTITAT_EXISTENTE" MODIFY ("DESCRIPCIO_ENTITAT" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."Z_SD010_ENTITAT_EXISTENTE" MODIFY ("ENTITAT_ID" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."Z_SD010_ENTITAT_EXISTENTE" MODIFY ("CONTACTE_ID" NOT NULL ENABLE);
