--------------------------------------------------------
--  Constraints for Table Z_SE002_INSTALACIO_AMBIT_PART
--------------------------------------------------------

  ALTER TABLE "SINTAGMA_U"."Z_SE002_INSTALACIO_AMBIT_PART" MODIFY ("DATACREACIO" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."Z_SE002_INSTALACIO_AMBIT_PART" MODIFY ("NOM" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."Z_SE002_INSTALACIO_AMBIT_PART" MODIFY ("INSTALACIOID" NOT NULL ENABLE);
