--------------------------------------------------------
--  Constraints for Table Z_SE160_ACCION_ELEMENTS_PPAL
--------------------------------------------------------

  ALTER TABLE "SINTAGMA_U"."Z_SE160_ACCION_ELEMENTS_PPAL" MODIFY ("TIPUS" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."Z_SE160_ACCION_ELEMENTS_PPAL" MODIFY ("ACCIONID" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."Z_SE160_ACCION_ELEMENTS_PPAL" MODIFY ("ELEMENT_PRINCIPAL_ID" NOT NULL ENABLE);
