--------------------------------------------------------
--  Constraints for Table Z_SE999_DM_TIPUS_AGENDA
--------------------------------------------------------

  ALTER TABLE "SINTAGMA_U"."Z_SE999_DM_TIPUS_AGENDA" MODIFY ("AMBIT_ID" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."Z_SE999_DM_TIPUS_AGENDA" MODIFY ("USUARI_CREACIO" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."Z_SE999_DM_TIPUS_AGENDA" MODIFY ("DATA_CREACIO" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."Z_SE999_DM_TIPUS_AGENDA" MODIFY ("DESCRIPCIO" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."Z_SE999_DM_TIPUS_AGENDA" MODIFY ("ID" NOT NULL ENABLE);
