--------------------------------------------------------
--  Constraints for Table Z_SE151_RELAC_ELEMENT_PPAL_SEC
--------------------------------------------------------

  ALTER TABLE "SINTAGMA_U"."Z_SE151_RELAC_ELEMENT_PPAL_SEC" MODIFY ("INSTALACIOID" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."Z_SE151_RELAC_ELEMENT_PPAL_SEC" MODIFY ("ID_ORIGINAL" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."Z_SE151_RELAC_ELEMENT_PPAL_SEC" MODIFY ("ELEMENT_PPAL_ID" NOT NULL ENABLE);
