--------------------------------------------------------
--  Constraints for Table Z_SE140_ELEMENT_PRINCIPAL
--------------------------------------------------------

  ALTER TABLE "SINTAGMA_U"."Z_SE140_ELEMENT_PRINCIPAL" MODIFY ("INSTALACIOID" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."Z_SE140_ELEMENT_PRINCIPAL" MODIFY ("ID_ORIGINAL" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."Z_SE140_ELEMENT_PRINCIPAL" MODIFY ("ASPECTE_ID" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."Z_SE140_ELEMENT_PRINCIPAL" MODIFY ("ID" NOT NULL ENABLE);
