--------------------------------------------------------
--  Constraints for Table Z_SE161_ACCIONS_PART1
--------------------------------------------------------

  ALTER TABLE "SINTAGMA_U"."Z_SE161_ACCIONS_PART1" MODIFY ("AMBIT_ORIGEN_ID" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."Z_SE161_ACCIONS_PART1" MODIFY ("ASPECTE_ID" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."Z_SE161_ACCIONS_PART1" MODIFY ("SUBTIPUS_ACCIO_ID" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."Z_SE161_ACCIONS_PART1" MODIFY ("DATA_CREACIO" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."Z_SE161_ACCIONS_PART1" MODIFY ("ESPERARESPOSTA" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."Z_SE161_ACCIONS_PART1" MODIFY ("ACCION_ID" NOT NULL ENABLE);
