--------------------------------------------------------
--  Constraints for Table Z_SE163_ACCIONS_PART3
--------------------------------------------------------

  ALTER TABLE "SINTAGMA_U"."Z_SE163_ACCIONS_PART3" MODIFY ("AMBIT_ORIGEN_ID" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."Z_SE163_ACCIONS_PART3" MODIFY ("ASPECTE_ID" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."Z_SE163_ACCIONS_PART3" MODIFY ("SUBTIPUS_ACCIO_ID" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."Z_SE163_ACCIONS_PART3" MODIFY ("DATA_CREACIO" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."Z_SE163_ACCIONS_PART3" MODIFY ("ES_NECESSITA_RESPOSTA" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."Z_SE163_ACCIONS_PART3" MODIFY ("ACCION_ID" NOT NULL ENABLE);
