--------------------------------------------------------
--  Constraints for Table Z_SE999_DM_SUBTIPUS_ACCIO
--------------------------------------------------------

  ALTER TABLE "SINTAGMA_U"."Z_SE999_DM_SUBTIPUS_ACCIO" MODIFY ("TIPUS_ACCIO_ID" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."Z_SE999_DM_SUBTIPUS_ACCIO" MODIFY ("DESCRIPCIO" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."Z_SE999_DM_SUBTIPUS_ACCIO" MODIFY ("ID" NOT NULL ENABLE);
