--------------------------------------------------------
--  Constraints for Table Z_SE999_DM_TIPUS_DATA
--------------------------------------------------------

  ALTER TABLE "SINTAGMA_U"."Z_SE999_DM_TIPUS_DATA" MODIFY ("AMBIT_ID" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."Z_SE999_DM_TIPUS_DATA" MODIFY ("USUARI_CREACIO" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."Z_SE999_DM_TIPUS_DATA" MODIFY ("DATA_CREACIO" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."Z_SE999_DM_TIPUS_DATA" MODIFY ("DESCRIPCIO" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."Z_SE999_DM_TIPUS_DATA" MODIFY ("ID" NOT NULL ENABLE);
