--------------------------------------------------------
--  Constraints for Table Z_SG115_CONVIDAT_PASO1
--------------------------------------------------------

  ALTER TABLE "SINTAGMA_U"."Z_SG115_CONVIDAT_PASO1" MODIFY ("ESTAT_CONFIRMACIO_ID" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."Z_SG115_CONVIDAT_PASO1" MODIFY ("ACTE_ID" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."Z_SG115_CONVIDAT_PASO1" MODIFY ("USUARI_CREACIO" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."Z_SG115_CONVIDAT_PASO1" MODIFY ("DATA_CREACIO" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."Z_SG115_CONVIDAT_PASO1" MODIFY ("NOM_CARRER" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."Z_SG115_CONVIDAT_PASO1" MODIFY ("NOM" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."Z_SG115_CONVIDAT_PASO1" MODIFY ("ID" NOT NULL ENABLE);
