--------------------------------------------------------
--  Constraints for Table Z_SG001_YA_EXISTS_CLASIFFICAC
--------------------------------------------------------

  ALTER TABLE "SINTAGMA_U"."Z_SG001_YA_EXISTS_CLASIFFICAC" MODIFY ("DM_DESCRIPCIO" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."Z_SG001_YA_EXISTS_CLASIFFICAC" MODIFY ("DM_CODI" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."Z_SG001_YA_EXISTS_CLASIFFICAC" MODIFY ("ID_SIAP" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."Z_SG001_YA_EXISTS_CLASIFFICAC" MODIFY ("ID_SINTAGMA" NOT NULL ENABLE);
