--------------------------------------------------------
--  Constraints for Table Z_SG022_TIPUS_ACTE_SIAP_VIPS
--------------------------------------------------------

  ALTER TABLE "SINTAGMA_U"."Z_SG022_TIPUS_ACTE_SIAP_VIPS" MODIFY ("DESCRIPCIO" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."Z_SG022_TIPUS_ACTE_SIAP_VIPS" MODIFY ("CODI" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."Z_SG022_TIPUS_ACTE_SIAP_VIPS" MODIFY ("ID" NOT NULL ENABLE);
