--------------------------------------------------------
--  Constraints for Table Z_T_RP_SUBTIPUSACCIO
--------------------------------------------------------

  ALTER TABLE "SINTAGMA_U"."Z_T_RP_SUBTIPUSACCIO" MODIFY ("ESVALORDEFECTE" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."Z_T_RP_SUBTIPUSACCIO" MODIFY ("TIPUSACCIOID" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."Z_T_RP_SUBTIPUSACCIO" MODIFY ("NOM" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."Z_T_RP_SUBTIPUSACCIO" MODIFY ("SUBTIPUSACCIOID" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."Z_T_RP_SUBTIPUSACCIO" MODIFY ("INSTALACIOID" NOT NULL ENABLE);
