--------------------------------------------------------
--  Constraints for Table Z_T_RP_NUMEROSREGISTREPREFIX
--------------------------------------------------------

  ALTER TABLE "SINTAGMA_U"."Z_T_RP_NUMEROSREGISTREPREFIX" MODIFY ("ESVALORDEFECTE" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."Z_T_RP_NUMEROSREGISTREPREFIX" MODIFY ("PREFIX" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."Z_T_RP_NUMEROSREGISTREPREFIX" MODIFY ("INSTALACIOID" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."Z_T_RP_NUMEROSREGISTREPREFIX" MODIFY ("NUMEROREGISTREPREFIXID" NOT NULL ENABLE);
