--------------------------------------------------------
--  Constraints for Table Z_T_RP_PLANTILLES
--------------------------------------------------------

  ALTER TABLE "SINTAGMA_U"."Z_T_RP_PLANTILLES" MODIFY ("TIPUSPLANTILLAID" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."Z_T_RP_PLANTILLES" MODIFY ("ESARXIVABLE" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."Z_T_RP_PLANTILLES" MODIFY ("ESEDITABLE" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."Z_T_RP_PLANTILLES" MODIFY ("NUMCOPIES" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."Z_T_RP_PLANTILLES" MODIFY ("NOMFITXER" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."Z_T_RP_PLANTILLES" MODIFY ("DESCRIPCIO" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."Z_T_RP_PLANTILLES" MODIFY ("INSTALACIOID" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."Z_T_RP_PLANTILLES" MODIFY ("PLANTILLAID" NOT NULL ENABLE);
