--------------------------------------------------------
--  Constraints for Table Z_T_RP_ELEMENTSPRINCIPALGEO
--------------------------------------------------------

  ALTER TABLE "SINTAGMA_U"."Z_T_RP_ELEMENTSPRINCIPALGEO" MODIFY ("TIPUS" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."Z_T_RP_ELEMENTSPRINCIPALGEO" MODIFY ("ASPECTEID" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."Z_T_RP_ELEMENTSPRINCIPALGEO" MODIFY ("ELEMENTPRINCIPALGEOID" NOT NULL ENABLE);
