--------------------------------------------------------
--  Constraints for Table Z_T_RP_CAMPSESPECIALS_TAULA3
--------------------------------------------------------

  ALTER TABLE "SINTAGMA_U"."Z_T_RP_CAMPSESPECIALS_TAULA3" MODIFY ("ESVALORDEFECTE" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."Z_T_RP_CAMPSESPECIALS_TAULA3" MODIFY ("INSTALACIOID" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."Z_T_RP_CAMPSESPECIALS_TAULA3" MODIFY ("NOM" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."Z_T_RP_CAMPSESPECIALS_TAULA3" MODIFY ("TAULA3ID" NOT NULL ENABLE);
