--------------------------------------------------------
--  Constraints for Table Z_T_RP_ELEMENTS_X
--------------------------------------------------------

  ALTER TABLE "SINTAGMA_U"."Z_T_RP_ELEMENTS_X" MODIFY ("TIPUS" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."Z_T_RP_ELEMENTS_X" MODIFY ("ESTAACTIU" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."Z_T_RP_ELEMENTS_X" MODIFY ("DATAASSENTAMENT" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."Z_T_RP_ELEMENTS_X" MODIFY ("ESENTRADA" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."Z_T_RP_ELEMENTS_X" MODIFY ("ACCIOID" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."Z_T_RP_ELEMENTS_X" MODIFY ("ASPECTEID" NOT NULL ENABLE);
