--------------------------------------------------------
--  Constraints for Table Z_T_SIAP_COSTOS_MOVIMENTS
--------------------------------------------------------

  ALTER TABLE "SINTAGMA_U"."Z_T_SIAP_COSTOS_MOVIMENTS" MODIFY ("SENTIT" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."Z_T_SIAP_COSTOS_MOVIMENTS" MODIFY ("REGULARITZAT" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."Z_T_SIAP_COSTOS_MOVIMENTS" MODIFY ("ENTITAT" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."Z_T_SIAP_COSTOS_MOVIMENTS" MODIFY ("JUSTIFICAT" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."Z_T_SIAP_COSTOS_MOVIMENTS" MODIFY ("IMPORT" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."Z_T_SIAP_COSTOS_MOVIMENTS" MODIFY ("CONCEPTE" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."Z_T_SIAP_COSTOS_MOVIMENTS" MODIFY ("CODITIPUS" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."Z_T_SIAP_COSTOS_MOVIMENTS" MODIFY ("DATA" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."Z_T_SIAP_COSTOS_MOVIMENTS" MODIFY ("ID" NOT NULL ENABLE);
