--------------------------------------------------------
--  Constraints for Table Z_T_RP_CAMPSESPECIALS_TAULA2
--------------------------------------------------------

  ALTER TABLE "SINTAGMA_U"."Z_T_RP_CAMPSESPECIALS_TAULA2" MODIFY ("ESVALORDEFECTE" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."Z_T_RP_CAMPSESPECIALS_TAULA2" MODIFY ("INSTALACIOID" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."Z_T_RP_CAMPSESPECIALS_TAULA2" MODIFY ("NOM" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."Z_T_RP_CAMPSESPECIALS_TAULA2" MODIFY ("ID" NOT NULL ENABLE);
