--------------------------------------------------------
--  Constraints for Table Z_T_RP_ENVIAMENTSANNEXOS
--------------------------------------------------------

  ALTER TABLE "SINTAGMA_U"."Z_T_RP_ENVIAMENTSANNEXOS" MODIFY ("ADRECACORREUID" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."Z_T_RP_ENVIAMENTSANNEXOS" MODIFY ("ANNEXID" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."Z_T_RP_ENVIAMENTSANNEXOS" MODIFY ("DATA" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."Z_T_RP_ENVIAMENTSANNEXOS" MODIFY ("ENVIAMENTANNEXOSID" NOT NULL ENABLE);
