--------------------------------------------------------
--  Constraints for Table Z_T_RP_NAVEGACIONS
--------------------------------------------------------

  ALTER TABLE "SINTAGMA_U"."Z_T_RP_NAVEGACIONS" MODIFY ("CALTANCAR" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."Z_T_RP_NAVEGACIONS" MODIFY ("ESPASSENPARAMS" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."Z_T_RP_NAVEGACIONS" MODIFY ("MODEOBERTURA" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."Z_T_RP_NAVEGACIONS" MODIFY ("CODIPANTALLADESTI" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."Z_T_RP_NAVEGACIONS" MODIFY ("ACCIOSORTIDA" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."Z_T_RP_NAVEGACIONS" MODIFY ("CODIPANTALLAORIGEN" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."Z_T_RP_NAVEGACIONS" MODIFY ("NAVEGACIOID" NOT NULL ENABLE);
