--------------------------------------------------------
--  Constraints for Table Z_T_RP_CAMPSESPECIALS_TAULA1
--------------------------------------------------------

  ALTER TABLE "SINTAGMA_U"."Z_T_RP_CAMPSESPECIALS_TAULA1" MODIFY ("ESVALORDEFECTE" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."Z_T_RP_CAMPSESPECIALS_TAULA1" MODIFY ("INSTALACIOID" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."Z_T_RP_CAMPSESPECIALS_TAULA1" MODIFY ("NOM" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."Z_T_RP_CAMPSESPECIALS_TAULA1" MODIFY ("ID" NOT NULL ENABLE);
