--------------------------------------------------------
--  Constraints for Table Z_T_RP_ASSIGNACIONSPERDEFECTE
--------------------------------------------------------

  ALTER TABLE "SINTAGMA_U"."Z_T_RP_ASSIGNACIONSPERDEFECTE" MODIFY ("INSTALACIOID" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."Z_T_RP_ASSIGNACIONSPERDEFECTE" MODIFY ("SUBTIPUSACCIOORIGENID" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."Z_T_RP_ASSIGNACIONSPERDEFECTE" MODIFY ("ASSIGNACIOPERDEFECTEID" NOT NULL ENABLE);
