--------------------------------------------------------
--  Constraints for Table Z_T_RP_USUARISACCIONSDEFECTE
--------------------------------------------------------

  ALTER TABLE "SINTAGMA_U"."Z_T_RP_USUARISACCIONSDEFECTE" MODIFY ("INSTALACIOID" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."Z_T_RP_USUARISACCIONSDEFECTE" MODIFY ("USUARIID" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."Z_T_RP_USUARISACCIONSDEFECTE" MODIFY ("TIPUSACCIOID" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."Z_T_RP_USUARISACCIONSDEFECTE" MODIFY ("USUARIACCIODEFECTEID" NOT NULL ENABLE);
