--------------------------------------------------------
--  Constraints for Table Z_T_RP_DELEGACIO
--------------------------------------------------------

  ALTER TABLE "SINTAGMA_U"."Z_T_RP_DELEGACIO" MODIFY ("ESVALORDEFECTE" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."Z_T_RP_DELEGACIO" MODIFY ("INSTALACIOID" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."Z_T_RP_DELEGACIO" MODIFY ("NOM" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."Z_T_RP_DELEGACIO" MODIFY ("DELEGACIOID" NOT NULL ENABLE);
