--------------------------------------------------------
--  Constraints for Table Z_T_RP_ANNEXOS
--------------------------------------------------------

  ALTER TABLE "SINTAGMA_U"."Z_T_RP_ANNEXOS" MODIFY ("ASPECTEID" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."Z_T_RP_ANNEXOS" MODIFY ("ESPRIVAT" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."Z_T_RP_ANNEXOS" MODIFY ("ESGENERAT" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."Z_T_RP_ANNEXOS" MODIFY ("DATACREACIO" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."Z_T_RP_ANNEXOS" MODIFY ("USUARIID" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."Z_T_RP_ANNEXOS" MODIFY ("ESPREFERENT" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."Z_T_RP_ANNEXOS" MODIFY ("NOMFITXER" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."Z_T_RP_ANNEXOS" MODIFY ("TIPUSANNEXID" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."Z_T_RP_ANNEXOS" MODIFY ("ANNEXID" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."Z_T_RP_ANNEXOS" MODIFY ("INSTALACIOID" NOT NULL ENABLE);
