--------------------------------------------------------
--  Constraints for Table Z_T_RP_CAMPSESPECIALS_TAULA4
--------------------------------------------------------

  ALTER TABLE "SINTAGMA_U"."Z_T_RP_CAMPSESPECIALS_TAULA4" MODIFY ("ESVALORDEFECTE" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."Z_T_RP_CAMPSESPECIALS_TAULA4" MODIFY ("TAULA3ID" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."Z_T_RP_CAMPSESPECIALS_TAULA4" MODIFY ("INSTALACIOID" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."Z_T_RP_CAMPSESPECIALS_TAULA4" MODIFY ("NOM" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."Z_T_RP_CAMPSESPECIALS_TAULA4" MODIFY ("TAULA4ID" NOT NULL ENABLE);
