--------------------------------------------------------
--  Constraints for Table Z_T_RP_ALERTES
--------------------------------------------------------

  ALTER TABLE "SINTAGMA_U"."Z_T_RP_ALERTES" MODIFY ("INSTALACIOID" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."Z_T_RP_ALERTES" MODIFY ("PROXIMITATDIES" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."Z_T_RP_ALERTES" MODIFY ("COLOR" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."Z_T_RP_ALERTES" MODIFY ("NOM" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."Z_T_RP_ALERTES" MODIFY ("ALERTAID" NOT NULL ENABLE);
