--------------------------------------------------------
--  Constraints for Table Z_T_RP_INFORMACIONSACCIONS
--------------------------------------------------------

  ALTER TABLE "SINTAGMA_U"."Z_T_RP_INFORMACIONSACCIONS" MODIFY ("ESACTIU" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."Z_T_RP_INFORMACIONSACCIONS" MODIFY ("USUARIID" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."Z_T_RP_INFORMACIONSACCIONS" MODIFY ("ASPECTEID" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."Z_T_RP_INFORMACIONSACCIONS" MODIFY ("INFORMACIOACCIOID" NOT NULL ENABLE);
