--------------------------------------------------------
--  Constraints for Table Z_T_RP_RELACIONSELEMENTSPRINCI
--------------------------------------------------------

  ALTER TABLE "SINTAGMA_U"."Z_T_RP_RELACIONSELEMENTSPRINCI" MODIFY ("ELEMENTRELACIONAT" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."Z_T_RP_RELACIONSELEMENTSPRINCI" MODIFY ("ELEMENTMESTRE" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."Z_T_RP_RELACIONSELEMENTSPRINCI" MODIFY ("RELACIOELEMENTPRINCIPALID" NOT NULL ENABLE);
