--------------------------------------------------------
--  Constraints for Table Z_T_RP_COTESARXIU
--------------------------------------------------------

  ALTER TABLE "SINTAGMA_U"."Z_T_RP_COTESARXIU" MODIFY ("INSTALACIOID" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."Z_T_RP_COTESARXIU" MODIFY ("ESVALORDEFECTE" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."Z_T_RP_COTESARXIU" MODIFY ("NOM" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."Z_T_RP_COTESARXIU" MODIFY ("COTAARXIUID" NOT NULL ENABLE);
