--------------------------------------------------------
--  Constraints for Table Z_T_RP_HISTORICASSIGNACIONS
--------------------------------------------------------

  ALTER TABLE "SINTAGMA_U"."Z_T_RP_HISTORICASSIGNACIONS" MODIFY ("ESTAASSIMILAT" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."Z_T_RP_HISTORICASSIGNACIONS" MODIFY ("DATAASSIGNACIO" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."Z_T_RP_HISTORICASSIGNACIONS" MODIFY ("USUARIREBEDOR" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."Z_T_RP_HISTORICASSIGNACIONS" MODIFY ("EXPEDIENTID" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."Z_T_RP_HISTORICASSIGNACIONS" MODIFY ("ASPECTEID" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."Z_T_RP_HISTORICASSIGNACIONS" MODIFY ("USUARIASSIGNADORID" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."Z_T_RP_HISTORICASSIGNACIONS" MODIFY ("HISTORICASSIGNACIONSID" NOT NULL ENABLE);
