--------------------------------------------------------
--  Constraints for Table Z_T_RP_HISTORICACCIONS
--------------------------------------------------------

  ALTER TABLE "SINTAGMA_U"."Z_T_RP_HISTORICACCIONS" MODIFY ("DATAREALITZACIO" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."Z_T_RP_HISTORICACCIONS" MODIFY ("EXPEDIENTID" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."Z_T_RP_HISTORICACCIONS" MODIFY ("ASPECTEID" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."Z_T_RP_HISTORICACCIONS" MODIFY ("USUARIID" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."Z_T_RP_HISTORICACCIONS" MODIFY ("HISTORICACCIONSID" NOT NULL ENABLE);
