--------------------------------------------------------
--  Constraints for Table Z_T_RP_ACCIONS
--------------------------------------------------------

  ALTER TABLE "SINTAGMA_U"."Z_T_RP_ACCIONS" MODIFY ("ESASSABENTAT" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."Z_T_RP_ACCIONS" MODIFY ("ESPERARESPOSTA" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."Z_T_RP_ACCIONS" MODIFY ("PRIORITATID" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."Z_T_RP_ACCIONS" MODIFY ("SUBTIPUSACCIOID" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."Z_T_RP_ACCIONS" MODIFY ("DATAINICI" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."Z_T_RP_ACCIONS" MODIFY ("ASPECTEID" NOT NULL ENABLE);
