--------------------------------------------------------
--  Constraints for Table Z_T_RP_PLANTILLES_BCK
--------------------------------------------------------

  ALTER TABLE "SINTAGMA_U"."Z_T_RP_PLANTILLES_BCK" MODIFY ("TIPUSPLANTILLAID" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."Z_T_RP_PLANTILLES_BCK" MODIFY ("ESARXIVABLE" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."Z_T_RP_PLANTILLES_BCK" MODIFY ("ESEDITABLE" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."Z_T_RP_PLANTILLES_BCK" MODIFY ("NUMCOPIES" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."Z_T_RP_PLANTILLES_BCK" MODIFY ("NOMFITXER" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."Z_T_RP_PLANTILLES_BCK" MODIFY ("DESCRIPCIO" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."Z_T_RP_PLANTILLES_BCK" MODIFY ("INSTALACIOID" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."Z_T_RP_PLANTILLES_BCK" MODIFY ("PLANTILLAID" NOT NULL ENABLE);
