--------------------------------------------------------
--  Constraints for Table Z_T_SIAP_COSTOS_CAIXA
--------------------------------------------------------

  ALTER TABLE "SINTAGMA_U"."Z_T_SIAP_COSTOS_CAIXA" MODIFY ("M_001" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."Z_T_SIAP_COSTOS_CAIXA" MODIFY ("M_002" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."Z_T_SIAP_COSTOS_CAIXA" MODIFY ("M_005" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."Z_T_SIAP_COSTOS_CAIXA" MODIFY ("M_010" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."Z_T_SIAP_COSTOS_CAIXA" MODIFY ("M_020" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."Z_T_SIAP_COSTOS_CAIXA" MODIFY ("M_050" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."Z_T_SIAP_COSTOS_CAIXA" MODIFY ("M_1" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."Z_T_SIAP_COSTOS_CAIXA" MODIFY ("M_2" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."Z_T_SIAP_COSTOS_CAIXA" MODIFY ("B_5" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."Z_T_SIAP_COSTOS_CAIXA" MODIFY ("B_10" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."Z_T_SIAP_COSTOS_CAIXA" MODIFY ("B_20" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."Z_T_SIAP_COSTOS_CAIXA" MODIFY ("B_50" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."Z_T_SIAP_COSTOS_CAIXA" MODIFY ("B_100" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."Z_T_SIAP_COSTOS_CAIXA" MODIFY ("B_200" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."Z_T_SIAP_COSTOS_CAIXA" MODIFY ("B_500" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."Z_T_SIAP_COSTOS_CAIXA" MODIFY ("DATA" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."Z_T_SIAP_COSTOS_CAIXA" MODIFY ("ID" NOT NULL ENABLE);
