--------------------------------------------------------
--  Constraints for Table Z_T_RP_UNIFORMES
--------------------------------------------------------

  ALTER TABLE "SINTAGMA_U"."Z_T_RP_UNIFORMES" MODIFY ("INSTALACIOID" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."Z_T_RP_UNIFORMES" MODIFY ("ESVALORDEFECTE" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."Z_T_RP_UNIFORMES" MODIFY ("NOM" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."Z_T_RP_UNIFORMES" MODIFY ("UNIFORMEID" NOT NULL ENABLE);
