--------------------------------------------------------
--  Constraints for Table Z_T_RP_TIPUSELEMENTPRINCIPAL
--------------------------------------------------------

  ALTER TABLE "SINTAGMA_U"."Z_T_RP_TIPUSELEMENTPRINCIPAL" MODIFY ("ESVALORDEFECTE" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."Z_T_RP_TIPUSELEMENTPRINCIPAL" MODIFY ("INSTALACIOID" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."Z_T_RP_TIPUSELEMENTPRINCIPAL" MODIFY ("NOM" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."Z_T_RP_TIPUSELEMENTPRINCIPAL" MODIFY ("TIPUSELEMENTPRINCIPALID" NOT NULL ENABLE);
