--------------------------------------------------------
--  Constraints for Table Z_T_SIAP_COSTOS_TIPUSMOVIMENT
--------------------------------------------------------

  ALTER TABLE "SINTAGMA_U"."Z_T_SIAP_COSTOS_TIPUSMOVIMENT" MODIFY ("ENTITAT" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."Z_T_SIAP_COSTOS_TIPUSMOVIMENT" MODIFY ("SENTIT" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."Z_T_SIAP_COSTOS_TIPUSMOVIMENT" MODIFY ("TIPUSMOVIMENT" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."Z_T_SIAP_COSTOS_TIPUSMOVIMENT" MODIFY ("CODI" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."Z_T_SIAP_COSTOS_TIPUSMOVIMENT" MODIFY ("ID" NOT NULL ENABLE);
