--------------------------------------------------------
--  Constraints for Table Z_T_RP_PREFIXDOSSIER
--------------------------------------------------------

  ALTER TABLE "SINTAGMA_U"."Z_T_RP_PREFIXDOSSIER" MODIFY ("ULTIMNUMERO" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."Z_T_RP_PREFIXDOSSIER" MODIFY ("ESVALORDEFECTE" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."Z_T_RP_PREFIXDOSSIER" MODIFY ("PREFIX" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."Z_T_RP_PREFIXDOSSIER" MODIFY ("INSTALACIOID" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."Z_T_RP_PREFIXDOSSIER" MODIFY ("PREFIXDOSSIERID" NOT NULL ENABLE);
