--------------------------------------------------------
--  Constraints for Table Z_T_RP_USUARIS
--------------------------------------------------------

  ALTER TABLE "SINTAGMA_U"."Z_T_RP_USUARIS" MODIFY ("ESTAACTIU" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."Z_T_RP_USUARIS" MODIFY ("COGNOMS" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."Z_T_RP_USUARIS" MODIFY ("NOM" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."Z_T_RP_USUARIS" MODIFY ("USUARI" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."Z_T_RP_USUARIS" MODIFY ("ADRECACORREU" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."Z_T_RP_USUARIS" MODIFY ("INSTALACIOID" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."Z_T_RP_USUARIS" MODIFY ("USUARIID" NOT NULL ENABLE);
