--------------------------------------------------------
--  Constraints for Table Z_T_RP_ESPECIFICS
--------------------------------------------------------

  ALTER TABLE "SINTAGMA_U"."Z_T_RP_ESPECIFICS" MODIFY ("INSTALACIOID" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."Z_T_RP_ESPECIFICS" MODIFY ("ESVALORDEFECTE" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."Z_T_RP_ESPECIFICS" MODIFY ("NOM" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."Z_T_RP_ESPECIFICS" MODIFY ("ESPECIFICID" NOT NULL ENABLE);
