--------------------------------------------------------
--  Constraints for Table Z_T_RP_CONCURRENCIES
--------------------------------------------------------

  ALTER TABLE "SINTAGMA_U"."Z_T_RP_CONCURRENCIES" MODIFY ("INSTALACIOID" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."Z_T_RP_CONCURRENCIES" MODIFY ("USUARIID" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."Z_T_RP_CONCURRENCIES" MODIFY ("DATAHORAINICI" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."Z_T_RP_CONCURRENCIES" MODIFY ("REGISTRE" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."Z_T_RP_CONCURRENCIES" MODIFY ("TAULA" NOT NULL ENABLE);
