--------------------------------------------------------
--  Constraints for Table Z_T_RP_CONTACTES
--------------------------------------------------------

  ALTER TABLE "SINTAGMA_U"."Z_T_RP_CONTACTES" MODIFY ("INSTALACIOID" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."Z_T_RP_CONTACTES" MODIFY ("PERTANYREPOSITORI" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."Z_T_RP_CONTACTES" MODIFY ("COGNOMS" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."Z_T_RP_CONTACTES" MODIFY ("NOM" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."Z_T_RP_CONTACTES" MODIFY ("CONTACTEID" NOT NULL ENABLE);
