--------------------------------------------------------
--  Constraints for Table Z_T_RP_TIPUSTEMAELEMENTPRINCIP
--------------------------------------------------------

  ALTER TABLE "SINTAGMA_U"."Z_T_RP_TIPUSTEMAELEMENTPRINCIP" MODIFY ("INSTALACIOID" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."Z_T_RP_TIPUSTEMAELEMENTPRINCIP" MODIFY ("ESVALORDEFECTE" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."Z_T_RP_TIPUSTEMAELEMENTPRINCIP" MODIFY ("NOM" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."Z_T_RP_TIPUSTEMAELEMENTPRINCIP" MODIFY ("TIPUSTEMAELEMENTPRINCIPALID" NOT NULL ENABLE);
