--------------------------------------------------------
--  Constraints for Table Z_TMP_RISPLUS_U_CONTACTES
--------------------------------------------------------

  ALTER TABLE "SINTAGMA_U"."Z_TMP_RISPLUS_U_CONTACTES" MODIFY ("INSTALACIOID" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."Z_TMP_RISPLUS_U_CONTACTES" MODIFY ("PERTANYREPOSITORI" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."Z_TMP_RISPLUS_U_CONTACTES" MODIFY ("COGNOMS" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."Z_TMP_RISPLUS_U_CONTACTES" MODIFY ("NOM" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."Z_TMP_RISPLUS_U_CONTACTES" MODIFY ("CONTACTEID" NOT NULL ENABLE);
