--------------------------------------------------------
--  Constraints for Table ZONA
--------------------------------------------------------

  ALTER TABLE "SINTAGMA_U"."ZONA" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "T_SINTAGMA"  ENABLE;
  ALTER TABLE "SINTAGMA_U"."ZONA" MODIFY ("USUARI_CREACIO" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."ZONA" MODIFY ("DATA_CREACIO" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."ZONA" MODIFY ("COLOR_ID" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."ZONA" MODIFY ("ABREVIATURA" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."ZONA" MODIFY ("NOM" NOT NULL ENABLE);
  ALTER TABLE "SINTAGMA_U"."ZONA" MODIFY ("ID" NOT NULL ENABLE);
