--------------------------------------------------------
--  DDL for Table A0_CONTACTE_CONSENTIMENT
--------------------------------------------------------

  CREATE TABLE "SINTAGMA_U"."A0_CONTACTE_CONSENTIMENT" 
   (	"ID" NUMBER(10,0), 
	"DATA_CONSENTIMENT" DATE, 
	"DATA_REVOCAMENT" DATE, 
	"DATA_CREACIO" TIMESTAMP (7), 
	"DATA_ESBORRAT" TIMESTAMP (7), 
	"DATA_MODIFICACIO" TIMESTAMP (7), 
	"USUARI_CREACIO" VARCHAR2(10 BYTE), 
	"USUARI_ESBORRAT" VARCHAR2(10 BYTE), 
	"USUARI_MODIFICACIO" VARCHAR2(10 BYTE), 
	"DOCUMENT_ID" NUMBER(10,0), 
	"CONTACTE_ID" NUMBER(10,0), 
	"ID_ORIGINAL" VARCHAR2(30 BYTE), 
	"ESQUEMA_ORIGINAL" VARCHAR2(30 BYTE), 
	"TABLA_ORIGINAL" VARCHAR2(30 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "T_SINTAGMA" ;
