--------------------------------------------------------
--  DDL for Table A0_CONVIDAT_ACOMPANYANT
--------------------------------------------------------

  CREATE TABLE "SINTAGMA_U"."A0_CONVIDAT_ACOMPANYANT" 
   (	"ID" NUMBER(10,0), 
	"NOM" VARCHAR2(150 BYTE), 
	"DATA_CREACIO" TIMESTAMP (0), 
	"DATA_MODIFICACIO" TIMESTAMP (0), 
	"DATA_ESBORRAT" TIMESTAMP (0), 
	"USUARI_CREACIO" VARCHAR2(50 BYTE), 
	"USUARI_MODIFICACIO" VARCHAR2(50 BYTE), 
	"USUARI_ESBORRAT" VARCHAR2(50 BYTE), 
	"CONVIDAT_ID" NUMBER(10,0), 
	"ID_ORIGINAL" VARCHAR2(30 BYTE), 
	"ESQUEMA_ORIGINAL" VARCHAR2(30 BYTE), 
	"TABLA_ORIGINAL" VARCHAR2(30 BYTE), 
	"COGNOM1" VARCHAR2(50 BYTE), 
	"COGNOM2" VARCHAR2(50 BYTE), 
	"ENTITAT" VARCHAR2(100 BYTE), 
	"ESTAT_CONFIRMACIO_ID" NUMBER(10,0), 
	"DECISIO_ASSISTENCIA_ID" NUMBER(10,0)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "T_SINTAGMA" ;
