--------------------------------------------------------
--  DDL for Table A0_ELEMENTS_RELACIONATS
--------------------------------------------------------

  CREATE TABLE "SINTAGMA_U"."A0_ELEMENTS_RELACIONATS" 
   (	"ID" NUMBER(10,0), 
	"ELEMENT_PRINCIPAL1" NUMBER(10,0), 
	"ELEMENT_PRINCIPAL2" NUMBER(10,0), 
	"ID_ORIGINAL" VARCHAR2(30 BYTE), 
	"ESQUEMA_ORIGINAL" VARCHAR2(30 BYTE), 
	"TABLA_ORIGINAL" VARCHAR2(30 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "T_SINTAGMA" ;
