--------------------------------------------------------
--  DDL for Table A0_PARAMETRE
--------------------------------------------------------

  CREATE TABLE "SINTAGMA_U"."A0_PARAMETRE" 
   (	"ID" NUMBER, 
	"CLAU" VARCHAR2(50 BYTE), 
	"VALOR" VARCHAR2(200 BYTE), 
	"DATA_CREACIO" TIMESTAMP (6), 
	"DATA_ESBORRAT" TIMESTAMP (6), 
	"DATA_MODIFICACIO" TIMESTAMP (6), 
	"USUARI_CREACIO" VARCHAR2(50 BYTE), 
	"USUARI_ESBORRAT" VARCHAR2(50 BYTE), 
	"USUARI_MODIFICACIO" VARCHAR2(50 BYTE), 
	"ID_ORIGINAL" VARCHAR2(30 BYTE), 
	"ESQUEMA_ORIGINAL" VARCHAR2(30 BYTE), 
	"TABLA_ORIGINAL" VARCHAR2(30 BYTE), 
	"INSTALACIOID" VARCHAR2(30 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "T_SINTAGMA" ;
