--------------------------------------------------------
--  DDL for Table A0_RASTRE
--------------------------------------------------------

  CREATE TABLE "SINTAGMA_U"."A0_RASTRE" 
   (	"ID" NUMBER(10,0), 
	"TIPUS_ACCIO" VARCHAR2(50 BYTE), 
	"ACCIO" VARCHAR2(50 BYTE), 
	"DATA_INICI" TIMESTAMP (0), 
	"DATA_FI" TIMESTAMP (0), 
	"RESPONSABLE" VARCHAR2(50 BYTE), 
	"DATA_CREACIO" TIMESTAMP (0), 
	"DATA_MODIFICACIO" TIMESTAMP (0), 
	"DATA_ESBORRAT" TIMESTAMP (0), 
	"USUARI_CREACIO" VARCHAR2(50 BYTE), 
	"USUARI_MODIFICACIO" VARCHAR2(50 BYTE), 
	"USUARI_ESBORRAT" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "T_SINTAGMA" ;
