--------------------------------------------------------
--  DDL for Table A1_COMENTARI
--------------------------------------------------------

  CREATE TABLE "SINTAGMA_U"."A1_COMENTARI" 
   (	"ID" NUMBER(10,0), 
	"NOM_USUARI" VARCHAR2(50 BYTE), 
	"MATRICULA_USUARI" VARCHAR2(50 BYTE), 
	"COMENTARI" VARCHAR2(4000 BYTE), 
	"DATA_COMENTARI" TIMESTAMP (0), 
	"DATA_CREACIO" NUMBER(10,0), 
	"DATA_MODIFICACIO" NUMBER(10,0), 
	"DATA_ESBORRAT" NUMBER(10,0), 
	"USUARI_CREACIO" NUMBER(10,0), 
	"USUARI_MODIFICACIO" NUMBER(10,0), 
	"USUARI_ESBORRAT" NUMBER(10,0), 
	"ASPECTE_ID" NUMBER(10,0), 
	"ID_ORIGINAL" VARCHAR2(30 BYTE), 
	"ESQUEMA_ORIGINAL" VARCHAR2(30 BYTE), 
	"TABLA_ORIGINAL" VARCHAR2(30 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "T_SINTAGMA" ;
