--------------------------------------------------------
--  DDL for Table A1_MANTENIMENT_DM
--------------------------------------------------------

  CREATE TABLE "SINTAGMA_U"."A1_MANTENIMENT_DM" 
   (	"ID" NUMBER, 
	"TABLE_NAME" VARCHAR2(50 BYTE), 
	"AMBIT_ID" NUMBER, 
	"ID_ORIGINAL" VARCHAR2(30 BYTE), 
	"ESQUEMA_ORIGINAL" VARCHAR2(30 BYTE), 
	"TABLA_ORIGINAL" VARCHAR2(30 BYTE), 
	"INSTALACIOID" VARCHAR2(30 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "T_SINTAGMA" ;
