--------------------------------------------------------
--  DDL for Table A1_OBSEQUI_ENTREGAT
--------------------------------------------------------

  CREATE TABLE "SINTAGMA_U"."A1_OBSEQUI_ENTREGAT" 
   (	"ID" NUMBER(10,0), 
	"NOM" VARCHAR2(50 BYTE), 
	"COGNOM1" VARCHAR2(50 BYTE), 
	"COGNOM2" VARCHAR2(50 BYTE), 
	"DATA_ENTREGA" TIMESTAMP (0), 
	"DATA_CREACIO" TIMESTAMP (0), 
	"DATA_MODIFICACIO" TIMESTAMP (0), 
	"DATA_ESBORRAT" TIMESTAMP (0), 
	"USUARI_CREACIO" VARCHAR2(50 BYTE), 
	"USUARI_MODIFICACIO" VARCHAR2(50 BYTE), 
	"USUARI_ESBORRAT" VARCHAR2(50 BYTE), 
	"OBSEQUI_ID" NUMBER(10,0), 
	"ID_ORIGINAL" VARCHAR2(30 BYTE), 
	"ESQUEMA_ORIGINAL" VARCHAR2(30 BYTE), 
	"TABLA_ORIGINAL" VARCHAR2(30 BYTE), 
	"INSTALACIOID" VARCHAR2(30 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "T_SINTAGMA" ;
