--------------------------------------------------------
--  DDL for Table A1_SUBJECTES_ARTICLE
--------------------------------------------------------

  CREATE TABLE "SINTAGMA_U"."A1_SUBJECTES_ARTICLE" 
   (	"ID" NUMBER(10,0), 
	"NOM" VARCHAR2(50 BYTE), 
	"COGNOM1" VARCHAR2(40 BYTE), 
	"COGNOM2" VARCHAR2(40 BYTE), 
	"TRACTAMENT_ID" NUMBER(10,0), 
	"SEXO" VARCHAR2(1 BYTE), 
	"LETRA" VARCHAR2(1 BYTE), 
	"ARTICLE_ID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "T_SINTAGMA" ;
