--------------------------------------------------------
--  DDL for Table ACTE
--------------------------------------------------------

  CREATE TABLE "SINTAGMA_U"."ACTE" 
   (	"ID" NUMBER(10,0), 
	"TITOL" VARCHAR2(100 BYTE), 
	"DATA_CREACIO" TIMESTAMP (0), 
	"DATA_ESBORRAT" TIMESTAMP (0), 
	"DATA_MODIFICACIO" TIMESTAMP (0), 
	"USUARI_CREACIO" VARCHAR2(50 BYTE), 
	"USUARI_ESBORRAT" VARCHAR2(50 BYTE), 
	"USUARI_MODIFICACIO" VARCHAR2(50 BYTE), 
	"DATA_ENTRADA" TIMESTAMP (0), 
	"COMENTARIS_VALORACIO" VARCHAR2(4000 BYTE), 
	"ELEMENT_PRINCIPAL_ID" NUMBER(10,0), 
	"TIPUS_ACTE_ID" NUMBER(10,0), 
	"CATEGORIA_ID" NUMBER(10,0), 
	"SECTOR_ID" NUMBER(10,0), 
	"PRESIDENT_ID" NUMBER(10,0), 
	"PETICIONARI_ID" NUMBER(10,0), 
	"ESTAT_ACTE_ID" NUMBER(10,0), 
	"ESTAT_GESTIO_INVITACIO_ID" NUMBER(10,0), 
	"ESTAT_GESTIO_ESPAIS_ID" NUMBER(10,0), 
	"ID_ORIGINAL" VARCHAR2(30 BYTE), 
	"ESQUEMA_ORIGINAL" VARCHAR2(30 BYTE), 
	"TABLA_ORIGINAL" VARCHAR2(30 BYTE), 
	"TECNIC_MATRICULA" VARCHAR2(50 BYTE), 
	"TECNIC_NOM" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "T_SINTAGMA" ;
