--------------------------------------------------------
--  DDL for Table ANNEX_REGISTRE
--------------------------------------------------------

  CREATE TABLE "SINTAGMA_U"."ANNEX_REGISTRE" 
   (	"ID" NUMBER(10,0), 
	"TITOL" VARCHAR2(100 BYTE), 
	"COMENTARI" VARCHAR2(4000 BYTE), 
	"ES_CARPETA_ALCALDE" NUMBER(1,0), 
	"REGISTRE_ID" NUMBER(10,0), 
	"DOCUMENT_ID" NUMBER(10,0), 
	"ID_ORIGINAL" VARCHAR2(30 BYTE), 
	"ESQUEMA_ORIGINAL" VARCHAR2(30 BYTE), 
	"TABLA_ORIGINAL" VARCHAR2(30 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "T_SINTAGMA" ;
