--------------------------------------------------------
--  DDL for Table AUX_EXPEDIENT
--------------------------------------------------------

  CREATE TABLE "SINTAGMA_U"."AUX_EXPEDIENT" 
   (	"ID" NUMBER, 
	"ANYO" NUMBER, 
	"CONTRACTE" NUMBER, 
	"ASSENTAMENT" VARCHAR2(255 BYTE), 
	"IDPARTIDA" NUMBER, 
	"PARTIDA" VARCHAR2(255 BYTE), 
	"CONCEPTE" VARCHAR2(255 BYTE), 
	"IMPORT" NUMBER(15,2), 
	"OBLIGAT" NUMBER, 
	"REMANENT" NUMBER, 
	"REMANENT_SAP" NUMBER
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "T_SINTAGMA" ;
