--------------------------------------------------------
--  DDL for Table BDANI_TB_CONTACTES_AUX
--------------------------------------------------------

  CREATE TABLE "SINTAGMA_U"."BDANI_TB_CONTACTES_AUX" 
   (	"ID_CONTACTE" NUMBER(*,0), 
	"N_VIP" NUMBER, 
	"ADRECA" VARCHAR2(100 BYTE), 
	"MUNICIPI" VARCHAR2(30 BYTE), 
	"CP" VARCHAR2(10 BYTE), 
	"PROVINCIA" VARCHAR2(30 BYTE), 
	"PAIS" VARCHAR2(30 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "T_SINTAGMA" ;
