--------------------------------------------------------
--  DDL for Table CLASSIFICACIO_ARXIU
--------------------------------------------------------

  CREATE TABLE "SINTAGMA_U"."CLASSIFICACIO_ARXIU" 
   (	"ID" NUMBER(10,0), 
	"DESCRIPTORS_TEMATICS" VARCHAR2(200 BYTE), 
	"DATA_TRANSFERENCIA" TIMESTAMP (0), 
	"DATA_ARXIU" TIMESTAMP (0), 
	"DATA_CREACIO" TIMESTAMP (0), 
	"DATA_MODIFICACIO" TIMESTAMP (0), 
	"DATA_ESBORRAT" TIMESTAMP (0), 
	"USUARI_CREACIO" VARCHAR2(50 BYTE), 
	"USUARI_MODIFICACIO" VARCHAR2(50 BYTE), 
	"USUARI_ESBORRAT" VARCHAR2(50 BYTE), 
	"SERIE_ID" NUMBER(10,0), 
	"ESPECIFIC_ID" NUMBER(10,0), 
	"ASPECTE_ID" NUMBER(10,0), 
	"ID_ORIGINAL" VARCHAR2(30 BYTE), 
	"ESQUEMA_ORIGINAL" VARCHAR2(30 BYTE), 
	"TABLA_ORIGINAL" VARCHAR2(30 BYTE), 
	"INSTALACIOID" VARCHAR2(30 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "T_SINTAGMA" ;
