--------------------------------------------------------
--  DDL for Table ELEMENTS_RELACIONATS
--------------------------------------------------------

  CREATE TABLE "SINTAGMA_U"."ELEMENTS_RELACIONATS" 
   (	"ID" NUMBER(10,0), 
	"ELEMENT_PRINCIPAL1_ID" NUMBER(10,0), 
	"ELEMENT_PRINCIPAL2_ID" NUMBER(10,0), 
	"ID_ORIGINAL" VARCHAR2(30 BYTE), 
	"ESQUEMA_ORIGINAL" VARCHAR2(30 BYTE), 
	"TABLA_ORIGINAL" VARCHAR2(30 BYTE), 
	"DATA_CREACIO" TIMESTAMP (6) DEFAULT (SYSTIMESTAMP), 
	"DATA_ESBORRAT" TIMESTAMP (6), 
	"DATA_MODIFICACIO" TIMESTAMP (6), 
	"USUARI_CREACIO" VARCHAR2(10 BYTE) DEFAULT ('[TEST]'), 
	"USUARI_ESBORRAT" VARCHAR2(10 BYTE), 
	"USUARI_MODIFICACIO" VARCHAR2(10 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "T_SINTAGMA" ;
