--------------------------------------------------------
--  DDL for Table ENTRADA_AGENDA
--------------------------------------------------------

  CREATE TABLE "SINTAGMA_U"."ENTRADA_AGENDA" 
   (	"ID" NUMBER(10,0), 
	"LLOC_BIS" VARCHAR2(100 BYTE), 
	"DATA_INICI_ACTE" TIMESTAMP (6), 
	"DATA_FI_ACTE" TIMESTAMP (6), 
	"DATA_CREACIO" TIMESTAMP (0), 
	"DATA_MODIFICACIO" TIMESTAMP (0), 
	"DATA_ESBORRAT" TIMESTAMP (0), 
	"USUARI_CREACIO" VARCHAR2(50 BYTE), 
	"USUARI_MODIFICACIO" VARCHAR2(50 BYTE), 
	"USUARI_ESBORRAT" VARCHAR2(50 BYTE), 
	"ACOMPANYANT" VARCHAR2(1000 BYTE), 
	"VALORACIO" VARCHAR2(4000 BYTE), 
	"ASSISTENTS" VARCHAR2(1000 BYTE), 
	"ES_AFECTA_PROTOCOL" NUMBER(1,0), 
	"ES_DECISIO" NUMBER(1,0), 
	"ELEMENT_PRINCIPAL_ID" NUMBER(10,0), 
	"DECISIO_AGENDA_ID" NUMBER(10,0), 
	"TIPUS_AGENDA_ID" NUMBER(10,0), 
	"LLOC_ID" NUMBER(10,0), 
	"TIPUS_DATA_ID" NUMBER(10,0), 
	"DISTRICTE_ID" NUMBER(10,0), 
	"BARRI_ID" NUMBER(10,0), 
	"ID_ORIGINAL" VARCHAR2(30 BYTE), 
	"ESQUEMA_ORIGINAL" VARCHAR2(30 BYTE), 
	"TABLA_ORIGINAL" VARCHAR2(30 BYTE), 
	"INSTALACIOID" VARCHAR2(30 BYTE), 
	"DESTI_DELEGACIO_ID" NUMBER(10,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "T_SINTAGMA" ;
