--------------------------------------------------------
--  DDL for Table ERR_ADRECA
--------------------------------------------------------

  CREATE TABLE "SINTAGMA_U"."ERR_ADRECA" 
   (	"ID" NUMBER(*,0), 
	"NOM_CARRER" VARCHAR2(4000 BYTE), 
	"ID_ORIGINAL" CHAR(9 BYTE), 
	"ESQUEMA_ORIGINAL" CHAR(60 BYTE), 
	"TABLA_ORIGINAL" VARCHAR2(60 BYTE), 
	"ERROR_DESCRIPCION" CHAR(300 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "T_SINTAGMA" ;
