--------------------------------------------------------
--  DDL for Table ERR_CONTACTES_SIN_GENER
--------------------------------------------------------

  CREATE TABLE "SINTAGMA_U"."ERR_CONTACTES_SIN_GENER" 
   (	"N_VIP" NUMBER(10,0), 
	"CLASSIF" VARCHAR2(5 BYTE), 
	"N_PRELACIO" NUMBER(4,0), 
	"CARREC" VARCHAR2(100 BYTE), 
	"ENTITAT" VARCHAR2(100 BYTE), 
	"ADRECA" VARCHAR2(100 BYTE), 
	"MUNICIPI" VARCHAR2(30 BYTE), 
	"CP" VARCHAR2(10 BYTE), 
	"PROVINCIA" VARCHAR2(30 BYTE), 
	"PAIS" VARCHAR2(30 BYTE), 
	"TELEFON1" VARCHAR2(14 BYTE), 
	"TELEFON2" VARCHAR2(14 BYTE), 
	"TELEFON_MOBIL" VARCHAR2(14 BYTE), 
	"FAX" VARCHAR2(14 BYTE), 
	"INTERNET" VARCHAR2(99 BYTE), 
	"DEPART" VARCHAR2(35 BYTE), 
	"ESQUEMA_ORIGINAL" CHAR(6 BYTE), 
	"TABLA_ORIGINAL" CHAR(4 BYTE), 
	"DESCRIPCION_ERR" CHAR(38 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "T_SINTAGMA" ;
