--------------------------------------------------------
--  DDL for Table ERR_NOMBRES_DISTINTOS_SIAP_VIP
--------------------------------------------------------

  CREATE TABLE "SINTAGMA_U"."ERR_NOMBRES_DISTINTOS_SIAP_VIP" 
   (	"ID_SIAP" NUMBER, 
	"NOM_SIAP" VARCHAR2(15 BYTE), 
	"COGNOMS_SIAP" VARCHAR2(255 BYTE), 
	"ID_VIPS" NUMBER(10,0), 
	"NOM_VIPS" VARCHAR2(15 BYTE), 
	"COGNOMS_VIPS" VARCHAR2(35 BYTE), 
	"ERROR" CHAR(40 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "T_SINTAGMA" ;
