--------------------------------------------------------
--  DDL for Table ERR_ADRECA_RISPLUS
--------------------------------------------------------

  CREATE TABLE "SINTAGMA_U"."ERR_ADRECA_RISPLUS" 
   (	"CONTACTEID" NUMBER(38,0), 
	"ESQUEMA" CHAR(7 BYTE), 
	"TABLA" CHAR(25 BYTE), 
	"CAMPO_ERROR" CHAR(49 BYTE), 
	"ERROR_DESC" CHAR(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "T_SINTAGMA" ;
