--------------------------------------------------------
--  DDL for Table ERR_TELEFONOS
--------------------------------------------------------

  CREATE TABLE "SINTAGMA_U"."ERR_TELEFONOS" 
   (	"ID_CONTACTE" NUMBER(*,0), 
	"N_VIP" NUMBER(10,0), 
	"TELEFON" VARCHAR2(14 BYTE), 
	"CAMPO" CHAR(8 BYTE), 
	"ESQUEMA" CHAR(6 BYTE), 
	"TABLA" CHAR(12 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "T_SINTAGMA" ;
