--------------------------------------------------------
--  DDL for Table ERR_CONTACTE
--------------------------------------------------------

  CREATE TABLE "SINTAGMA_U"."ERR_CONTACTE" 
   (	"ID" NUMBER(*,0), 
	"NOM" VARCHAR2(80 BYTE), 
	"COGNOMS" VARCHAR2(500 BYTE), 
	"TIPUS_CONTACTE_ID" NUMBER, 
	"CARREC_ID" NUMBER, 
	"ENTITAT_ID" NUMBER, 
	"ID_ORIGINAL" VARCHAR2(30 BYTE), 
	"ESQUEMA_ORIGINAL" CHAR(30 BYTE), 
	"TABLA_ORIGINAL" CHAR(30 BYTE), 
	"ERR_DESCRIPCION" CHAR(300 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "T_SINTAGMA" ;
