--------------------------------------------------------
--  DDL for Table ERR_R_SUBJECTES_NOM_NULL
--------------------------------------------------------

  CREATE TABLE "SINTAGMA_U"."ERR_R_SUBJECTES_NOM_NULL" 
   (	"CONTACTEID" NUMBER(38,0), 
	"NOM" VARCHAR2(100 BYTE), 
	"COGNOMS" VARCHAR2(200 BYTE), 
	"NOM_NORMALITZAT" VARCHAR2(4000 BYTE), 
	"ERR" CHAR(32 BYTE), 
	"TABLA" CHAR(25 BYTE), 
	"ESQUEMA" CHAR(7 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "T_SINTAGMA" ;
