--------------------------------------------------------
--  DDL for Table ERR_SUBJECTE_NOMS_REP
--------------------------------------------------------

  CREATE TABLE "SINTAGMA_U"."ERR_SUBJECTE_NOMS_REP" 
   (	"ID" NUMBER(10,0), 
	"NOM" VARCHAR2(50 BYTE), 
	"COGNOM1" VARCHAR2(40 BYTE), 
	"COGNOM2" VARCHAR2(40 BYTE), 
	"ALIES" VARCHAR2(40 BYTE), 
	"DATA_DEFUNCIO" DATE, 
	"ES_PROVISIONAL" NUMBER(1,0), 
	"NOM_NORMALITZAT" VARCHAR2(60 BYTE), 
	"MOTIU_BAIXA" VARCHAR2(500 BYTE), 
	"DATA_CREACIO" TIMESTAMP (7), 
	"DATA_ESBORRAT" TIMESTAMP (7), 
	"DATA_MODIFICACIO" TIMESTAMP (7), 
	"USUARI_CREACIO" VARCHAR2(10 BYTE), 
	"USUARI_ESBORRAT" VARCHAR2(10 BYTE), 
	"USUARI_MODIFICACIO" VARCHAR2(10 BYTE), 
	"TRACTAMENT_ID" NUMBER(10,0), 
	"PRIORITAT_ID" NUMBER(10,0), 
	"TIPUS_SUBJECTE_ID" NUMBER(10,0), 
	"AMBIT_ID" NUMBER(10,0), 
	"IDIOMA_ID" NUMBER(10,0), 
	"ARTICLE_ID" NUMBER, 
	"ID_ORIGINAL" VARCHAR2(30 BYTE), 
	"ESQUEMA_ORIGINAL" VARCHAR2(30 BYTE), 
	"TABLA_ORIGINAL" VARCHAR2(30 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "T_SINTAGMA" ;
