--------------------------------------------------------
--  DDL for Table ERR_SUBJECTE
--------------------------------------------------------

  CREATE TABLE "SINTAGMA_U"."ERR_SUBJECTE" 
   (	"ID" NUMBER(*,0), 
	"NOM" VARCHAR2(4000 BYTE), 
	"COGNOM1" VARCHAR2(400 BYTE), 
	"COGNOM2" VARCHAR2(400 BYTE), 
	"TRACTAMENT_ID" NUMBER, 
	"ID_ORIGINAL" NUMBER(10,0), 
	"ESQUEMA_ORIGINAL" CHAR(30 BYTE), 
	"TABLA_ORIGINAL" VARCHAR2(30 BYTE), 
	"ERROR_DESCRIPCION" CHAR(300 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "T_SINTAGMA" ;
