--------------------------------------------------------
--  DDL for Table ERR_CONTACTES_SIN_SUBJECTES
--------------------------------------------------------

  CREATE TABLE "SINTAGMA_U"."ERR_CONTACTES_SIN_SUBJECTES" 
   (	"NP" VARCHAR2(100 BYTE), 
	"NOM2" VARCHAR2(100 BYTE), 
	"COGNOM_1" VARCHAR2(100 BYTE), 
	"COGNOM_2" VARCHAR2(100 BYTE), 
	"ESQUEMA_ORIGINAL" CHAR(6 BYTE), 
	"TABLA_ORIGINAL" CHAR(9 BYTE), 
	"ERR_DESCRIPCION" CHAR(41 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "T_SINTAGMA" ;
