--------------------------------------------------------
--  DDL for Table TRUCADA
--------------------------------------------------------

  CREATE TABLE "SINTAGMA_U"."TRUCADA" 
   (	"ID" NUMBER(10,0), 
	"DATA_REGISTRE" TIMESTAMP (7), 
	"DATA_RESOLUCIO" TIMESTAMP (7), 
	"NOM" VARCHAR2(30 BYTE), 
	"COGNOM1" VARCHAR2(40 BYTE), 
	"COGNOM2" VARCHAR2(40 BYTE), 
	"CARREC" VARCHAR2(100 BYTE), 
	"TELEFON" VARCHAR2(40 BYTE), 
	"TELEFON_SECUNDARI" VARCHAR2(40 BYTE), 
	"DESCRIPCIO" VARCHAR2(250 BYTE), 
	"DATA_CREACIO" TIMESTAMP (7), 
	"DATA_ESBORRAT" TIMESTAMP (7), 
	"DATA_MODIFICACIO" TIMESTAMP (7), 
	"USUARI_CREACIO" VARCHAR2(50 BYTE), 
	"USUARI_ESBORRAT" VARCHAR2(50 BYTE), 
	"USUARI_MODIFICACIO" VARCHAR2(50 BYTE), 
	"ENTITAT_ID" NUMBER(10,0), 
	"ESTAT_TRUCADA_ID" NUMBER(10,0), 
	"DESTINATARI_PERSONA_ID" NUMBER(10,0), 
	"CONTACTE_ID" NUMBER(10,0), 
	"SENTIT_ID" NUMBER(10,0), 
	"ID_ORIGINAL" VARCHAR2(30 BYTE), 
	"ESQUEMA_ORIGINAL" VARCHAR2(30 BYTE), 
	"TABLA_ORIGINAL" VARCHAR2(30 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "T_SINTAGMA" ;
