--------------------------------------------------------
--  DDL for Table TRUCADA_TEMA
--------------------------------------------------------

  CREATE TABLE "SINTAGMA_U"."TRUCADA_TEMA" 
   (	"ID" NUMBER(10,0), 
	"TRUCADA_ID" NUMBER(10,0), 
	"TEMA_ID" NUMBER(10,0), 
	"ID_ORIGINAL" VARCHAR2(30 BYTE), 
	"ESQUEMA_ORIGINAL" VARCHAR2(30 BYTE), 
	"TABLA_ORIGINAL" VARCHAR2(30 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "T_SINTAGMA" ;
