--------------------------------------------------------
--  DDL for Table WENTITATS_DIST
--------------------------------------------------------

  CREATE TABLE "SINTAGMA_U"."WENTITATS_DIST" 
   (	"ID" VARCHAR2(100 BYTE), 
	"ID_PERTENECE" CHAR(2 BYTE), 
	"ENTITAT" VARCHAR2(100 BYTE), 
	"ENTITAT_NORMA" VARCHAR2(4000 BYTE), 
	"TABLA_ORIGEN" CHAR(28 BYTE), 
	"BD_ORIGEN" CHAR(6 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "T_SINTAGMA" ;
