--------------------------------------------------------
--  DDL for Table WENTITATS
--------------------------------------------------------

  CREATE TABLE "SINTAGMA_U"."WENTITATS" 
   (	"ID" VARCHAR2(200 BYTE), 
	"ID_PERTENECE" VARCHAR2(200 BYTE), 
	"ENTITAT" VARCHAR2(200 BYTE), 
	"ENTITAT_NORMA" VARCHAR2(200 BYTE), 
	"TABLA_ORIGEN" VARCHAR2(200 BYTE), 
	"BD_ORIGEN" VARCHAR2(200 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "T_SINTAGMA" ;
