--------------------------------------------------------
--  DDL for Table Z_B002_DIF_CONT_PART_VIPS
--------------------------------------------------------

  CREATE TABLE "SINTAGMA_U"."Z_B002_DIF_CONT_PART_VIPS" 
   (	"ID_CONTACTE" NUMBER(*,0), 
	"N_VIP" NUMBER(10,0), 
	"ADRECA_P" VARCHAR2(100 BYTE), 
	"MUNICIPI_P" VARCHAR2(30 BYTE), 
	"TELEFON_P" VARCHAR2(14 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "T_SINTAGMA" ;
