--------------------------------------------------------
--  DDL for Table Z_C03_NO_EXISTE_SUBJECTE
--------------------------------------------------------

  CREATE TABLE "SINTAGMA_U"."Z_C03_NO_EXISTE_SUBJECTE" 
   (	"ID_SUBJECTE_SINTAGMA" NUMBER, 
	"ID_SUBJECTE" VARCHAR2(100 BYTE), 
	"NOM2" VARCHAR2(100 BYTE), 
	"COGNOM_1" VARCHAR2(100 BYTE), 
	"COGNOM_2" VARCHAR2(100 BYTE), 
	"ALIES" VARCHAR2(100 BYTE), 
	"NOM_NORMALITZAT" VARCHAR2(4000 BYTE), 
	"DATA_DEFUNCIO" VARCHAR2(100 BYTE), 
	"IDIOMA_ID" CHAR(4 BYTE), 
	"DATA_DARRERA" VARCHAR2(100 BYTE), 
	"DATA_BAIXA" VARCHAR2(100 BYTE), 
	"ID_PRIORITAT" CHAR(4 BYTE), 
	"TIPUS_SUBJECTE_ID" NUMBER, 
	"AMBIT_ID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "T_SINTAGMA" ;
