--------------------------------------------------------
--  DDL for Table Z_C35_ADRECA_CONTACTE
--------------------------------------------------------

  CREATE TABLE "SINTAGMA_U"."Z_C35_ADRECA_CONTACTE" 
   (	"ADRECA_ID" VARCHAR2(40 BYTE), 
	"NOM_CARRER" VARCHAR2(1000 BYTE), 
	"ID_CONTACTE_SINTAGMA" NUMBER, 
	"DIRECCIO" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "T_SINTAGMA" ;
