--------------------------------------------------------
--  DDL for Table Z_C40_SUBJECTES
--------------------------------------------------------

  CREATE TABLE "SINTAGMA_U"."Z_C40_SUBJECTES" 
   (	"ID" NUMBER, 
	"NOM" VARCHAR2(105 BYTE), 
	"COGNOM1" VARCHAR2(100 BYTE), 
	"COGNOM2" VARCHAR2(201 BYTE), 
	"ALIES" VARCHAR2(100 BYTE), 
	"DATA_DEFUNCIO" VARCHAR2(100 BYTE), 
	"ES_PROVISIONAL" NUMBER, 
	"NOM_NORMALITZAT" VARCHAR2(4000 BYTE), 
	"MOTIU_BAIXA" CHAR(4 BYTE), 
	"DATA_CREACIO" DATE, 
	"DATA_ESBORRAT" CHAR(4 BYTE), 
	"DATA_MODIFICACIO" CHAR(4 BYTE), 
	"USUARI_CREACIO" CHAR(8 BYTE), 
	"USUARI_ESBORRAT" CHAR(4 BYTE), 
	"USUARI_MODIFICACIO" CHAR(4 BYTE), 
	"TRACTAMENT_ID" CHAR(4 BYTE), 
	"PRIORITAT_ID" CHAR(4 BYTE), 
	"TIPUS_SUBJECTE_ID" NUMBER, 
	"AMBIT_ID" NUMBER, 
	"IDIOMA_ID" CHAR(4 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "T_SINTAGMA" ;
