--------------------------------------------------------
--  DDL for Table Z_C42_CONTACTE
--------------------------------------------------------

  CREATE TABLE "SINTAGMA_U"."Z_C42_CONTACTE" 
   (	"ID" NUMBER, 
	"ES_PRINCIPAL" NUMBER, 
	"DEPARTAMENT" VARCHAR2(35 BYTE), 
	"DADES_QUALITAT" NUMBER, 
	"DATA_DARRERA_ACTUALITZACIO" DATE, 
	"DATA_CREACIO" DATE, 
	"DATA_ESBORRAT" DATE, 
	"DATA_MODIFICACIO" DATE, 
	"USUARI_CREACIO" CHAR(8 BYTE), 
	"USUARI_ESBORRAT" CHAR(4 BYTE), 
	"USUARI_MODIFICACIO" CHAR(4 BYTE), 
	"TIPUS_CONTACTE_ID" NUMBER, 
	"SUBJECTE_ID" VARCHAR2(100 BYTE), 
	"ADRECA_ID" NUMBER, 
	"ENTITAT_ID" NUMBER, 
	"CONTACTE_ORIGEN_ID" CHAR(4 BYTE), 
	"VISIBILITAT_ID" NUMBER, 
	"AMBIT_ID" NUMBER, 
	"CARREC_ID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "T_SINTAGMA" ;
