--------------------------------------------------------
--  DDL for Table Z_C95_TRUCADAS_ACTIVES_CALIMA
--------------------------------------------------------

  CREATE TABLE "SINTAGMA_U"."Z_C95_TRUCADAS_ACTIVES_CALIMA" 
   (	"ID" VARCHAR2(100 BYTE), 
	"DATA_REGISTRE" DATE, 
	"DATA_RESOLUCIO" CHAR(4 BYTE), 
	"NOM" VARCHAR2(100 BYTE), 
	"COGNOM1" VARCHAR2(100 BYTE), 
	"COGNOM2" VARCHAR2(100 BYTE), 
	"CARREC" VARCHAR2(100 BYTE), 
	"TELEFON" VARCHAR2(100 BYTE), 
	"TELEFON_SECUNDARI" CHAR(4 BYTE), 
	"DESCRIPCIO" VARCHAR2(100 BYTE), 
	"DATA_CREACIO" DATE, 
	"DATA_ESBORRAT" CHAR(4 BYTE), 
	"DATA_MODIFICACIO" CHAR(4 BYTE), 
	"USUARI_CREACIO" VARCHAR2(100 BYTE), 
	"USUARI_ESBORRAT" CHAR(4 BYTE), 
	"USUARI_MODIFICACIO" VARCHAR2(100 BYTE), 
	"ENTITAT_ID" NUMBER, 
	"ESTAT_TRUCADA_ID" NUMBER, 
	"DESTINATARI_PERSONA_ID" NUMBER, 
	"CONTACTE_ID" CHAR(4 BYTE), 
	"SENTIT_ID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "T_SINTAGMA" ;
