--------------------------------------------------------
--  DDL for Table Z_D03_DM_CARREC
--------------------------------------------------------

  CREATE TABLE "SINTAGMA_U"."Z_D03_DM_CARREC" 
   (	"ID" NUMBER, 
	"DESCRIPCIO" VARCHAR2(100 BYTE), 
	"DATA_CREACIO" DATE, 
	"DATA_ESBORRAT" CHAR(4 BYTE), 
	"DATA_MODIFICACIO" CHAR(4 BYTE), 
	"USUARI_CREACIO" CHAR(8 BYTE), 
	"USUARI_ESBORRAT" CHAR(4 BYTE), 
	"USUARI_MIGRACIO" CHAR(4 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "T_SINTAGMA" ;
