--------------------------------------------------------
--  DDL for Table Z_D99_ADRECA
--------------------------------------------------------

  CREATE TABLE "SINTAGMA_U"."Z_D99_ADRECA" 
   (	"ID" NUMBER, 
	"CODI_MUNICIPI" CHAR(4 BYTE), 
	"MUNICIPI" VARCHAR2(100 BYTE), 
	"CODI_PROVINCIA" CHAR(4 BYTE), 
	"PROVINCIA" VARCHAR2(100 BYTE), 
	"CODI_PAIS" CHAR(4 BYTE), 
	"PAIS" VARCHAR2(100 BYTE), 
	"CODI_CARRER" CHAR(4 BYTE), 
	"NOM_CARRER" VARCHAR2(4000 BYTE), 
	"LLETRA_INICI" CHAR(4 BYTE), 
	"LLETRA_FI" CHAR(4 BYTE), 
	"ESCALA" CHAR(4 BYTE), 
	"CODI_POSTAL" VARCHAR2(10 BYTE), 
	"COORDENADA_X" CHAR(4 BYTE), 
	"COORDENADA_Y" CHAR(4 BYTE), 
	"SECCIO_CENSAL" CHAR(4 BYTE), 
	"ANY_CONST" CHAR(4 BYTE), 
	"NUMERO_INICI" CHAR(4 BYTE), 
	"NUMERO_FI" CHAR(4 BYTE), 
	"DATA_CREACIO" DATE, 
	"DATA_ESBORRAT" CHAR(4 BYTE), 
	"DATA_MODIFICACIO" CHAR(4 BYTE), 
	"USUARI_CREACIO" CHAR(8 BYTE), 
	"USUARI_ESBORRAT" CHAR(4 BYTE), 
	"USUARI_MODIFICACIO" CHAR(4 BYTE), 
	"PIS" CHAR(4 BYTE), 
	"PORTA" CHAR(4 BYTE), 
	"BLOC" CHAR(4 BYTE), 
	"CODI_TIPUS_VIA" CHAR(4 BYTE), 
	"CODI_BARRI" CHAR(4 BYTE), 
	"BARRI" CHAR(4 BYTE), 
	"CODI_DISTRICTE" CHAR(4 BYTE), 
	"DISTRICTE" CHAR(4 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "T_SINTAGMA" ;
