--------------------------------------------------------
--  DDL for Table Z_D99_SUBJECTES
--------------------------------------------------------

  CREATE TABLE "SINTAGMA_U"."Z_D99_SUBJECTES" 
   (	"ID" NUMBER, 
	"NOM" VARCHAR2(50 BYTE), 
	"COGNOM1" VARCHAR2(40 BYTE), 
	"COGNOM2" VARCHAR2(200 BYTE), 
	"ALIES" CHAR(4 BYTE), 
	"DATA_DEFUNCIO" CHAR(4 BYTE), 
	"ES_PROVISIONAL" NUMBER, 
	"NOM_NORMALITZAT" VARCHAR2(60 BYTE), 
	"MOTIU_BAIXA" CHAR(4 BYTE), 
	"DATA_CREACIO" DATE, 
	"DATA_ESBORRAT" CHAR(4 BYTE), 
	"DATA_MODIFICACIO" DATE, 
	"USUARI_CREACIO" CHAR(8 BYTE), 
	"USUARI_ESBORRAT" CHAR(4 BYTE), 
	"USUARI_MODIFICACIO" VARCHAR2(25 BYTE), 
	"TRACTAMENT_ID" NUMBER, 
	"PRIORITAT_ID" NUMBER, 
	"TIPUS_SUBJECTE_ID" NUMBER, 
	"AMBIT_ID" NUMBER, 
	"IDIOMA_ID" CHAR(4 BYTE), 
	"ARTICLE_ID" NUMBER, 
	"ID_ORIGINAL" VARCHAR2(30 BYTE), 
	"ESQUEMA_ORIGINAL" VARCHAR2(30 BYTE), 
	"TABLA_ORIGINAL" VARCHAR2(30 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "T_SINTAGMA" ;
