--------------------------------------------------------
--  DDL for Table Z_E002_INSTALACIO_AMBIT_PART
--------------------------------------------------------

  CREATE TABLE "SINTAGMA_U"."Z_E002_INSTALACIO_AMBIT_PART" 
   (	"INSTALACIOID" NUMBER(38,0), 
	"DESCRIPCIO" VARCHAR2(512 BYTE), 
	"NOM" VARCHAR2(100 BYTE), 
	"DATACREACIO" DATE, 
	"AMBIT_ID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "T_SINTAGMA" ;
