--------------------------------------------------------
--  DDL for Table Z_E163_ACCIONS_PART3
--------------------------------------------------------

  CREATE TABLE "SINTAGMA_U"."Z_E163_ACCIONS_PART3" 
   (	"ACCION_ID" NUMBER(38,0), 
	"RESPOSTA" VARCHAR2(4000 BYTE), 
	"ES_NECESSITA_RESPOSTA" CHAR(1 BYTE), 
	"NOM_USUARI_ACCIO" VARCHAR2(201 BYTE), 
	"MATRICULA_USUARI_ACCIO" VARCHAR2(25 BYTE), 
	"DATA_CREACIO" DATE, 
	"DATA_MODIFICACIO" TIMESTAMP (9), 
	"DATA_ESBORRAT" TIMESTAMP (9), 
	"USUARI_CREACIO" VARCHAR2(4000 BYTE), 
	"USUARI_MODIFICACIO" VARCHAR2(4000 BYTE), 
	"USUARI_ESBORRAT" VARCHAR2(4000 BYTE), 
	"SUBTIPUS_ACCIO_ID" NUMBER(38,0), 
	"ASPECTE_ID" NUMBER(38,0), 
	"ELEMENT_PRINCIPAL_ID" NUMBER, 
	"AMBIT_ORIGEN_ID" NUMBER(38,0), 
	"PAS_ACCIO_ID" NUMBER, 
	"ID_ORIGINAL" VARCHAR2(30 BYTE), 
	"ESQUEMA_ORIGINAL" VARCHAR2(30 BYTE), 
	"TABLA_ORIGINAL" VARCHAR2(30 BYTE), 
	"INSTALACIOID" VARCHAR2(30 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "T_SINTAGMA" ;
