--------------------------------------------------------
--  DDL for Table Z_SB999_ADRECA
--------------------------------------------------------

  CREATE TABLE "SINTAGMA_U"."Z_SB999_ADRECA" 
   (	"ID" NUMBER(*,0), 
	"NOM_CARRER" VARCHAR2(4000 BYTE), 
	"MUNICIPI" VARCHAR2(30 BYTE), 
	"PROVINCIA" VARCHAR2(30 BYTE), 
	"CODI_POSTAL" VARCHAR2(10 BYTE), 
	"PAIS" VARCHAR2(30 BYTE), 
	"USUARI_CREACIO" VARCHAR2(4000 BYTE), 
	"DATA_CREACIO" DATE, 
	"USUARI_MODIFICACIO" VARCHAR2(10 BYTE), 
	"DATA_MODIFICACIO" DATE, 
	"ID_ORIGINAL" CHAR(9 BYTE), 
	"ESQUEMA_ORIGINAL" CHAR(6 BYTE), 
	"TABLA_ORIGINAL" VARCHAR2(11 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "T_SINTAGMA" ;
