--------------------------------------------------------
--  DDL for Table Z_SB110_TELEFON
--------------------------------------------------------

  CREATE TABLE "SINTAGMA_U"."Z_SB110_TELEFON" 
   (	"ID_CONTACTE" NUMBER(*,0), 
	"N_VIP" NUMBER(10,0), 
	"TIPUS_TELEFON" NUMBER, 
	"TELEFON" VARCHAR2(4000 BYTE), 
	"ES_PRINCIPAL" NUMBER, 
	"CONCEPTE" VARCHAR2(4000 BYTE), 
	"ES_PARTICULAR" NUMBER, 
	"ID_ORIGINAL" NUMBER(10,0), 
	"ESQUEMA_ORIGINAL" CHAR(6 BYTE), 
	"TABLA_ORIGINAL" CHAR(30 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "T_SINTAGMA" ;
