--------------------------------------------------------
--  DDL for Table Z_SB140_ACOMPANYANTS_VIPS
--------------------------------------------------------

  CREATE TABLE "SINTAGMA_U"."Z_SB140_ACOMPANYANTS_VIPS" 
   (	"SUBJECTE_ID" NUMBER(10,0), 
	"NOM" VARCHAR2(15 BYTE), 
	"COGNOM1" VARCHAR2(35 BYTE), 
	"COGNOM2" VARCHAR2(35 BYTE), 
	"DATA_CREACIO" DATE, 
	"DATA_ESBORRAT" DATE, 
	"DATA_MODIFICACIO" DATE, 
	"USUARI_CREACIO" VARCHAR2(4000 BYTE), 
	"USUARI_ESBORRAT" VARCHAR2(4000 BYTE), 
	"USUARI_MODIFICACIO" VARCHAR2(10 BYTE), 
	"TRACTAMENT_ID" NUMBER, 
	"CONTACTE_ID" NUMBER(10,0), 
	"ID_ORIGINAL" NUMBER(10,0), 
	"ESQUEMA_ORIGINAL" CHAR(6 BYTE), 
	"TABLA_ORIGINAL" CHAR(4 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "T_SINTAGMA" ;
