--------------------------------------------------------
--  DDL for Table Z_SB060_ENTITAT_CATALOG
--------------------------------------------------------

  CREATE TABLE "SINTAGMA_U"."Z_SB060_ENTITAT_CATALOG" 
   (	"ID" NUMBER(*,0), 
	"CODI" VARCHAR2(5 BYTE), 
	"ENTITAT" VARCHAR2(100 BYTE), 
	"ENTITAT_NORM" VARCHAR2(4000 BYTE), 
	"ID_ORIGINAL" VARCHAR2(5 BYTE), 
	"ESQUEMA_ORIGINAL" CHAR(6 BYTE), 
	"TABLA_ORIGINAL" CHAR(7 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "T_SINTAGMA" ;
