--------------------------------------------------------
--  DDL for Table Z_SB120_CLASSIFICACIONS
--------------------------------------------------------

  CREATE TABLE "SINTAGMA_U"."Z_SB120_CLASSIFICACIONS" 
   (	"ID" NUMBER(*,0), 
	"CODI" VARCHAR2(5 BYTE), 
	"DESCRIPCIO" VARCHAR2(60 BYTE), 
	"ORDEN" NUMBER(2,0), 
	"ID_ORIGINAL" VARCHAR2(5 BYTE), 
	"ESQUEMA_ORIGINAL" CHAR(6 BYTE), 
	"TABLA_ORIGINAL" CHAR(15 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "T_SINTAGMA" ;
