--------------------------------------------------------
--  DDL for Table Z_SB130_CLASSIF_CONTACTE
--------------------------------------------------------

  CREATE TABLE "SINTAGMA_U"."Z_SB130_CLASSIF_CONTACTE" 
   (	"CONTACTE_ID" NUMBER(*,0), 
	"CLASSIFICACIO_CODI" VARCHAR2(5 BYTE), 
	"PRELACIO" NUMBER(4,0), 
	"ID_CLASSIFICACIO" NUMBER(10,0), 
	"DATA_CREACIO" DATE, 
	"USUARI_CREACIO" VARCHAR2(4000 BYTE), 
	"USUARI_MODIFICACIO" VARCHAR2(10 BYTE), 
	"DATA_MODIFICACIO" DATE, 
	"ID_ORIGINAL" NUMBER(10,0), 
	"ESQUEMA_ORIGINAL" CHAR(6 BYTE), 
	"TABLA_ORIGINAL" CHAR(12 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "T_SINTAGMA" ;
