--------------------------------------------------------
--  DDL for Table Z_SC096_TRUCADAS_HISTORIC
--------------------------------------------------------

  CREATE TABLE "SINTAGMA_U"."Z_SC096_TRUCADAS_HISTORIC" 
   (	"ID" NUMBER(*,0), 
	"DATA_REGISTRE" DATE, 
	"DATA_RESOLUCIO" DATE, 
	"NOM" VARCHAR2(30 BYTE), 
	"COGNOM1" VARCHAR2(100 BYTE), 
	"COGNOM2" VARCHAR2(40 BYTE), 
	"CARREC" VARCHAR2(100 BYTE), 
	"TELEFON" VARCHAR2(4000 BYTE), 
	"TELEFON_SECUNDARI" VARCHAR2(4000 BYTE), 
	"DESCRIPCIO" VARCHAR2(100 BYTE), 
	"DATA_CREACIO" DATE, 
	"DATA_ESBORRAT" DATE, 
	"DATA_MODIFICACIO" DATE, 
	"USUARI_CREACIO" CHAR(8 BYTE), 
	"USUARI_ESBORRAT" VARCHAR2(4000 BYTE), 
	"USUARI_MODIFICACIO" VARCHAR2(4000 BYTE), 
	"ENTITAT_ID" NUMBER, 
	"ESTAT_TRUCADA_ID" NUMBER, 
	"DESTINATARI_PERSONA_ID" NUMBER, 
	"CONTACTE_ID" VARCHAR2(4000 BYTE), 
	"SENTIT_ID" NUMBER, 
	"ID_ORIGINAL" VARCHAR2(100 BYTE), 
	"ESQUEMA_ORIGINAL" CHAR(6 BYTE), 
	"TABLA_ORIGINAL" CHAR(12 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "T_SINTAGMA" ;
