--------------------------------------------------------
--  DDL for Table Z_SC071_TELEFON_MOBIL
--------------------------------------------------------

  CREATE TABLE "SINTAGMA_U"."Z_SC071_TELEFON_MOBIL" 
   (	"ID_CONTACTE" VARCHAR2(100 BYTE), 
	"TIPUS_TELEFON" NUMBER, 
	"TELEFON" VARCHAR2(4000 BYTE), 
	"ES_PRINCIPAL" NUMBER, 
	"CONCEPTE" VARCHAR2(4000 BYTE), 
	"ES_PARTICULAR" NUMBER, 
	"ES_PRIVAT" NUMBER, 
	"ID_ORIGINAL" VARCHAR2(100 BYTE), 
	"ESQUEMA_ORIGINAL" CHAR(6 BYTE), 
	"TABLA_ORIGINAL" CHAR(32 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "T_SINTAGMA" ;
