--------------------------------------------------------
--  DDL for Table Z_SD040_ADRECAS_UNICAS
--------------------------------------------------------

  CREATE TABLE "SINTAGMA_U"."Z_SD040_ADRECAS_UNICAS" 
   (	"ID_ADRECA" NUMBER(*,0), 
	"NOM_ADRECA" VARCHAR2(250 BYTE), 
	"MUNICIPI" VARCHAR2(100 BYTE), 
	"CODIPOSTAL" VARCHAR2(10 BYTE), 
	"PROVINCIA" VARCHAR2(100 BYTE), 
	"PAIS" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "T_SINTAGMA" ;
