--------------------------------------------------------
--  DDL for Table Z_SD999_SUBJECTES
--------------------------------------------------------

  CREATE TABLE "SINTAGMA_U"."Z_SD999_SUBJECTES" 
   (	"ID" NUMBER(*,0), 
	"NOM" VARCHAR2(50 BYTE), 
	"COGNOM1" VARCHAR2(40 BYTE), 
	"COGNOM2" VARCHAR2(4000 BYTE), 
	"ALIES" VARCHAR2(4000 BYTE), 
	"DATA_DEFUNCIO" VARCHAR2(4000 BYTE), 
	"ES_PROVISIONAL" NUMBER, 
	"NOM_NORMALITZAT" VARCHAR2(60 BYTE), 
	"MOTIU_BAIXA" VARCHAR2(4000 BYTE), 
	"DATA_CREACIO" DATE, 
	"DATA_ESBORRAT" DATE, 
	"DATA_MODIFICACIO" DATE, 
	"USUARI_CREACIO" VARCHAR2(4000 BYTE), 
	"USUARI_ESBORRAT" VARCHAR2(4000 BYTE), 
	"USUARI_MODIFICACIO" VARCHAR2(25 BYTE), 
	"TRACTAMENT_ID" NUMBER, 
	"PRIORITAT_ID" NUMBER, 
	"TIPUS_SUBJECTE_ID" NUMBER, 
	"AMBIT_ID" NUMBER, 
	"IDIOMA_ID" VARCHAR2(4000 BYTE), 
	"ARTICLE_ID" VARCHAR2(4000 BYTE), 
	"ID_ORIGINAL" VARCHAR2(4000 BYTE), 
	"ESQUEMA_ORIGINAL" CHAR(7 BYTE), 
	"TABLA_ORIGINAL" CHAR(9 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "T_SINTAGMA" ;
