--------------------------------------------------------
--  DDL for Table Z_SE151_RELAC_ELEMENT_PPAL_SEC
--------------------------------------------------------

  CREATE TABLE "SINTAGMA_U"."Z_SE151_RELAC_ELEMENT_PPAL_SEC" 
   (	"ELEMENT_SEC_ID" NUMBER(38,0), 
	"ELEMENT_PPAL_ID" NUMBER(38,0), 
	"TIPUSELEMENTPRINCIPALID" NUMBER(38,0), 
	"TIPUSTEMAELEMENTPRINCIPALID" NUMBER(38,0), 
	"DATADOCUMENT" DATE, 
	"RESPONSABLEID" NUMBER(38,0), 
	"PRIORITATID" NUMBER(38,0), 
	"DATATERMINI" DATE, 
	"SEGUIMENTDESDE" DATE, 
	"SEGUIMENTFINS" DATE, 
	"DATARESOLUCIO" DATE, 
	"RESPINTERESSAT" DATE, 
	"DOSSIERID" NUMBER(38,0), 
	"TEXTGEOLOC" VARCHAR2(2000 BYTE), 
	"ID_ORIGINAL" NUMBER(38,0), 
	"ESQUEMA_ORIGINAL" CHAR(7 BYTE), 
	"TABLA_ORIGINAL" CHAR(17 BYTE), 
	"INSTALACIOID" NUMBER(38,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "T_SINTAGMA" ;
