--------------------------------------------------------
--  DDL for Table Z_SE110_ASPECTE_ACCIO
--------------------------------------------------------

  CREATE TABLE "SINTAGMA_U"."Z_SE110_ASPECTE_ACCIO" 
   (	"ID" NUMBER(*,0), 
	"DESCRIPCIO" VARCHAR2(4000 BYTE), 
	"DATA_ASSENTAMENT" DATE, 
	"USUARI_ASSENTAMENT" VARCHAR2(4000 BYTE), 
	"DATA_CREACIO" DATE, 
	"DATA_MODIFICACIO" TIMESTAMP (9), 
	"DATA_ESBORRAT" TIMESTAMP (9), 
	"USUARI_CREACIO" VARCHAR2(4000 BYTE), 
	"USUARI_MODIFICACIO" VARCHAR2(4000 BYTE), 
	"USUARI_ESBORRAT" VARCHAR2(4000 BYTE), 
	"TIPUS_TEMA_ID" NUMBER, 
	"AMBIT_ID" NUMBER, 
	"ID_ORIGINAL" NUMBER(38,0), 
	"ESQUEMA_ORIGINAL" CHAR(7 BYTE), 
	"TABLA_ORIGINAL" CHAR(15 BYTE), 
	"INSTALACIOID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "T_SINTAGMA" ;
