--------------------------------------------------------
--  DDL for Table Z_SG997_ASPECTES
--------------------------------------------------------

  CREATE TABLE "SINTAGMA_U"."Z_SG997_ASPECTES" 
   (	"ID" NUMBER, 
	"DESCRIPCIO" VARCHAR2(4000 BYTE), 
	"DATA_ASSENTAMENT" DATE, 
	"USUARI_ASSENTAMENT" VARCHAR2(4000 BYTE), 
	"DATA_CREACIO" DATE, 
	"DATA_MODIFICACIO" DATE, 
	"DATA_ESBORRAT" DATE, 
	"USUARI_CREACIO" VARCHAR2(4000 BYTE), 
	"USUARI_MODIFICACIO" VARCHAR2(4000 BYTE), 
	"USUARI_ESBORRAT" VARCHAR2(4000 BYTE), 
	"TIPUS_TEMA_ID" NUMBER, 
	"AMBIT_ID" NUMBER, 
	"ID_ORIGINAL" NUMBER, 
	"ESQUEMA_ORIGINAL" CHAR(4 BYTE), 
	"TABLA_ORIGINAL" CHAR(5 BYTE), 
	"INSTALACIOID" CHAR(1 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "T_SINTAGMA" ;
