--------------------------------------------------------
--  DDL for Table Z_SG010_ENTITAT_SIAP
--------------------------------------------------------

  CREATE TABLE "SINTAGMA_U"."Z_SG010_ENTITAT_SIAP" 
   (	"ID" NUMBER, 
	"CODI" VARCHAR2(5 BYTE), 
	"ENTITAT" VARCHAR2(255 BYTE), 
	"ENTITAT_NORM" VARCHAR2(4000 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "T_SINTAGMA" ;
