--------------------------------------------------------
--  DDL for Table Z_SG116_CONVIDAT_PASO2
--------------------------------------------------------

  CREATE TABLE "SINTAGMA_U"."Z_SG116_CONVIDAT_PASO2" 
   (	"NOM" VARCHAR2(50 BYTE), 
	"COGNOM1" VARCHAR2(50 BYTE), 
	"COGNOM2" VARCHAR2(50 BYTE), 
	"NOM_NORMALITZAT" VARCHAR2(4000 BYTE), 
	"CODI_CLASSIFICACIO" VARCHAR2(50 BYTE), 
	"CONTACTE_ID" NUMBER(10,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "T_SINTAGMA" ;
