--------------------------------------------------------
--  DDL for Table Z_SG001_YA_EXISTS_CLASIFFICAC
--------------------------------------------------------

  CREATE TABLE "SINTAGMA_U"."Z_SG001_YA_EXISTS_CLASIFFICAC" 
   (	"ID_SINTAGMA" NUMBER(10,0), 
	"ID_SIAP" NUMBER, 
	"DM_CODI" VARCHAR2(20 BYTE), 
	"DM_DESCRIPCIO" VARCHAR2(60 BYTE), 
	"SIAP_CODI" VARCHAR2(5 BYTE), 
	"SIAP_CLASSIFICACIO" VARCHAR2(255 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "T_SINTAGMA" ;
