--------------------------------------------------------
--  DDL for Table Z_T_RP_ANNEXOS
--------------------------------------------------------

  CREATE TABLE "SINTAGMA_U"."Z_T_RP_ANNEXOS" 
   (	"INSTALACIOID" NUMBER(38,0), 
	"ANNEXID" NUMBER(38,0), 
	"TIPUSANNEXID" NUMBER(38,0), 
	"NOMFITXER" VARCHAR2(512 BYTE), 
	"COMENTARI" VARCHAR2(4000 BYTE), 
	"ESPREFERENT" CHAR(1 BYTE), 
	"USUARIID" NUMBER(38,0), 
	"DATACREACIO" DATE, 
	"ESGENERAT" CHAR(1 BYTE), 
	"ESPRIVAT" CHAR(1 BYTE), 
	"ASPECTEID" NUMBER(38,0), 
	"ENTITATDOCUMENTUMID" VARCHAR2(64 BYTE), 
	"FITXAAGENDAID" NUMBER(38,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "T_SINTAGMA" ;
