--------------------------------------------------------
--  DDL for Table Z_T_RC_NUM_DOCS
--------------------------------------------------------

  CREATE TABLE "SINTAGMA_U"."Z_T_RC_NUM_DOCS" 
   (	"ID_RIS" VARCHAR2(10 BYTE), 
	"NUMERO" NUMBER(8,0), 
	"USUARI" VARCHAR2(10 BYTE), 
	"DATA_B" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "T_SINTAGMA" ;
