--------------------------------------------------------
--  DDL for Table Z_T_SIAP_SERVEIS
--------------------------------------------------------

  CREATE TABLE "SINTAGMA_U"."Z_T_SIAP_SERVEIS" 
   (	"ID" NUMBER, 
	"SERVEI" VARCHAR2(255 BYTE), 
	"IDPROV" NUMBER, 
	"PROV" VARCHAR2(255 BYTE), 
	"COST" VARCHAR2(255 BYTE), 
	"IDAGRUPACIO" NUMBER, 
	"AGRUPACIO" VARCHAR2(255 BYTE), 
	"ORDRE" NUMBER, 
	"FORMULARI" VARCHAR2(4000 BYTE), 
	"IVA" NUMBER(15,2), 
	"IDIMP_PROTOCOL" NUMBER, 
	"IMP_PROTOCOL" VARCHAR2(20 BYTE), 
	"OBSOLET" VARCHAR2(1 BYTE), 
	"COST_PREVIST" NUMBER(15,2)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "T_SINTAGMA" ;
