--------------------------------------------------------
--  DDL for Table Z_T_SIAP_COSTOS_ANNEXOS
--------------------------------------------------------

  CREATE TABLE "SINTAGMA_U"."Z_T_SIAP_COSTOS_ANNEXOS" 
   (	"ID" NUMBER(*,0), 
	"DESCRIPCIO" VARCHAR2(150 BYTE), 
	"NOMFITXER" VARCHAR2(150 BYTE), 
	"DATA_ALTA" DATE, 
	"IDREGISTRE" NUMBER(*,0), 
	"ORIGEN" NUMBER
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "T_SINTAGMA" ;
