--------------------------------------------------------
--  DDL for Table Z_T_RP_ELEMENTSPRINCIPALGEO
--------------------------------------------------------

  CREATE TABLE "SINTAGMA_U"."Z_T_RP_ELEMENTSPRINCIPALGEO" 
   (	"ELEMENTPRINCIPALGEOID" NUMBER(38,0), 
	"ASPECTEID" NUMBER(38,0), 
	"TIPUS" VARCHAR2(2 BYTE), 
	"CARRER1" VARCHAR2(6 BYTE), 
	"NUMPOST1" VARCHAR2(5 BYTE), 
	"NUMPOST2" VARCHAR2(5 BYTE), 
	"CARRER2" VARCHAR2(6 BYTE), 
	"CARRER3" VARCHAR2(6 BYTE), 
	"DISTRICTE" VARCHAR2(2 BYTE), 
	"BARRI" VARCHAR2(2 BYTE), 
	"XMIN" NUMBER(8,0), 
	"XMAX" NUMBER(8,0), 
	"YMIN" NUMBER(8,0), 
	"YMAX" NUMBER(8,0), 
	"TEXT" VARCHAR2(100 BYTE), 
	"XCEN" NUMBER(8,0), 
	"YCEN" NUMBER(8,0)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "T_SINTAGMA" ;
