--------------------------------------------------------
--  DDL for Table Z_T_RP_USUARISACCIONSDEFECTE
--------------------------------------------------------

  CREATE TABLE "SINTAGMA_U"."Z_T_RP_USUARISACCIONSDEFECTE" 
   (	"USUARIACCIODEFECTEID" NUMBER(38,0), 
	"TIPUSACCIOID" NUMBER(38,0), 
	"USUARIID" NUMBER(38,0), 
	"INSTALACIOID" NUMBER(38,0)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "T_SINTAGMA" ;
