--------------------------------------------------------
--  DDL for Table Z_T_SIAP_DESPESES
--------------------------------------------------------

  CREATE TABLE "SINTAGMA_U"."Z_T_SIAP_DESPESES" 
   (	"ID" NUMBER, 
	"IDACTE" NUMBER, 
	"IDSERVEI" NUMBER, 
	"SERVEI" VARCHAR2(255 BYTE), 
	"DESCRIPCIO_ANTIGA" VARCHAR2(4000 BYTE), 
	"IDPROV" NUMBER, 
	"PROV" VARCHAR2(255 BYTE), 
	"CORREU" VARCHAR2(255 BYTE), 
	"IDIMP_PROTOCOL" NUMBER, 
	"IMP_PROTOCOL" VARCHAR2(20 BYTE), 
	"QUI_HO_PAGA" VARCHAR2(255 BYTE), 
	"COST_PREVIST" NUMBER(15,2), 
	"D_FACTURA" DATE, 
	"FACTURA" VARCHAR2(255 BYTE), 
	"COST_REAL" NUMBER(15,2), 
	"IDPROGRAMA" NUMBER, 
	"PROGRAMA" VARCHAR2(255 BYTE), 
	"IDPARTIDA" NUMBER, 
	"PARTIDA" VARCHAR2(255 BYTE), 
	"IDAMBITDESPESA" NUMBER, 
	"AMBITDESPESA" VARCHAR2(255 BYTE), 
	"IDAGRUPACIO" NUMBER, 
	"AGRUPACIO" VARCHAR2(255 BYTE), 
	"IDGRUP" NUMBER, 
	"GRUP" VARCHAR2(255 BYTE), 
	"CONTRACTE" VARCHAR2(255 BYTE), 
	"DESCRIPCIO" CLOB
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "T_SINTAGMA" 
 LOB ("DESCRIPCIO") STORE AS BASICFILE (
  TABLESPACE "T_SINTAGMA" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
