--------------------------------------------------------
--  DDL for Table Z_T_RP_ENVIAMENTSANNEXOS
--------------------------------------------------------

  CREATE TABLE "SINTAGMA_U"."Z_T_RP_ENVIAMENTSANNEXOS" 
   (	"ENVIAMENTANNEXOSID" NUMBER(38,0), 
	"DATA" DATE, 
	"ANNEXID" NUMBER(38,0), 
	"ADRECACORREUID" NUMBER(38,0)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "T_SINTAGMA" ;
