--------------------------------------------------------
--  DDL for Table Z_T_SIAP_GRUPS
--------------------------------------------------------

  CREATE TABLE "SINTAGMA_U"."Z_T_SIAP_GRUPS" 
   (	"ID" NUMBER, 
	"GRUP" VARCHAR2(255 BYTE), 
	"IDECONOMIC" NUMBER, 
	"ECONOMIC" VARCHAR2(255 BYTE), 
	"CONTRACTE" VARCHAR2(255 BYTE), 
	"CONCEPTE_PROVEIDOR" VARCHAR2(255 BYTE), 
	"CREDIT_INICIAL" NUMBER(15,2), 
	"OBSOLET" VARCHAR2(1 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "T_SINTAGMA" ;
