--------------------------------------------------------
--  DDL for Table Z_T_SIAP_COSTOS_CAIXA
--------------------------------------------------------

  CREATE TABLE "SINTAGMA_U"."Z_T_SIAP_COSTOS_CAIXA" 
   (	"ID" NUMBER, 
	"DATA" DATE, 
	"B_500" NUMBER, 
	"B_200" NUMBER, 
	"B_100" NUMBER, 
	"B_50" NUMBER, 
	"B_20" NUMBER, 
	"B_10" NUMBER, 
	"B_5" NUMBER, 
	"M_2" NUMBER, 
	"M_1" NUMBER, 
	"M_050" NUMBER, 
	"M_020" NUMBER, 
	"M_010" NUMBER, 
	"M_005" NUMBER, 
	"M_002" NUMBER, 
	"M_001" NUMBER, 
	"OBSOLET" VARCHAR2(1 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "T_SINTAGMA" ;
