--------------------------------------------------------
--  DDL for Table Z_T_SIAP_COSTOS_OAS
--------------------------------------------------------

  CREATE TABLE "SINTAGMA_U"."Z_T_SIAP_COSTOS_OAS" 
   (	"ID" NUMBER, 
	"DATA" DATE, 
	"REFDOC" VARCHAR2(50 BYTE), 
	"RECEPTOR" VARCHAR2(255 BYTE), 
	"REFERENT" VARCHAR2(255 BYTE), 
	"CONCEPTE" VARCHAR2(255 BYTE), 
	"IMPORT" NUMBER(15,2), 
	"JUSTIFICAT" VARCHAR2(1 BYTE), 
	"NIF_CREDITOR" VARCHAR2(255 BYTE), 
	"NOMCOMERCIAL_CREDITOR" VARCHAR2(255 BYTE), 
	"NOM_CREDITOR" VARCHAR2(255 BYTE), 
	"ANY_PRESSUPOSTARI" VARCHAR2(4 BYTE), 
	"CODI_ECONOMIC" VARCHAR2(10 BYTE), 
	"CODI_FUNCIONAL" VARCHAR2(10 BYTE), 
	"CODI_ORGANIC" VARCHAR2(10 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "T_SINTAGMA" ;
