--------------------------------------------------------
--  DDL for Table Z_T_SIAP_ACTES
--------------------------------------------------------

  CREATE TABLE "SINTAGMA_U"."Z_T_SIAP_ACTES" 
   (	"ID" NUMBER, 
	"DESCRIPCIO" VARCHAR2(255 BYTE), 
	"IDTIPUS_ACTE" NUMBER, 
	"TIPUS_ACTE" VARCHAR2(255 BYTE), 
	"DATA_INICI" DATE, 
	"HORA_INICI" VARCHAR2(255 BYTE), 
	"DATA_FINAL" DATE, 
	"IDTECNIC" NUMBER, 
	"TECNIC" VARCHAR2(255 BYTE), 
	"IDPETICIONARI" NUMBER, 
	"PETICIONARI" VARCHAR2(255 BYTE), 
	"IDLLOC" NUMBER, 
	"LLOC" VARCHAR2(255 BYTE), 
	"IDLLOC2" NUMBER, 
	"LLOC2" VARCHAR2(255 BYTE), 
	"GRUPS" VARCHAR2(255 BYTE), 
	"ESTAT" VARCHAR2(255 BYTE), 
	"OBSERVACIONS" VARCHAR2(4000 BYTE), 
	"IDPRESIDENT" NUMBER, 
	"PRESIDENT" VARCHAR2(255 BYTE), 
	"IDSECTOR" NUMBER, 
	"SECTOR" VARCHAR2(255 BYTE), 
	"IDGERENCIA" NUMBER, 
	"GERENCIA" VARCHAR2(255 BYTE), 
	"IDCARREC" NUMBER, 
	"CARREC" VARCHAR2(255 BYTE), 
	"PREFIXREGISTRE" VARCHAR2(4 BYTE), 
	"IDREGISTRE" NUMBER, 
	"IDCATEGORIA" NUMBER, 
	"CATEGORIA" VARCHAR2(255 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "T_SINTAGMA" ;
