--------------------------------------------------------
--  DDL for Table Z_T_RC_TEMES_CONVENIS
--------------------------------------------------------

  CREATE TABLE "SINTAGMA_U"."Z_T_RC_TEMES_CONVENIS" 
   (	"NUM_REG" VARCHAR2(14 BYTE), 
	"CODI_ORG_GESTOR" VARCHAR2(8 BYTE), 
	"ORG_GESTOR" VARCHAR2(30 BYTE), 
	"OBJECTE_CONVENI" VARCHAR2(60 BYTE), 
	"DATA_SIGNATURA" DATE, 
	"IMPORT" NUMBER(24,2), 
	"NUM_EXPEDIENT" VARCHAR2(15 BYTE), 
	"DATA_INICI" DATE, 
	"I_SIGNATARI_COGNOMS" VARCHAR2(28 BYTE), 
	"I_SIGNATARI_NOM" VARCHAR2(10 BYTE), 
	"II_SIGNATARI_COGNOMS" VARCHAR2(28 BYTE), 
	"II_SIGNATARI1_NOM" VARCHAR2(10 BYTE), 
	"SIGNAT" VARCHAR2(60 BYTE), 
	"NOTES" VARCHAR2(30 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "T_SINTAGMA" ;
