--------------------------------------------------------
--  DDL for Table Z_T_RP_USUARIS
--------------------------------------------------------

  CREATE TABLE "SINTAGMA_U"."Z_T_RP_USUARIS" 
   (	"USUARIID" NUMBER(38,0), 
	"INSTALACIOID" NUMBER(38,0), 
	"ADRECACORREU" VARCHAR2(100 BYTE), 
	"USUARI" VARCHAR2(25 BYTE), 
	"NOM" VARCHAR2(50 BYTE), 
	"COGNOMS" VARCHAR2(150 BYTE), 
	"CARREC" VARCHAR2(50 BYTE), 
	"DEPARTAMENT" VARCHAR2(50 BYTE), 
	"ESTAACTIU" CHAR(1 BYTE), 
	"ULTIMAENTRADA" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "T_SINTAGMA" ;
