--------------------------------------------------------
--  DDL for Table Z_T_RC_PASSOS_R
--------------------------------------------------------

  CREATE TABLE "SINTAGMA_U"."Z_T_RC_PASSOS_R" 
   (	"ID_RIS" VARCHAR2(1000 BYTE), 
	"N_TEMA" VARCHAR2(14 BYTE), 
	"CODI_PAS" VARCHAR2(4 BYTE), 
	"DESCRIPCIO" VARCHAR2(60 BYTE), 
	"DATA_INICI" DATE, 
	"DATA_FI" DATE, 
	"DURACIO_REAL" NUMBER(4,0), 
	"DATA_ESPERADA" DATE, 
	"DURACIO_ESPERADA" NUMBER(4,0), 
	"IMPORT_PAS" VARCHAR2(22 BYTE), 
	"DATA_MODI" DATE, 
	"USU_MODI" VARCHAR2(10 BYTE), 
	"DATA_ALTA" DATE, 
	"USU_ALTA" VARCHAR2(10 BYTE), 
	"ESTAT" VARCHAR2(3 BYTE), 
	"PRIORITAT" NUMBER(4,0), 
	"R_COGNOMS" VARCHAR2(28 BYTE), 
	"R_NOM" VARCHAR2(10 BYTE), 
	"R_F_J" VARCHAR2(1 BYTE), 
	"R_DNI" VARCHAR2(10 BYTE), 
	"R_TELEFON" VARCHAR2(12 BYTE), 
	"R_CODI_AMBIT" VARCHAR2(4 BYTE), 
	"R_AMBIT" VARCHAR2(60 BYTE), 
	"R_CODI_AREA" VARCHAR2(2 BYTE), 
	"R_AREA" VARCHAR2(60 BYTE), 
	"R_CODI_DEPT" VARCHAR2(7 BYTE), 
	"R_DEPT" VARCHAR2(65 BYTE), 
	"R_CARREC" VARCHAR2(30 BYTE), 
	"R_CODI_CARRER" NUMBER(8,0), 
	"R_TIPUS_CARRER" VARCHAR2(4 BYTE), 
	"R_CARRER" VARCHAR2(27 BYTE), 
	"R_NUM1" NUMBER(8,0), 
	"R_LLETRA1" VARCHAR2(1 BYTE), 
	"R_NUM2" NUMBER(8,0), 
	"R_LLETRA2" VARCHAR2(1 BYTE), 
	"R_LOCALITZACIO" VARCHAR2(1 BYTE), 
	"R_PORTAL" VARCHAR2(1 BYTE), 
	"R_ESCALA" VARCHAR2(1 BYTE), 
	"R_PIS" VARCHAR2(2 BYTE), 
	"R_PORTA" VARCHAR2(2 BYTE), 
	"R_APARTAMENT" NUMBER(8,0), 
	"R_MUNICIPI" VARCHAR2(20 BYTE), 
	"R_PROVINCIA" VARCHAR2(16 BYTE), 
	"R_PAIS" VARCHAR2(16 BYTE), 
	"R_CODI_POSTAL" VARCHAR2(5 BYTE), 
	"N_PAS" NUMBER(8,0), 
	"RESPONSABLE" VARCHAR2(15 BYTE), 
	"REFREG" VARCHAR2(10 BYTE), 
	"REFDOC" VARCHAR2(10 BYTE), 
	"MOTIU" VARCHAR2(60 BYTE), 
	"OBSERVACIONS" VARCHAR2(4000 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "T_SINTAGMA" ;
