--------------------------------------------------------
--  DDL for Table Z_T_RP_ARXIUS
--------------------------------------------------------

  CREATE TABLE "SINTAGMA_U"."Z_T_RP_ARXIUS" 
   (	"ARXIUID" NUMBER(38,0), 
	"ASPECTEID" NUMBER(38,0), 
	"DATATRANSFERENCIA" DATE, 
	"SUBSERIEID" NUMBER(38,0), 
	"UNIFORMEID" NUMBER(38,0), 
	"ESPECIFICID" NUMBER(38,0), 
	"COTAARXIUID" NUMBER(38,0), 
	"DESCRIPTORSTEMATICS" VARCHAR2(200 BYTE), 
	"DESCRIPTORSGEOGRAFICS" VARCHAR2(200 BYTE), 
	"ALTRESDESCRIPTORS" VARCHAR2(200 BYTE), 
	"CONSERVACIO" VARCHAR2(200 BYTE), 
	"TRANSFERENCIA" VARCHAR2(200 BYTE), 
	"DATAARXIU" DATE, 
	"PRESTATGE" VARCHAR2(200 BYTE), 
	"CAIXA" VARCHAR2(200 BYTE), 
	"SERIEID" NUMBER(38,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "T_SINTAGMA" ;
