--------------------------------------------------------
--  DDL for Table Z_T_RC_DOCUMENTS
--------------------------------------------------------

  CREATE TABLE "SINTAGMA_U"."Z_T_RC_DOCUMENTS" 
   (	"ID_RIS" VARCHAR2(10 BYTE), 
	"CODI_PAS" VARCHAR2(4 BYTE), 
	"DESCRIPCIO" VARCHAR2(40 BYTE), 
	"NOM_DOCUMENT" VARCHAR2(12 BYTE), 
	"COPIES" NUMBER(4,0), 
	"EDITABLE" VARCHAR2(1 BYTE), 
	"ARXIVABLE" VARCHAR2(1 BYTE), 
	"MACRO" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "T_SINTAGMA" ;
