--------------------------------------------------------
--  DDL for Table Z_TMP_VIPS_U_REGALS
--------------------------------------------------------

  CREATE TABLE "SINTAGMA_U"."Z_TMP_VIPS_U_REGALS" 
   (	"CODI" VARCHAR2(5 BYTE), 
	"DESCRIPCIO" VARCHAR2(60 BYTE), 
	"T_REGAL" VARCHAR2(5 BYTE), 
	"VALOR" NUMBER(10,0), 
	"STOCK" VARCHAR2(1 BYTE), 
	"PROVEIDOR" VARCHAR2(35 BYTE), 
	"ADRECA_PROV" VARCHAR2(35 BYTE), 
	"TELEF_PROV" VARCHAR2(14 BYTE), 
	"OBSERVACIONS" VARCHAR2(800 BYTE), 
	"EN_STOCK" NUMBER(7,0), 
	"ENTRADES" NUMBER(8,0), 
	"SORTIDES" NUMBER(8,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "T_SINTAGMA" ;
