--------------------------------------------------------
--  DDL for Table Z_TMP_VIPS_U_ES_REGAL
--------------------------------------------------------

  CREATE TABLE "SINTAGMA_U"."Z_TMP_VIPS_U_ES_REGAL" 
   (	"CODI" VARCHAR2(5 BYTE), 
	"N_ES_REGAL" NUMBER, 
	"TIPUS" VARCHAR2(1 BYTE), 
	"DATA" DATE, 
	"QUANTITAT" NUMBER(6,0), 
	"RESPONSABLE" VARCHAR2(100 BYTE), 
	"MOTIU" VARCHAR2(250 BYTE), 
	"USUARI_MOV" VARCHAR2(25 BYTE), 
	"DATA_MOV" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "T_SINTAGMA" ;
