--------------------------------------------------------
--  DDL for Table Z_TMP_VIPS_U_LLOCS
--------------------------------------------------------

  CREATE TABLE "SINTAGMA_U"."Z_TMP_VIPS_U_LLOCS" 
   (	"CODI" VARCHAR2(5 BYTE), 
	"DESCRIPCIO" VARCHAR2(40 BYTE), 
	"ADMIN" VARCHAR2(40 BYTE), 
	"ADRECA" VARCHAR2(40 BYTE), 
	"TELEFON" VARCHAR2(14 BYTE), 
	"FAX" VARCHAR2(14 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "T_SINTAGMA" ;
