--------------------------------------------------------
--  DDL for Table Z_TMP_VIPS_U_PLANT_DEFECTE
--------------------------------------------------------

  CREATE TABLE "SINTAGMA_U"."Z_TMP_VIPS_U_PLANT_DEFECTE" 
   (	"CODI" VARCHAR2(1 BYTE), 
	"NOM_PLANT1" VARCHAR2(12 BYTE), 
	"LIT_PLANT1" VARCHAR2(12 BYTE), 
	"EDITABLE1" VARCHAR2(1 BYTE), 
	"NOM_PLANT2" VARCHAR2(12 BYTE), 
	"LIT_PLANT2" VARCHAR2(12 BYTE), 
	"EDITABLE2" VARCHAR2(1 BYTE), 
	"NOM_PLANT3" VARCHAR2(12 BYTE), 
	"LIT_PLANT3" VARCHAR2(12 BYTE), 
	"EDITABLE3" VARCHAR2(1 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "T_SINTAGMA" ;
