--------------------------------------------------------
--  DDL for Table Z_TMP_VIPS_U_ORGA_ACTIVACIO
--------------------------------------------------------

  CREATE TABLE "SINTAGMA_U"."Z_TMP_VIPS_U_ORGA_ACTIVACIO" 
   (	"LLISTA" VARCHAR2(6 BYTE), 
	"ACTE" VARCHAR2(5 BYTE), 
	"AC2E" VARCHAR2(5 BYTE), 
	"CLASSIF" VARCHAR2(5 BYTE), 
	"DAT_ACT_TRA" DATE, 
	"USU_ACT_TRA" VARCHAR2(10 BYTE), 
	"DAT_ACT_AR" DATE, 
	"USU_ACT_AR" VARCHAR2(10 BYTE), 
	"DAT_ACT_CONF" DATE, 
	"USU_ACT_CONF" VARCHAR2(10 BYTE), 
	"DAT_ACT_ASS" DATE, 
	"USU_ACT_ASS" VARCHAR2(10 BYTE), 
	"LITERAL_CAMP1" VARCHAR2(10 BYTE), 
	"DAT_ACT_CAMP1" DATE, 
	"USU_ACT_CAMP1" VARCHAR2(10 BYTE), 
	"LITERAL_CAMP2" VARCHAR2(10 BYTE), 
	"DAT_ACT_CAMP2" DATE, 
	"USU_ACT_CAMP2" VARCHAR2(10 BYTE), 
	"LITERAL_CAMP3" VARCHAR2(10 BYTE), 
	"DAT_ACT_CAMP3" DATE, 
	"USU_ACT_CAMP3" VARCHAR2(10 BYTE), 
	"LITERAL_CAMP4" VARCHAR2(10 BYTE), 
	"DAT_ACT_CAMP4" DATE, 
	"USU_ACT_CAMP4" VARCHAR2(10 BYTE), 
	"EMPM" VARCHAR2(5 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "T_SINTAGMA" ;
