--------------------------------------------------------
--  DDL for Table Z_TMP_VIPS_U_ACTES
--------------------------------------------------------

  CREATE TABLE "SINTAGMA_U"."Z_TMP_VIPS_U_ACTES" 
   (	"CODI" VARCHAR2(5 BYTE), 
	"DESCRIPCIO" VARCHAR2(250 BYTE), 
	"T_ACTE" VARCHAR2(5 BYTE), 
	"DATA_INI" DATE, 
	"DATA_FI" DATE, 
	"HORA_INI" DATE, 
	"LLOC" VARCHAR2(5 BYTE), 
	"OBSERVACIONS" VARCHAR2(800 BYTE), 
	"EXPEDIENT" VARCHAR2(11 BYTE), 
	"REGAL1" VARCHAR2(5 BYTE), 
	"REGAL2" VARCHAR2(5 BYTE), 
	"TECNIC" VARCHAR2(10 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "T_SINTAGMA" ;
