--------------------------------------------------------
--  DDL for Table Z_TMP_VIPS_U_VIPS_REGALS
--------------------------------------------------------

  CREATE TABLE "SINTAGMA_U"."Z_TMP_VIPS_U_VIPS_REGALS" 
   (	"COMPTADOR" NUMBER(10,0), 
	"N_VIP" NUMBER(10,0), 
	"REGAL" VARCHAR2(5 BYTE), 
	"DATA_ENTREGA" DATE, 
	"ACCEPTAT" VARCHAR2(1 BYTE), 
	"MOTIU" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "T_SINTAGMA" ;
