--------------------------------------------------------
--  DDL for Table Z_TMP_RISPLUS_U_CONTACTES
--------------------------------------------------------

  CREATE TABLE "SINTAGMA_U"."Z_TMP_RISPLUS_U_CONTACTES" 
   (	"CONTACTEID" NUMBER(38,0), 
	"TRACTAMENT" VARCHAR2(50 BYTE), 
	"NOM" VARCHAR2(100 BYTE), 
	"COGNOMS" VARCHAR2(200 BYTE), 
	"CARREC" VARCHAR2(100 BYTE), 
	"EMPRESA" VARCHAR2(100 BYTE), 
	"DEPARTAMENT" VARCHAR2(100 BYTE), 
	"ADRECA" VARCHAR2(250 BYTE), 
	"DISTRICTE" VARCHAR2(100 BYTE), 
	"CODIPOSTAL" VARCHAR2(10 BYTE), 
	"MUNICIPI" VARCHAR2(100 BYTE), 
	"PROVINCIA" VARCHAR2(100 BYTE), 
	"PAIS" VARCHAR2(100 BYTE), 
	"TELEFONMOBIL" VARCHAR2(100 BYTE), 
	"TELEFONFIXE" VARCHAR2(100 BYTE), 
	"EMAIL" VARCHAR2(100 BYTE), 
	"INTERESSAT1" VARCHAR2(200 BYTE), 
	"INTERESSAT2" VARCHAR2(200 BYTE), 
	"PERTANYREPOSITORI" CHAR(1 BYTE), 
	"INSTALACIOID" NUMBER(38,0), 
	"DATAMODIF" DATE, 
	"USUARI" VARCHAR2(25 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "T_SINTAGMA" ;
