--------------------------------------------------------
--  DDL for Table Z_Z_CONSTRAINTS_ERRORES
--------------------------------------------------------

  CREATE TABLE "SINTAGMA_U"."Z_Z_CONSTRAINTS_ERRORES" 
   (	"SINTAGMA_TABLA" VARCHAR2(30 BYTE), 
	"SINTAGMA_ESQUEMA" CHAR(3 BYTE), 
	"SINTAGMA_TABLA_SINTAGMA" VARCHAR2(30 BYTE), 
	"SINTAGMA_TOTAL_CONSTRAINT" NUMBER, 
	"A0_TABLA" VARCHAR2(30 BYTE), 
	"A0_ESQUEMA" CHAR(3 BYTE), 
	"A0_TABLA_SINTAGMA" VARCHAR2(30 BYTE), 
	"A0_TOTAL_CONSTRAINT" NUMBER, 
	"A1_TABLA" VARCHAR2(4000 BYTE), 
	"A1_ESQUEMA" VARCHAR2(4000 BYTE), 
	"A1_TABLA_SINTAGMA" VARCHAR2(4000 BYTE), 
	"A1_TOTAL_CONSTRAINT" VARCHAR2(4000 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "T_SINTAGMA" ;
