--------------------------------------------------------
--  DDL for Package A0_02_CONTACTES_VIPS
--------------------------------------------------------

  CREATE OR REPLACE PACKAGE "SINTAGMA_U"."A0_02_CONTACTES_VIPS" AS 

  /* CONTACTES DE VIPS CON SECUENCIAS */ 
  
  
      ConstTelefonFix CONSTANT integer:=1; --Fijo
      ConstTelefonMobil CONSTANT integer:=2; --Móvil
      ConstTelefonFax CONSTANT integer:=3;  --Fax

      ConstSubjectePersona CONSTANT integer:=1; 
      ConstSubjecteEntitat CONSTANT integer:=2; 

      ConstContactePersonal CONSTANT integer:=1; 
      ConstContacteProfesional CONSTANT integer:=2; 

      ConstAMBIT_ALCALDIA CONSTANT integer:=1; 
      ConstAMBIT_PROTOCOL CONSTANT integer:=2; 
      
      ConstVISIBILITAT_PUBLICA CONSTANT integer:=1; 
      ConstVISIBILITAT_PRIVADA CONSTANT integer:=2; 
      ConstVISIBILITAT_ALCALDIA CONSTANT integer:=3; 
      
      ConstTipologia CONSTANT integer:=1; 
      
      ConstPRIORIDAD_SC CONSTANT integer:=1; 
      
      ConstNO CONSTANT integer:=0; 
      ConstSI CONSTANT integer:=1; 
      

       PROCEDURE RESETEATOR_TABLAS_AUX;       
       PROCEDURE RESETEATOR_TABLAS_SINTAGMA;       
       PROCEDURE RESETEATOR_SECUENCIAS;

       PROCEDURE SB01_CONTACTOS_ACTIVOS;
       PROCEDURE SB02_CONTACTOS_VIPS;
       PROCEDURE SB03_CONTACTES_ID;
       PROCEDURE SB04_SUBJECTES_ID;
       PROCEDURE SB05_CONTACTES_SIN_GENER;
       
     
       PROCEDURE SB30_TRACTAMENTS;
       PROCEDURE SB31_DM_TRACTAMENT;
     
      
     

       PROCEDURE SB50_CARRECS;
       PROCEDURE SB51_CARRECS_CONTACTES_REL;
       PROCEDURE SB52_CARRECS_CONTACTES_NULL;
       PROCEDURE SB53_CARRECS_CONTACTES;
       PROCEDURE SB55_DM_CARREC;       

       PROCEDURE SB60_ENTITATS;
       PROCEDURE SB61_ENTITATS_CODI_NULL;
       PROCEDURE SB65_DM_ENTITATS;
       PROCEDURE SB66_ENTITATS_CONTACTES;
       
       PROCEDURE SB70_SUBJECTES_DIFUNTS;
       PROCEDURE SB71_SUBJECTES_AMB_PRIORITAT;
       PROCEDURE SB72_SUBJECTES_VIPS; 
       PROCEDURE SB73_SUBJECTE_CONTACTE;
       PROCEDURE SB78_SUBJECTES;
       PROCEDURE SB79_ERR_SUBJECTE;
       
       
       PROCEDURE SB80_ADRECA_CONTACTE;
       PROCEDURE SB81_ADRECA_SUBJECTE;
       PROCEDURE SB82_DM_ADRECA;
       PROCEDURE SB83_ERR_ADRECA;
       
       PROCEDURE SB90_CONTACTES_PRINCIPALS;
       PROCEDURE SB91_DATA_ACT_CONTACTE;
       PROCEDURE SB92_TIPUS_CONTACTES;
       PROCEDURE SB93_CONTACTES_CONTACTES;
       PROCEDURE SB94_CONTACTES_SUBJECTES;
       PROCEDURE SB95_CONTACTES;
       PROCEDURE SB96_ERR_CONTACTES;
       
       PROCEDURE SB100_CORREUS_CONTACTES;
       PROCEDURE SB101_CORREUS_PRINCIPALS;
       PROCEDURE SB102_CORREUS_CONTACTES;

       PROCEDURE SB110_TELEFONS_TELEFON1;
       PROCEDURE SB111_TELEFONS_TELEFON2;
       PROCEDURE SB112_TELEFONS_MOBIL;
       PROCEDURE SB113_TELEFONS_FAX;
       PROCEDURE SB114_TELEFONS_TELEFON_P;
       
--       PROCEDURE SB115_CONTACTE_TELEFON;
       
       

       
       PROCEDURE SB120_CLASSIFICACIO;
       PROCEDURE SB121_DM_CLASSIFICACIO;
       
       PROCEDURE SB130_CLASSIF_CONTACTE;
       PROCEDURE SB131_CONTACTE_CLASSIFICACIO;

       PROCEDURE SB140_ACOMPANYANTS_VIPS;
       PROCEDURE SB141_ACOMPANYANTS;
  

END A0_02_CONTACTES_VIPS;

/
