--------------------------------------------------------
--  DDL for Package A0_01_INSERTS
--------------------------------------------------------

  CREATE OR REPLACE PACKAGE "SINTAGMA_U"."A0_01_INSERTS" AS 


  /* SE SUSTITUYE IDs originales por secuencias */  
     ConstUsuari_CREACIO varchar2(10) := 'SYSTEM';



PROCEDURE RESETEATOR_TABLAS; --OJO BORRAR TODAS LAS TABLAS.

PROCEDURE CLASSIF_ACTIVES;

PROCEDURE A0_DM_AMBIT;

PROCEDURE A0_DM_CONF_FUN_VISUALS;
--------------------------------------------------------
-- TRUCADA
--------------------------------------------------------

PROCEDURE A0_DM_ESTAT_TRUCADA;

PROCEDURE A0_DM_SENTIT_TRUCADA;

--------------------------------------------------------
-- CONTACTES
--------------------------------------------------------

PROCEDURE A0_DM_TIPUS_TELEFON;

PROCEDURE A0_DM_TIPUS_SUBJECTE;

PROCEDURE A0_DM_PRIORITAT;

PROCEDURE A0_DM_TIPOLOGIA_OBSEQUI;

PROCEDURE A0_DM_OBSEQUI;

PROCEDURE A0_DM_VISIBILITAT;

PROCEDURE A0_DM_TIPUS_CONTACTE;

PROCEDURE A0_DM_IDIOMA;

PROCEDURE A0_DM_TIPOLOGIA_CLASSIFICACIO;



PROCEDURE A0_DM_AFECTA_AGENDA;

PROCEDURE A0_DM_TIPUS_AMBIT;

PROCEDURE A0_DM_BARRI;

PROCEDURE A0_DM_SECTOR;

PROCEDURE A0_DM_DECISIO_ASSISTENCIA;

PROCEDURE A0_DM_RAO;

PROCEDURE A0_DM_ARTICLE;



--------------------------------------------------------
-- ACTES
--------------------------------------------------------

PROCEDURE A0_DM_ESTAT_CONFIRMACIO;

PROCEDURE A0_DM_TIPUS_VIA_INVITACIO;

PROCEDURE A0_DM_INICIATIVA_RESPOSTA;

PROCEDURE A0_DM_TIPUS_VIA_RESPOSTA;

PROCEDURE A0_DM_ESTAT_GESTIO_INVITACIO;

PROCEDURE A0_DM_ESTAT_GESTIO_ESPAIS;

PROCEDURE A0_DM_ESTAT_ELEMENT;

PROCEDURE A0_DM_PAS_ACCIO;

PROCEDURE A0_DM_TIPUS_AGENDA;

PROCEDURE A0_DM_ORIGEN_ELEMENT;

PROCEDURE A0_DM_TIPUS_DATA;


END A0_01_INSERTS;

/
