--------------------------------------------------------
--  DDL for Package A_99_SECUENCIAS
--------------------------------------------------------

  CREATE OR REPLACE PACKAGE "SINTAGMA_U"."A_99_SECUENCIAS" AS 

  /* Resetea las secuencias al último Valor +a */ 
  
  PROCEDURE SEQ_ACOMPANYANT;
  
  PROCEDURE SEQ_ADRECA;
  
  PROCEDURE SEQ_AGENDA_DELEGACIO;
  
  PROCEDURE SEQ_CONTACTE;
  
  PROCEDURE SEQ_CONTACTE_CLASSIFICACIO;
  
  PROCEDURE SEQ_CONTACTE_CORREU;
  
  PROCEDURE SEQ_CONTACTE_TELEFON;
  
  PROCEDURE SEQ_CONVIDAT;
  
  PROCEDURE SEQ_CONVIDAT_CORREU;
  
  PROCEDURE SEQ_DM_CARREC;
  
  PROCEDURE SEQ_DM_CLASSIFICACIO;
  
  PROCEDURE SEQ_DM_CONF_FUN_VISUALS;
  
  PROCEDURE SEQ_DM_DESTINATARI_PERSONA;
  
  PROCEDURE SEQ_DM_ENTITAT;
  
  PROCEDURE SEQ_DM_ESTAT_ACTE;
  
  PROCEDURE SEQ_DM_ORIGEN_ELEMENT;
  
  PROCEDURE SEQ_DM_PAS_ACCIO;
  
  PROCEDURE SEQ_DM_PRIORITAT_ELEMENT;
  
  PROCEDURE SEQ_DM_SERIE;
  
  PROCEDURE SEQ_DM_TIPUS_ACCIO;
  
  PROCEDURE SEQ_DM_TIPUS_ACTE;
  
  PROCEDURE SEQ_DM_TIPUS_AGENDA;
  
  PROCEDURE SEQ_DM_TIPUS_DATA;
  
  PROCEDURE SEQ_DM_TIPUS_TEMA;  
  
  PROCEDURE SEQ_DM_TRACTAMENT;
  
  PROCEDURE SEQ_DOSSIER;
  
  PROCEDURE SEQ_REGISTRE;
  
  PROCEDURE SEQ_SUBJECTE;
  
  PROCEDURE SEQ_TITULAR_DINS;
  
  


END A_99_SECUENCIAS;

/
