--------------------------------------------------------
--  DDL for Package MIGRACIO_VIPS_DANI
--------------------------------------------------------

  CREATE OR REPLACE PACKAGE "SINTAGMA_U"."MIGRACIO_VIPS_DANI" AS

     PROCEDURE INSERT_MESTRES;

     PROCEDURE B01_DIF_CONT_VIPS;
     PROCEDURE B02_DIF_CONT_PART_VIPS;
     PROCEDURE B03_CONTACTES_ID;
     PROCEDURE B04_CONTACTES_PART_ID;
          
     PROCEDURE B10_CORREUS_CONTACTES;
     PROCEDURE DANI_CORREUS_PRINCIPALS;
     PROCEDURE DANI_CORREUS_CONTACTES;
     
     PROCEDURE DANI_TELEFONS_NUMERICS;
     PROCEDURE DANI_TELEFON_PRINCIPAL;
     PROCEDURE DANI_CONTACTE_TELEFON;
     
     PROCEDURE DANI_ACOMPANYANTS_SUBJECTE;
     PROCEDURE DANI_TRACTAMENTS;
     PROCEDURE B30_SUBJECTES_DIFUNTS;
     PROCEDURE B32_SUBJECTES_AMB_PRIORITAT;
     PROCEDURE DANI_TIPUS_CONTACTES;
     PROCEDURE DANI_ADRECA_CONTACTE;
              
     
     PROCEDURE DANI_ENTITATS;
     PROCEDURE DANI_ENTITATS_CONTACTES;
     PROCEDURE DANI_CARRECS;
     PROCEDURE DANI_CARRECS_CONTACTES;
     
     PROCEDURE DANI_CREACIO_CONTACTES;
     PROCEDURE DANI_CONTACTES_PRINCIPALS;
     
     PROCEDURE DANI_DATA_ACT_CONTACTE;
     
     PROCEDURE DANI_CREATE_CLASSIFICACIO;
     PROCEDURE DANI_CLASSIF_CONTACTE;
     --PROCEDURE DANI_TELEFONS_NO_NUMERICS;
     
     PROCEDURE ACTUALITZAR_SEQUENCIES;

     PROCEDURE B35_CREACIO_SUBJECTES;
     
     PROCEDURE BORRAR_TODOS_DATOS;
     PROCEDURE RESET_SEQUENCES;
     PROCEDURE NYAPA_CLASSIFICACIONS;
        
END;

/
