--------------------------------------------------------
--  DDL for Package S_05_TEMAS_RISPLUS
--------------------------------------------------------

  CREATE OR REPLACE PACKAGE "SINTAGMA_U"."S_05_TEMAS_RISPLUS" AS 

 
  --   ConstAdreca CONSTANT integer:=30000; --25246
--   ConstContacte CONSTANT integer:=50000;  --26109

--   ConstContacteCorreu CONSTANT integer:=10000; -- 2414
--   ConstContacteTelefon CONSTANT integer:=10000; --3714
--   ConstCarrec CONSTANT integer:=10000; --Inicio 6025
--   ConstEntitat CONSTANT integer:=20000; -- 11306 entitat  

--   ConstSubjecte CONSTANT integer:=1500000; --1018026

--   ConstDestPersona CONSTANT integer:=0;
   
--   ConstTractament CONSTANT integer:=200; --107

--   ConstEntitatTrucada CONSTANT integer:=1; -- 1527860 entitat  
   
   ConstInstalacioAlcaldia CONSTANT integer :=30; -- Corresponde a ámbito Alcaldia
   
   ConstAMBIT_ALCALDIA CONSTANT integer:=1; 
   ConstAMBIT_PROTOCOL CONSTANT integer:=2;    
   
   
   ConstSI CONSTANT integer:=1; 
   ConstNO CONSTANT integer:=2; 
   
   ConstENTRADA CONSTANT integer:=1; 
   ConstSALIDA CONSTANT integer:=2; 
   
   ConstPart_1 CONSTANT integer :=1;
   ConstPart_2 CONSTANT integer :=2;
      
   ConstPersonal CONSTANT integer:=1; 
   ConstProfesional CONSTANT integer:=2; 
   
   ConstSebjectePersona CONSTANT integer:=1; 
   ConstSebjecteEntitat CONSTANT integer:=2; 
   
   
   ConstTRUECADAPEN CONSTANT integer:=1;    
   ConstTRUCADAPAS CONSTANT integer:=2;    
   
   ConstSALIDA CONSTANT integer:=1; 
   
   Const_ORIGENELEMENT_RANG CONSTANT integer:=1;
   Const_ORIGENELEMENT_CONCRETA CONSTANT integer:=4;
   
   Const_ESTAT_ELEMENT_CONCLUSIO CONSTANT integer :=1;
   
   ConstUsuari_CREACIO varchar2(10) := 'P469047';

   
   

   
   PROCEDURE RESETEATOR_TABLAS;
--   PROCEDURE RESETEATOR_SECUENCIAS;
   
   PROCEDURE SE001_PARTICIONES;
   PROCEDURE SE002_INSTALACIO_AMBITS_PART;
   PROCEDURE SE003_AMBITS;
   
   PROCEDURE SE010_DM_LLOC;
   PROCEDURE SE011_DM_DISTRICTE;
   PROCEDURE SE012_DM_TIPUS_TEMA;
   PROCEDURE SE013_DM_ESPECIFIC;

  PROCEDURE SE020_TIPUSACCIO_DMTIPUSACCIO;
  PROCEDURE SE021_DMTIPUSACCIO;
  PROCEDURE SE025_DM_SUBTIPUSACCIO;
  PROCEDURE SE026_DM_PASS_ACCIO;
  PROCEDURE SE027_TRANSICIO_TRAMITACIO;
   
  PROCEDURE SE030_DM_DESTI_DELEGACIO;   
  PROCEDURE SE031_DM_TIPUS_ELEMENT;
  PROCEDURE SE032_DM_DECISIO_AGENDA;  
  PROCEDURE SE033_DM_PRIORITAT_ELEMENT;
  PROCEDURE SE034_DM_PREFIX_ANY;
  PROCEDURE SE035_DM_TIPUS_SUPORT;

  
  PROCEDURE SE040_SERIESSUBSERIES;
  PROCEDURE SE041_DM_SERIES;   
  PROCEDURE SE042_DM_CATALEG_DOCUMENT;
  PROCEDURE SE043_DM_PREFIX;
 
   PROCEDURE SE090_DM_TIPUS_ARG;
    --*******************************************************************
   PROCEDURE SE110_ASPECTES_ACCIO;
   PROCEDURE SE111_ASPECTES_ELEMENT_PPAL;
   PROCEDURE SE112_ASPECTES_ELEMENT_SEC;
   PROCEDURE SE113_ASPECTES_DOSSIER;
   PROCEDURE SE114_ASPECTES;
   
   
    

   
   PROCEDURE SE120_DOSSIER;

   PROCEDURE SE130_TITULARSDINS_ASPECTE;
   
   PROCEDURE SE140_ELEMENT_PRINCIPAL;
   PROCEDURE SE141_ELEMENTS_PPAL_ASPECTES;
   PROCEDURE SE142_ELEMENT_PRINCIPAL;
   
   PROCEDURE SE150_ELEMENTS_SEC_ACCION;
   PROCEDURE SE151_RELAC_ELEMENTS_PPAL_SEC;
   
   
   PROCEDURE SE160_ACCION_ELEMENTS_PPALS;
   PROCEDURE SE161_ACCIONS_PART1;
   PROCEDURE SE162_ACCIONS_PART2;
   PROCEDURE SE163_ACCIONS_PART3; --CON USUARIOS INFORMADOS
   PROCEDURE SE164_ACCIONS_PART4;
   PROCEDURE SE165_ACCION;   

   PROCEDURE SE170_DOSSIER; 
   
   PROCEDURE SE180_ENTRADA_AGENDA; 
   
   PROCEDURE SE190_AGENDA_DELEGACIO;
   
   PROCEDURE SE200_CLASSIFICACIO_ARXIU;
   
   PROCEDURE SE210_ELEMENTS_RELACIONATS;
   
   PROCEDURE SE220_TITULAR_FORA;

END S_05_TEMAS_RISPLUS;

/
