--------------------------------------------------------
--  DDL for Package SINTAGMA_02_CONTACTES_CALIMA
--------------------------------------------------------

  CREATE OR REPLACE PACKAGE "SINTAGMA_U"."SINTAGMA_02_CONTACTES_CALIMA" AS 

  ConstVISIBILITAT_PUBLICA CONSTANT integer:=1; 
   ConstVISIBILITAT_PRIVADA CONSTANT integer:=2; 
   ConstVISIBILITAT_ALCALDIA CONSTANT integer:=3; 
   
   ConstAMBIT_ALCALDIA CONSTANT integer:=1; 
   ConstAMBIT_PROTOCOL CONSTANT integer:=2; 
     
   ConstALCALDIA CONSTANT integer:=1; 
   ConstPROTOCOL CONSTANT integer:=2;    
      
   ConstPersonal CONSTANT integer:=1; 
   ConstProfesional CONSTANT integer:=2; 
   
   ConstSubjectePersona CONSTANT integer:=1; 
   ConstSubjecteEntitat CONSTANT integer:=2; 
   
   
   ConstTRUECADAPEN CONSTANT integer:=1;    
   ConstTRUCADAPAS CONSTANT integer:=2; 
   
   
   ConstSALIDA CONSTANT integer:=1; 
   ConstENTRADA CONSTANT integer:=2;    
   
   ConstNO CONSTANT integer:=0; 
   ConstSI CONSTANT integer:=1; 
--   ConstEntitatTruc CONSTANT integer:=5000;    
   
   ConstRao_Altres CONSTANT integer:=1;    
   
   ConstTelefonFix CONSTANT integer:=1; --Fijo
   ConstTelefonMobil CONSTANT integer:=2; --Móvil
   ConstTelefonFax CONSTANT integer:=3;  --Fax
    
   /*DELETES DE TODO */
   PROCEDURE RESETEATOR_TABLAS_SINTAGMA;
   PROCEDURE RESETEATOR_TABLAS_AUX;   
   PROCEDURE RESETEATOR_SECUENCIAS;
   
   
   
   
   PROCEDURE SC001_NEW_TRACTAMENT;
   PROCEDURE SC002_DM_TRACTAMENT;

   PROCEDURE SC010_NEW_CARREC;
   PROCEDURE SC011_DM_CARREC;
   
   PROCEDURE SC020_NEW_ENTITAT_CONTACTE;
   PROCEDURE SC021_DM_ENTITAT_CONTACTE;
   PROCEDURE SC022_NEW_ENTITAT_TRUCADA;
   PROCEDURE SC023_DM_ENTITAT_TRUCADA;
   PROCEDURE SC024_DM_ENTITAT_TRUC_HIST;
   PROCEDURE SC025_DM_ENTITAT_TRUC_HIST;
   
   PROCEDURE SC030_SUBJECTE_UNIC_CONTACTES;
   
   PROCEDURE SC031_SUBJECTES_TIPO_PERSONA;
   PROCEDURE SC032_SUBJECTES_TIPO_ENTITAT;
   PROCEDURE SC033_NEW_SUBJECTES;
   PROCEDURE SC034_SUBJECTES;
   
   PROCEDURE SC040_ADRECAS; --- AQUÍ CONTACTE ES ID_CONTACTE
   PROCEDURE SC041_ADRECA; --- AQUÍ CONTACTE ES ID_CONTACTE
   
   PROCEDURE SC050_CONTACTES;
   PROCEDURE SC051_NEW_CONTACTES;
   
   PROCEDURE SC060_CORREUS_CONTACTES;
   PROCEDURE SC061_CORREUS_PRINCIPALES;
   PROCEDURE SC062_CORREOS_CONTACTOS;
   
   PROCEDURE SC070_TELEFONS_FIX;
   
   PROCEDURE SC090_TRUCADA_DESTINATARI;
   PROCEDURE SC093_INSERTAR_DM_DESTINATARI;
   
   PROCEDURE SC095_TRUCADAS_ACTIVES;
   PROCEDURE SC096_TRUCADAS_HISTORIC;
   
   PROCEDURE SC097_TRUCADAS;
   PROCEDURE SC098_HIST_TRUCADAS;
   
/*   
--PROCEDURE SC000_TABLAS_ESENCIALES;

PROCEDURE SC001_SUBJECTES_PERSON;
--PROCEDURE SC002_EXISTE_SUBJECTE;
--PROCEDURE SC003_NO_EXISTE_SUBJECTE;
--PROCEDURE SC004_SUBJECTES_REL_VIPS;
PROCEDURE SC002_SUBJECTES_ENTITAT;





--SE DAN DE ALTA TODOS LOS CONTACTES DE CALIMA
PROCEDURE SC030_TODOS_CONTACTES;    
--PROCEDURE SC031_CONTACTES_NOT_IN_SINTAGMA;


--PROCEDURE SC033_INSERT_ENTITAT_NO_EXISTE;
PROCEDURE SC034_ADRECA;
PROCEDURE SC035_ADRECA_CONTACTE;
PROCEDURE SC036_CONTACTE_CON_SUBJECTES;

--PROCEDURE SC040_DM_ENTITAT;
PROCEDURE SC040_SUBJECTES;
PROCEDURE SC041_SUBJECTE;
PROCEDURE SC042_CONTACTE;
PROCEDURE SC043_CONTACTE;

PROCEDURE SC050_CORREUS_CONTACTES;
PROCEDURE SC051_CORREUS_PRINCIPALES;
PROCEDURE SC052_CORREOS_CONTACTOS;
PROCEDURE SC055_TELEFONS_NUMERICS;
PROCEDURE SC056_TELEFON_PRINCIPAL;
PROCEDURE SC057_CONTACTE_TELEFON;

PROCEDURE SC090_ENTITATS_TRUCADA;
PROCEDURE SC091_DM_ENTITATS_TRUCADAS;
PROCEDURE SC092_TRUCADA_DESTINATARI;
PROCEDURE SC093_INSERTAR_DM_DESTINATARI;
PROCEDURE SC095_TRUCADAS_ACTIVES;
PROCEDURE SC096_TRUCADAS_HISTORIC;

PROCEDURE SC097_TRUCADAS;
PROCEDURE SC098_HIST_TRUCADAS;
*/

END SINTAGMA_02_CONTACTES_CALIMA;

/
