--------------------------------------------------------
--  DDL for Package Z_A01_INSERTS_CATALOGOS
--------------------------------------------------------

  CREATE OR REPLACE PACKAGE "SINTAGMA_U"."Z_A01_INSERTS_CATALOGOS" AS 

PROCEDURE A0_DM_TIPUS_TELEFON;

PROCEDURE A0_DM_TIPUS_SUBJECTE;

PROCEDURE A0_DM_AMBIT;

PROCEDURE A0_DM_CONF_FUN_VISUALS;

PROCEDURE A0_DM_PRIORITAT;

PROCEDURE A0_DM_TIPOLOGIA_OBSEQUI;

PROCEDURE A0_DM_OBSEQUI;

PROCEDURE A0_DM_VISIBILITAT;

PROCEDURE A0_DM_TIPUS_CONTACTE;

PROCEDURE A0_DM_IDIOMA;

PROCEDURE A0_DM_TIPOLOGIA_CLASSIFICACIO;

PROCEDURE A0_DM_SENTIT_TRUCADA;

PROCEDURE A0_DM_AFECTA_AGENDA;

PROCEDURE A0_DM_TIPUS_AMBIT;

PROCEDURE A0_DM_BARRI;

PROCEDURE A0_DM_SECTOR;

PROCEDURE A0_DM_DECISIO_ASSISTENCIA;

PROCEDURE A0_DM_RAO;

PROCEDURE A0_DM_ARTICLE;

--------------------------------------------------------
-- TRUCADA
--------------------------------------------------------

PROCEDURE A0_DM_ESTAT_TRUCADA;


--------------------------------------------------------
-- ACTES
--------------------------------------------------------

PROCEDURE A0_DM_ESTAT_CONFIRMACIO;

PROCEDURE A0_DM_TIPUS_VIA_INVITACIO;

PROCEDURE A0_DM_INICIATIVA_RESPOSTA;

PROCEDURE A0_DM_TIPUS_VIA_RESPOSTA;

PROCEDURE A0_DM_ESTAT_GESTIO_INVITACIO;

PROCEDURE A0_DM_ESTAT_GESTIO_ESPAIS;

PROCEDURE A0_DM_ESTAT_ELEMENT;


END Z_A01_INSERTS_CATALOGOS;

/
