--------------------------------------------------------
--  DDL for Package Z_C01_CALIMA_CONTACTES
--------------------------------------------------------

  CREATE OR REPLACE PACKAGE "SINTAGMA_U"."Z_C01_CALIMA_CONTACTES" AS 
     
   ConstVISIBILITAT_PUBLICA CONSTANT integer:=1; 
   ConstVISIBILITAT_PRIVADA CONSTANT integer:=2; 
   ConstVISIBILITAT_ALCALDIA CONSTANT integer:=3; 
   
   ConstAMBIT_ALCALDIA CONSTANT integer:=1; 
   ConstAMBIT_PROTOCOL CONSTANT integer:=2; 
     
   ConstALCALDIA CONSTANT integer:=1; 
   ConstPROTOCOL CONSTANT integer:=2;    
      
   ConstPersonal CONSTANT integer:=1; 
   ConstProfesional CONSTANT integer:=2; 
   
   ConstSebjectePersona CONSTANT integer:=1; 
   ConstSebjecteEntitat CONSTANT integer:=2; 
   
   
   ConstTRUECADAPEN CONSTANT integer:=1;    
   ConstTRUCADAPAS CONSTANT integer:=2; 
   
   
   ConstSALIDA CONSTANT integer:=1; 
   ConstENTRADA CONSTANT integer:=2;    
--   ConstEntitatTruc CONSTANT integer:=5000;    
   
   ConstRao_Altres CONSTANT integer:=1;    
   
    
   /*DELETES DE TODO */
   PROCEDURE RESETEATOR_TABLAS;
--   PROCEDURE RESETEATOR_SECUENCIAS;
   
PROCEDURE C00_TABLAS_ESENCIALES;

PROCEDURE C01_EXTRAER_SUBJECTES_PERSONAS;
PROCEDURE C02_EXISTE_SUBJECTE;
PROCEDURE C03_NO_EXISTE_SUBJECTE;
PROCEDURE C04_SUBJECTES_CALIMA_REL_VIPS;
PROCEDURE C05_EXTRAER_Subjectes_ENTITAT;

PROCEDURE C10_EXTRAER_ENTITAT;
PROCEDURE C11_EXISTE_ENTITAT_SUBJECTE;
PROCEDURE C12_NO_EXISTE_ENTITAT_SUBJECTE;

PROCEDURE C10BIS_EXTRAER_ENTITAT_CONTACT;
PROCEDURE C11BIS_EXIST_ENTITAT_CONTACTE;
PROCEDURE C12BIS_NO_EXISTE_ENTITAT_CONT;

PROCEDURE C18_ENTITATS_CALIMA;
PROCEDURE C19_ENTITATS_CONTACTES;

PROCEDURE C20_DM_ENTITATS_CALIMA; 


--PROCEDURE C13_INSERT_NEW_ENTITAT;
--PROCEDURE C13BIS_INSERT_NEW_ENTITAT_CONT;

PROCEDURE C21_NEW_CARREC; 
PROCEDURE C25_NEW_TRACTAMENT;

--SE DAN DE ALTA TODOS LOS CONTACTES DE CALIMA
PROCEDURE C30_TODOS_CONTACTES;    
--PROCEDURE C31_CONTACTES_NOT_IN_SINTAGMA;


--PROCEDURE C33_INSERT_ENTITAT_NO_EXISTE;
PROCEDURE C34_ADRECA_CALIMA;
PROCEDURE C35_ADRECA_CONTACTE;
PROCEDURE C36_CONTACTE_CON_SUBJECTES;

--PROCEDURE C40_DM_ENTITAT;
PROCEDURE C40_SUBJECTES_CALIMA;
PROCEDURE C41_SUBJECTE;
PROCEDURE C42_CONTACTE_CALIMA;
PROCEDURE C43_CONTACTE;

PROCEDURE C50_CORREUS_CONTACTES;
PROCEDURE C51_CORREUS_PRINCIPALES;
PROCEDURE C52_CORREOS_CONTACTOS;
PROCEDURE C55_TELEFONS_NUMERICS;
PROCEDURE C56_TELEFON_PRINCIPAL;
PROCEDURE C57_CONTACTE_TELEFON;

PROCEDURE C90_ENTITATS_TRUCADA;
PROCEDURE C91_DM_ENTITATS_TRUCADAS;
PROCEDURE C92_TRUCADA_DESTINATARI;
PROCEDURE C93_INSERTAR_DM_DESTINATARI;
PROCEDURE C95_TRUCADAS_ACTIVES_CALIMA;
PROCEDURE C96_TRUCADAS_HISTORIC_CALIMA;

PROCEDURE C97_TRUCADAS;
PROCEDURE C98_HIST_TRUCADAS;

END Z_C01_CALIMA_CONTACTES;

/
