--------------------------------------------------------
--  DDL for Package Z_E01_TEMAS_RISPLUS
--------------------------------------------------------

  CREATE OR REPLACE PACKAGE "SINTAGMA_U"."Z_E01_TEMAS_RISPLUS" AS 

    --   ConstAdreca CONSTANT integer:=30000; --25246
--   ConstContacte CONSTANT integer:=50000;  --26109

--   ConstContacteCorreu CONSTANT integer:=10000; -- 2414
--   ConstContacteTelefon CONSTANT integer:=10000; --3714
--   ConstCarrec CONSTANT integer:=10000; --Inicio 6025
--   ConstEntitat CONSTANT integer:=20000; -- 11306 entitat  

--   ConstSubjecte CONSTANT integer:=1500000; --1018026

--   ConstDestPersona CONSTANT integer:=0;
   
--   ConstTractament CONSTANT integer:=200; --107

--   ConstEntitatTrucada CONSTANT integer:=1; -- 1527860 entitat  
   
   ConstInstalacio CONSTANT integer :=30; -- Corresponde a ámbito Alcaldia
   
   ConstAMBIT_ALCALDIA CONSTANT integer:=1; 
   ConstAMBIT_PROTOCOL CONSTANT integer:=2;    
   ConstAMBIT_NADA CONSTANT integer:=99;    
      
   ConstPart_1 CONSTANT integer :=1;
   ConstPart_2 CONSTANT integer :=2;
      
   ConstPersonal CONSTANT integer:=1; 
   ConstProfesional CONSTANT integer:=2; 
   
   ConstSebjectePersona CONSTANT integer:=1; 
   ConstSebjecteEntitat CONSTANT integer:=2; 
   
   
   ConstTRUECADAPEN CONSTANT integer:=1;    
   ConstTRUCADAPAS CONSTANT integer:=2;    
   
   ConstSALIDA CONSTANT integer:=1; 
   
   Const_ORIGENELEMENT_RANG CONSTANT integer:=1;
   Const_ORIGENELEMENT_CONCRETA CONSTANT integer:=2;
   
   Const_ESTAT_ELEMENT_CONCLUSIO CONSTANT integer :=1;
   

   
   PROCEDURE RESETEATOR_TABLAS;
--   PROCEDURE RESETEATOR_SECUENCIAS;
   
   PROCEDURE E001_PARTICIONES;
   PROCEDURE E002_INSTALACIO_AMBITS_PART;
   PROCEDURE E003_AMBITS;
   
   PROCEDURE E010_DM_LLOC;
   PROCEDURE E011_DM_DISTRICTE;
   PROCEDURE E012_DM_TIPUS_TEMA;
   PROCEDURE E013_DM_ESPECIFIC;

  PROCEDURE E020_TIPUSACCIO_DMTIPUSACCIO;
  PROCEDURE E021_DMTIPUSACCIO;
  PROCEDURE E025_DM_SUBTIPUSACCIO;
  
   
  PROCEDURE E030_DM_DESTI_DELEGACIO;   
  PROCEDURE E031_DM_TIPUS_ELEMENT;
  PROCEDURE E032_DM_DECISIO_AGENDA;  
  PROCEDURE E033_DM_PRIORITAT_ELEMENT;
  PROCEDURE E034_DM_PREFIX_ANY;
  PROCEDURE E035_DM_TIPUS_SUPORT;

  
  PROCEDURE E040_SERIESSUBSERIES;
  PROCEDURE E041_DM_SERIES;   
  PROCEDURE E042_DM_CATALEG_DOCUMENT;
  PROCEDURE E043_DM_PREFIX;
   
  PROCEDURE E050_ESTAT_ELEMENT;
  PROCEDURE E051_DM_ESTAT_ELEMENT;
  
  
  PROCEDURE E060_PAS_ACCIO; 
  PROCEDURE E061_DM_PAS_ACCIO;
  

  PROCEDURE E070_TIPUS_AGENDA;  
  PROCEDURE E071_DM_TIPUS_AGENDA;  
    
  PROCEDURE E080_ORIGEN_ELEMENT;
  PROCEDURE E081_DM_ORIGEN_ELEMENT;
  
  --PROCEDURE E090_TIPUS_ARG;
  PROCEDURE E090_DM_TIPUS_ARG;
  
  PROCEDURE E100_TIPUS_DATA;
  PROCEDURE E101_DM_TIPUS_DATA;
  -- FIN CATÁLOGOS


    --*******************************************************************
    
   PROCEDURE E110_ASPECTES;
   
   PROCEDURE E120_DOSSIER;

   PROCEDURE E130_TITULARSDINS_ASPECTE;
   
   PROCEDURE E140_ELEMPRINCIPAL_REGISTRE;
   PROCEDURE E141_REGISTRE_PART1;   
   PROCEDURE E142_ELEMENT_PRINCIPAL;
   
   PROCEDURE E150_ELEMSECUNDARI_REGISTRE;
   PROCEDURE E151_REGISTRE_PART2;
   PROCEDURE E152_ELEMENTS_SECUNDARIS;
   
   PROCEDURE E160_ACCION_ELEMENTS_PPALS;
   PROCEDURE E161_ACCIONS_PART1;
   PROCEDURE E162_ACCIONS_PART2;
   PROCEDURE E163_ACCIONS_PART3; --CON USUARIOS INFORMADOS
   PROCEDURE E164_ACCIONS_PART4;
   PROCEDURE AUX_ACCION;   

--   PROCEDURE E170_DOSSIER; 
   
   PROCEDURE E180_ENTRADA_AGENDA; 
   
   PROCEDURE E190_AGENDA_DELEGACIO;
   
   PROCEDURE E200_CLASSIFICACIO_ARXIU;

END Z_E01_TEMAS_RISPLUS;

/
