--------------------------------------------------------
--  DDL for Package Z_Z99_SECUENCIAS
--------------------------------------------------------

  CREATE OR REPLACE PACKAGE "SINTAGMA_U"."Z_Z99_SECUENCIAS" AS 

  /* Resetea las secuencias al último Valor +a */ 
  
  PROCEDURE A0_SEQ_ACOMPANYANT;
  
  PROCEDURE A0_SEQ_ADRECA;
  
  PROCEDURE A0_SEQ_AGENDA_DELEGACIO;
  
  PROCEDURE A0_SEQ_CONTACTE;
  
  PROCEDURE A0_SEQ_CONTACTE_CLASSIFICACIO;
  
  PROCEDURE A0_SEQ_CONTACTE_CORREU;
  
  PROCEDURE A0_SEQ_CONTACTE_TELEFON;
  
  PROCEDURE A0_SEQ_CONVIDAT;
  
  PROCEDURE A0_SEQ_CONVIDAT_CORREU;
  
  PROCEDURE A0_SEQ_DM_CARREC;
  
  PROCEDURE A0_SEQ_DM_CLASSIFICACIO;
  
  PROCEDURE A0_SEQ_DM_CONF_FUN_VISUALS;
  
  PROCEDURE A0_SEQ_DM_DESTINATARI_PERSONA;
  
  PROCEDURE A0_SEQ_DM_ENTITAT;
  
  PROCEDURE A0_SEQ_DM_ESTAT_ACTE;
  
  PROCEDURE A0_SEQ_DM_ORIGEN_ELEMENT;
  
  PROCEDURE A0_SEQ_DM_PAS_ACCIO;
  
  PROCEDURE A0_SEQ_DM_PRIORITAT_ELEMENT;
  
  PROCEDURE A0_SEQ_DM_SERIE;
  
  PROCEDURE A0_SEQ_DM_TIPUS_ACCIO;
  
  PROCEDURE A0_SEQ_DM_TIPUS_ACTE;
  
  PROCEDURE A0_SEQ_DM_TIPUS_AGENDA;
  
  PROCEDURE A0_SEQ_DM_TIPUS_DATA;
  
  PROCEDURE A0_SEQ_DM_TIPUS_TEMA;  
  
  PROCEDURE A0_SEQ_DM_TRACTAMENT;
  
  PROCEDURE A0_SEQ_DOSSIER;
  
  PROCEDURE A0_SEQ_REGISTRE;
  
  PROCEDURE A0_SEQ_SUBJECTE;
  
  PROCEDURE A0_SEQ_TITULAR_DINS;

END Z_Z99_SECUENCIAS;

/
