--------------------------------------------------------
--  DDL for Package ZZ_FINAL
--------------------------------------------------------

  CREATE OR REPLACE PACKAGE "SINTAGMA_U"."ZZ_FINAL" AS 

      ConstTelefonFix CONSTANT integer:=1; --Fijo
      ConstTelefonMobil CONSTANT integer:=2; --Móvil
      ConstTelefonFax CONSTANT integer:=3;  --Fax

      ConstSubjectePersona CONSTANT integer:=1; 
      ConstSubjecteEntitat CONSTANT integer:=2; 

      ConstContactePersonal CONSTANT integer:=1; 
      ConstContacteProfesional CONSTANT integer:=2; 

      ConstAMBIT_ALCALDIA CONSTANT integer:=1; 
      ConstAMBIT_PROTOCOL CONSTANT integer:=2; 
      
      ConstVISIBILITAT_PUBLICA CONSTANT integer:=1; 
      ConstVISIBILITAT_PRIVADA CONSTANT integer:=2; 
      ConstVISIBILITAT_ALCALDIA CONSTANT integer:=3; 

PROCEDURE BORRAR_TODOS_DATOS;

PROCEDURE B01_DIF_CONT_VIPS;
PROCEDURE B02_DIF_CONT_PART_VIPS;
PROCEDURE B03_CONTACTES_ID;
PROCEDURE B04_CONTACTES_PART_ID;
PROCEDURE B05_CONTACTES_SIN_GENER;
PROCEDURE B30_TRACTAMENTS ;
PROCEDURE B50_CARRECS;
PROCEDURE B51_CARRECS_CONTACTES     ;
PROCEDURE B52_DM_CARREC   ;
PROCEDURE B60_ENTITATS ;
PROCEDURE B62_ENTITATS_CONTACTES   ;
PROCEDURE B70_SUBJECTES_DIFUNTS   ;
PROCEDURE B71_SUBJECTES_AMB_PRIORITAT;
PROCEDURE B72_SUBJECTES      ;
PROCEDURE B80_ADRECA_CONTACTE    ;
PROCEDURE B90_CONTACTES_PRINCIPALS;
PROCEDURE B91_DATA_ACT_CONTACTE  ;
PROCEDURE B92_TIPUS_CONTACTES;
PROCEDURE B93_CONTACTES ;
PROCEDURE B100_CORREUS_CONTACTES;
PROCEDURE B101_CORREUS_PRINCIPALS;
PROCEDURE B102_CORREUS_CONTACTES  ;
PROCEDURE B110_TELEFONS_NUMERICS ;
PROCEDURE B111_TELEFON_PRINCIPAL;
PROCEDURE B112_CONTACTE_TELEFON ;
PROCEDURE B120_CLASSIFICACIO;
PROCEDURE B121_CLASSIF_CONTACTE;
PROCEDURE B130_ACOMPANYANTS;

END ZZ_FINAL;

/
